### ISSUE TITLE
Light Theme: Project sort order reverts to one when project edited

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#100]
I have noticed that after a project has been created, and the sort order has been set, everything looks fine.

But if I go back in to edit the project and then save it, the sort order reverts to 1. Can this be fixed?

Screenshots aren't too useful, but for example, try looking at the Admin projects page 
http://steeplejacksworld.corbettresearchgroup.com/admin/projects
for the project "Tower Bell Carriage Replacement." You will see it is ranked #2 in its portfolio.

If you click edit (either from the Admin Projects screen or from looking at the dedicated project page), you will see that the sort order now is 1. If you save the project, the sort order is 1.

**Comment by acavanagh** [comment]
This one should be working now.

**Comment by meetinghouse** [comment]
Looks good, thanks.
