### ISSUE TITLE
Some of the sites don't load

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#101]
Andy, I've sent this question to Dan as well, because I'm not sure if it's a sys admin thing or a programmer thing. But when I went to login to graneymetaldesign.corbettresearchgroup.com this morning I received an error (attached below).

As I explore this further, I see that some of the sites I've set up in Forge show this same error, and some load just fine. It is not obvious to me what the difference is.

A couple of sites that load fine:
http://dawsoncolvert.corbettresearchgroup.com/
http://woodenstormwindows.corbettresearchgroup.com/

A couple of sites that give me the same error:
http://graneymetaldesign.corbettresearchgroup.com/login
http://graneymetaldesign.corbettresearchgroup.com/login

![screenshot 2015-03-24 at 11 00 38 am](https://cloud.githubusercontent.com/assets/5215893/6804730/a10593c0-d215-11e4-98bd-25fee3568768.png)

**Comment by acavanagh** [comment]
Should be all set now.  The way these sites are deployed and updated is a
little inconsistent.  Once the current round of changes are all settled and
I have some time, it would probably be worthwhile to take an hour or so and
streamline and update your deployment and update process.  Also might want
to implement monitoring so you get an alert if a site goes down or
something.

**Comment by meetinghouse** [comment]
Thank you for making the site accessible. Once things are settled, I do very much agree that having a good deployment procedure to avoid this type of thing would be great. If it keeps cropping up before then, maybe establishing such a procedure beforehand would be helpful. For now, I will label this as a "discuss first" issue (I wish there were some sort of "backburner" label!) but I will leave it open.
