### ISSUE TITLE
Google Analytics for two existing Bones sites

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#102]
Sort of related to Issue #90 , there is a current client who has two existing websites (not in the new software, obviously, but in Bones). 

The sites they own are
http://www.heatherandlittle.com
and
http://www.roofingandsheetmetal.ca

For both logins are demo_user/5GHid39QmHNc

They have requested that they have Google Analytics installed for those sites. 

The Tracking ID's are as follows:
heatherandlittle.com is Tracking Code UA-61166081-1
roofingandsheetmetal.ca is Tracking Code UA-61182463-1

Is it possible for you to set this up? I don't know which php documents need the code added to them, or I would perhaps venture to do it myself. If there's only one, it would be great to know which one so I could perhaps do it in the future. We don't want to be supporting these old sites forever, but at the moment I do still have to.

Let me know if this is possible or if it should go the Sys Admin.

**Comment by meetinghouse** [comment]
I neglected to add that John has told me this is a higher priority than other requests. Let me know what's possible here. Thanks.

**Comment by acavanagh** [comment]
Hi - I'd need to have access to the server to add the analytics code for those sites.  Where do those sites live?

**Comment by meetinghouse** [comment]
Right, of course. Sorry for not giving that to you.

I log in through WHM:
https://207.58.179.231:2087/
Username root
PW jYre9gV2S4bN

This gives you access to all the accounts, not the Heather and Little ones.

The account names for this issue are named heathera and roofinga

**Comment by acavanagh** [comment]
Hi John - I just checked in to this, and unfortunately I have absolutely no idea how to use WHM.  Adding the google analytics is easy, someone just has to post the following code in whatever template or files those sites are using:

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-XXXXX-X']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

- note that 'UA-XXXXX-X' gets replaced with the actual tracking numbers.
