### ISSUE TITLE
Light Theme: Error on navigating to About page from home page

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#104]
I am transferring data for a client. I've updated the About Us page, but I am unable to navigate to it from the left nav. I get the error below. I am able to get to it from the Admin Pages screen, though.

It may or may not be relevant, but there is a link in the About Us page to a portfolio I also created. This portfolio (called Our Approach) is not marked as published, so you can only get to it by clicking the link on the About Us page. I don't think that's the cause of the issue, because I've toggled that Portfolio between published and unpublished and that didn't affect the error, but I mention it because it is the only different thing about this About page I can think of.

![screenshot 2015-03-26 at 1 12 11 pm](https://cloud.githubusercontent.com/assets/5215893/6852262/ec4634a2-d3b9-11e4-8a5d-8477de787343.png)

**Comment by acavanagh** [comment]
Ah - due to a slight error, the light theme there was actually getting the pages page for the dark theme.  Those pages don't exist in the light theme, unless you create them.

**Comment by meetinghouse** [comment]
This is resolved, thanks. Closing.
