### ISSUE TITLE
Light theme: Code merge

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#106]
Here's the exchange you've been having so far over email with John. I will put further notes in a separate comment:

John wrote on 3-31-15:
"I write outside of Github in order to furnish some priorities on current issues.

Is it so that you have updated heatherandlittle.com and roofingandsheetmetal.ca with Google Analytics? We see data in the account. Let me know if this is not so.
preservationarts.corbettresearchgroup.com is still unable to upload an image. Please see what you can do.
Provision the website with the URL (.html) update, per our notes.
Push the compress Portfolios.
Install and push Google Analytics, across the board, installed "natively".
I furnish notes on these because they affect current User experience. Thanks!"

You wrote on 4-1-15:
"In working on these I realized that the old branch with the original code and the new branch with all the updates have drifted apart so much that they're basically incompatible and we're maintaining two different code bases.  I merged the few changes we'd made to the old 'light' theme into the 'blog' branch and updated preservationarts.corbettresearchgroup.com using that code.  I think it's solved most of the issues there.  In addition, I added a box on the setting page where you can add the User Account # for the site's google analytics, and it will fill that value in to the tracking script that I added to the main page template.

Before we roll this out to other sites, can you take a look at preservationarts.corbettresearchgroup.com and make sure that we didn't introduce any new issues with the change?  Once this is rolled out it should take care of 2, 4, and 5 above.  Number 1 has some comments in github, and 3 will be a server-wide change that I should be able to fit in soon."

**Comment by meetinghouse** [comment]
I would love to ask that all the code be pushed over to update all the light theme sites right now, but I am finding some issues with the preservationarts.corbettresearchgroup.com site. 

I see the toggle between dark and light theme is working (though not thoroughly tested yet). That is cool.

But Admin Pages is problematic now in the light theme because several of the pages now throw errors when clicked. They don't exist on the light theme side of things.

http://preservationarts.corbettresearchgroup.com/pages
![screenshot 2015-04-02 at 12 14 22 pm](https://cloud.githubusercontent.com/assets/5215893/6968079/e005cc0c-d931-11e4-84ee-4eac7fe682d6.png)

The ones that cause an error when clicked are:
Our Process
Testimonials
News & Awards

Here is an example of the error page generated:
http://preservationarts.corbettresearchgroup.com/our_process
![screenshot 2015-04-02 at 12 16 10 pm](https://cloud.githubusercontent.com/assets/5215893/6968105/16287a14-d932-11e4-8d81-c52b067170e6.png)

**Comment by acavanagh** [comment]
thanks for testing.  I'll fix those errors tonight.  let me know if you
find anything else in there that's blocking rolling this version out.
Also, thanks for bringing this back into github!

**Comment by meetinghouse** [comment]
You're welcome. I realized that I duplicated another issue I created a couple of days ago, so I'm just going to close that one out.

**Comment by meetinghouse** [comment]
Andy,
I'd like to get preservationarts.corbettresearchgroup.com updated, as a priority. This is a paying customer who is doing his own updating. Not sure if current issues are pushed there. The client has added issues Github #'s 120, 121 & 122.
Thanks,
John C.

**Comment by meetinghouse** [comment]
This issue is pretty much done now, I think. Thanks.
