### ISSUE TITLE
Admin Menus drag-and-drop not working

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#107]
On the preservationarts.corbettresearchgroup.com site, the drag-and-drop functionality on the Admin Menus page doesn't work.
http://preservationarts.corbettresearchgroup.com/menus
![screenshot 2015-04-02 at 12 55 28 pm](https://cloud.githubusercontent.com/assets/5215893/6968809/8e5ae580-d937-11e4-9bcd-887aa7427c13.png)

**Comment by meetinghouse** [comment]
Upon reviewing this screen, I see the drag and drop still doesn't have any effect. Interestingly, I think the whole screen is kind of non-useful and is disconnected from what the left sidebar actually is.

Can it be hidden from the user-level access role? It can still be visible to the admins, because who knows? It may prove to have a use sometime in the future. Thanks.

**Comment by KathJohnson** [comment]
This was discussed in the menu management issues in April 2016, and this issue is no longer needed. Closing.
