### ISSUE TITLE
Light Theme: Project images not displaying

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#110]
As I'm trying to transfer some client content, I'm finding that the images I add to projects through the Project Blowup Images Uploader aren't displaying. I don't know if it's because of old code on this website or what. I thought all the code updates had been pushed out, but I may be misunderstanding or misremembering. 

For instance, see this project:
http://blackburnrestoration.corbettresearchgroup.com/projects/13
![screenshot 2015-04-14 at 2 15 33 pm](https://cloud.githubusercontent.com/assets/5215893/7144034/c616bf1c-e2b0-11e4-961f-940f3532dd73.png)

I have uploaded the image on the edit page, though:
http://blackburnrestoration.corbettresearchgroup.com/projects/13/edit
![screenshot 2015-04-14 at 2 16 39 pm](https://cloud.githubusercontent.com/assets/5215893/7144060/e37dc4a6-e2b0-11e4-9387-6cb2f68e3b95.png)

**Comment by acavanagh** [comment]
The sites haven't all been updated yet. That should take care of the
problem. I don't have the time at the moment to do them all manually.  I'll
work out the deploy script for doing it through forge tonight, and then
send instructions over so you can update them easily yourselves through
forge.

**Comment by meetinghouse** [comment]
Thanks for fixing this up for Blackburnrestoration.corbettresearchgroup.com

Do you have that deploy script handy? I am working on some other sites now and I think they're all in a sort of random state of updatedness. If I have the newest deploy code I can update them as I start working on them. Thanks.

**Comment by acavanagh** [comment]
The deploy script in use by SHCONSTRUCTION2.CORBETTRESEARCHGROUP.COM is the
updated one.  To add the supplemental css file, you'll need another line
right after cd /home/forge/$CUSTOM_NAME.corbettresearchgroup.com that says:
~~~
touch public/assets/css/customProject.css
~~~

deploy once to create that file, then remove the line again.

HOWEVER, after some changes in the last round of work I should do the
deploy for the first time to make sure it goes ok.    After that the
automated script will work fine.  It'll only take me a few minutes per
site, and I'm available today until 4 and again after 8pm, so if you email
me a list of the ones you're thinking about working on today I'll make sure
they're ok for automatic deployment asap.

**Comment by meetinghouse** [comment]
Dangit, I wish I'd noticed this comment earlier! Well, at any rate, I'd like to work specifically coloralchemist.corbettresearchgroup.com and then moultoncustomdoor.corbettresearchgroup.com

I admit to being impatient and attempting to deploy coloralchemist with the above code you sent. It is messed up now, though there wasn't anything in there to save, so it doesn't matter. Even if we had to wipe out the site and re-deploy it from scratch that won't really cause a problem.

**Comment by acavanagh** [comment]
both these guys should be all set now.

**Comment by meetinghouse** [comment]
I know you are busy, but I wonder if you have the updated deployment code ready for me. I would love to be able to update all the sites myself in Forge (as well as deploy new ones). I'm sure you'd like to have those requests off your plate as well. Perhaps the problem in issues 116 needs to be resolved first. But as soon as you have that code scrap for me, or as soon as the one you referred to your notes here is good to go, please do let me know. I'll test it and use it right away. Thanks.

**Comment by acavanagh** [comment]
I believe that 116 is closed, I may have replied to a separate email about
it without closing the issue.  Actually, I just looked and I evidently
never sent the email saying it was fixed.

re:code snippet - I posted that in another ticket, I just have to see if I
can find it.  I'll start a spreadsheet tonight to keep track of which ones
are done, there's been a bunch of them already set up but there's too many
to keep track of without some records.  The problem is that because of the
extent of some of the recent changes, I have to add a file and do some
shenanigans manually before the update script will work.  Once a site is
done, you can the update script whenever.



For the other stuff, the code that's in

**Comment by meetinghouse** [comment]
Yuck, manual shenannigans, that is not fun. So are we currently stuck at me asking you for individual site updates then?

If so, I've got a some more (though Issue 116 is still unresolved, and may impact them as well):

-http://fitzgeraldtimberframes.corbettresearchgroup.com/
-http://armanirestoration.corbettresearchgroup.com/
-http://ctmason.corbettresearchgroup.com/

All these are functional, more or less, but project images in the "Subsequent Images Uploader" section don't display. That's the original problem from this issue, in fact, before there was some drift in subject matter. You did correct it for Blackburnrestoration, thanks.

**Comment by acavanagh** [comment]
ok, those sites should be all set now.  I'll update the deploy script for
them.  The manual shenanigans are annoying, but fortunately we only have to
do them once.

**Comment by meetinghouse** [comment]
I'm going to close this then, since all the updated sites display images now. Thanks.
