### ISSUE TITLE
Light Theme: Make image caption an unlimited size field

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#112]
A client is trying to move his content over to his new site, and he has requested a longer wordcount/character limit for the image caption field in the Project Blowup Images Uploader. What is the current limit, and can it be increased or removed entirely?

http://steeplejacksworld.corbettresearchgroup.com/projects/5/edit
![screenshot 2015-04-16 at 2 32 50 pm](https://cloud.githubusercontent.com/assets/5215893/7188410/7eaaec8e-e445-11e4-86d9-0f00a1aa8748.png)

**Comment by meetinghouse** [comment]
Andy,

I write to offer guidance in response to your email questions:

Our existing "Bones" software permits long captions, if there is any guidance for you there.

If you can establish an arbitrary limit, say 80 words, I think that will cover our needs, based upon my review of presarts content. (NOTE: This can be pushed throughout light (and dark), as I think presarts is on the long end of the requirement.)

There is no need to permit paragraph returns. One single line, only.

Failing the above, per Charles K., your proposed "Read More..." dropdown convention will suffice.

I look forward to your comments and questions.

Best,

John C.

**Comment by acavanagh** [comment]
Hi John - permitting longer captions isn't an issue, it's displaying them
within your existing image display without throwing off the formatting that
we have to figure out.  I think that limiting to 80 words, no line breaks
and setting all of the image blocks to the same height will probably look
ok.  I can implement that and you can see what you think.

**Comment by meetinghouse** [comment]
Andy,

Thanks, sounds like it will work fine. The Users will have to work within...

I just sent you an "error" screenshot, which I suspect was caused by your
presence on the server...


Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748

**Comment by acavanagh** [comment]
Check out these and see what you think:
http://preservationarts.corbettresearchgroup.com/chemical_cleaning

**Comment by meetinghouse** [comment]
Andy,
Looks fine for an 80 wd caption. How about when it is a 0 wd caption? Is there a way to:
#1 collapse the display area allotted for 80 wds when less-than-80 are entered or
#2 allow some specification of the default word length
Let me know what you think.
Best,
John C.

**Comment by meetinghouse** [comment]
Actually, Andy, John and I (Katherine) just looked at this on the preservationarts site and it looks fine. Thank you for the change.

**Comment by acavanagh** [comment]
This is on the priority list, but it's also closed and commented as looks fine.  should we remove it from the list?

**Comment by meetinghouse** [comment]
Closed, indeed. Take it off the list.


Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748
