### ISSUE TITLE
houzz badge or button

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#113]
Andy, 
At Admin Settings in the UI, please add social media option Houzz. Let me know if you need me to furnish a button, but it looks like you may have established a convention for same.
John C.

**Comment by acavanagh** [comment]
Hi - I will need an image to use for the button.  I don't have houzz one
that matches.

**Comment by meetinghouse** [comment]
Andy,
Been to their website and to Google images, this was the best I could find.
Best,
John C.


Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748

**Comment by acavanagh** [comment]
fixed in theblog branch, need to update a site as an example

**Comment by acavanagh** [comment]
this is done, you can see it on any of the recently deployed sites such as:
http://woodwindowworkshop.corbettresearchgroup.com/settings/1/edit

**Comment by meetinghouse** [comment]
I see it. It looks great and seems to work fine. Thanks!
