### ISSUE TITLE
Banner question.

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#114]
Andy,
Question only, light theme banners, what would it take (or is it feasible) to install the option to un-display all banners on selected pages? Or, if it is easier, ALL pages EXCEPT Home?
Thanks,
John C.

**Comment by meetinghouse** [comment]
In addition to this question from John, I notice that on the blackburnrestoration.corbettresearchgroup.com site, if I have more than one image uploaded as a banner, and set to be active, all of a sudden I don't see any banner at all.

I believe the Blackburn site is the most up-to-date, and I don't remember having this problem before, so I'm asking about it now before we roll all the most updated code to all the other sites too.

Screenshots:
Both banners uploaded and set to active:
http://blackburnrestoration.corbettresearchgroup.com/banners#banner-header
![screenshot 2015-04-30 at 2 22 35 pm](https://cloud.githubusercontent.com/assets/5215893/7419639/64723340-ef44-11e4-8a4b-034db0407f4f.png)

No banner at all showing on the homepage:
http://blackburnrestoration.corbettresearchgroup.com/
![screenshot 2015-04-30 at 2 23 13 pm](https://cloud.githubusercontent.com/assets/5215893/7419648/74844b38-ef44-11e4-93b8-991978b6f651.png)

**Comment by acavanagh** [comment]
fixed now.

**Comment by meetinghouse** [comment]
Thanks for the bux fix, by the way. It looks great. The question about how feasible it is to hide the banner on all pages other than home is still outstanding. I'm just putting this note in as a sort of reminder to both of us.

**Comment by acavanagh** [comment]
Do you want to always hide the banner on all pages other than the home page, or to have it as an option?

**Comment by meetinghouse** [comment]
It would be nice to have the option. Can you quote the difference between the two choices?

**Comment by acavanagh** [comment]
removing it completely would take maybe 20 minutes, making it optional would be more like an hour.

**Comment by meetinghouse** [comment]
John,

Here's Andy's quote on hiding the banner on all pages other than the
homepage. Let me know which direction you'd like to go (or you could just
put it in the Issue, too, as a comment. Either way).

Sincerely,

Katherine Johnson, Content Developer
The Custom Building & Restoration Trades Directory
<http://www.restorationtradesdirectory.com/>
http://www.restorationtradesdirectory.com
(413) 584-0288

Published by:
Corbett Research Group <https://mail.google.com/>
"Building Websites that Work - - for the Building Artisans."
http://www.restorationtrades.com

**Comment by KathJohnson** [comment]
John B, this is an older issue that has come up again and is being requested by a client. You can see some of the back-and-forth on specs with Andy from last year. Is this something that is in your skillset to handle?

**Comment by jboz62** [comment]
@KathJohnson On the second option (ALL pages EXCEPT Home) did you mean that it would display on the homepage ONLY or not on the homepage and display on all the other pages?

I can take a look at the code and see if this is something I can handle.

**Comment by meetinghouse** [comment]
I mean the user should have the option for the banner to either (a) display
on all pages of the site, as it does now, or (b) display ONLY on the
homepage and not on any other pages.

I hope that's clearer.

Sincerely,
Katherine Johnson, Research Director
Corbett Research Group
http://www.restorationtrades.com
"Web Marketing that Works"

Publishers of:

The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

The Building Arts Notebook, "Journal of the Guild of Building Artisans"
http://buildingartisansguild.com/

Email:  katherine@restorationtrades.com
Phone: (413) 475-3154

**Comment by jboz62** [comment]
Thanks for the clarification, Katherine. Without having to change any code, it’s possible to just use CSS to hide it on all the other pages and then make it display on the homepage only. I can give you the styles to add to the custom stylesheet when needed. If you want to go with a way to do this on the user level, we’d have to do some programming. Let me know which way you want to go and we can plan a strategy for that.

Thanks,
John
--
John Bozaan
Bozaan Design
413-437-0097
www.bozaandesign.com <http://www.bozaandesign.com/>

**Comment by KathJohnson** [comment]
This is being done for the moment with CSS on a site-by-site basis. That seems to work fine, so I am closing this issue.
