### ISSUE TITLE
Light Theme: About Page Edit screen goes to dark theme

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#115]
Thanks for getting Coloralchemist ready to use. 

As I was updating it, though, I noticed that when I go to edit the About page, it takes me to the dark theme. The view screen is light theme, but it is a bit confusing to suddenly jump to dark theme just for that page:

Here's the About Page:
http://coloralchemist.corbettresearchgroup.com/about
![screenshot 2015-05-05 at 12 11 35 pm](https://cloud.githubusercontent.com/assets/5215893/7477134/e86d534e-f31f-11e4-9a63-28e7b579bfb6.png)

Here's the edit screen for the About Page:
http://coloralchemist.corbettresearchgroup.com/pages/2/edit
![screenshot 2015-05-05 at 12 12 12 pm](https://cloud.githubusercontent.com/assets/5215893/7477158/faffaff2-f31f-11e4-8190-4b23ff58cefe.png)

**Comment by acavanagh** [comment]
should be fixed now

**Comment by meetinghouse** [comment]
Sure is, looks good. Thanks.
