### ISSUE TITLE
Light Theme: Error when adding subsequent images to project

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#116]
Sorry here's another issue. There are actually two related items here in this same issue.

On the Project creation screen (and the edit screen, same either way) there is a problem with the image uploader section.

1. It used to have two image uploader sections: Project Default Image Uploader, and Project Blowup Image Uploader. It now has three, like in the dark theme, and it is kind of confusing. Can we drop the Tile uploader from the light theme and go back to the older light theme verbiage easily?

2. More to the immediate point, I'm not able to save a project with any images in the subsequent image uploader section. I don't remember seeing this problem before.

Here's the edit screen where I'm uploading images:

http://coloralchemist.corbettresearchgroup.com/projects/15/edit
![screenshot 2015-05-05 at 12 37 04 pm](https://cloud.githubusercontent.com/assets/5215893/7477686/755e7db6-f323-11e4-9904-c8f733ac0107.png)

Here's the error screen when I click "Update Project"
http://coloralchemist.corbettresearchgroup.com/projects/15
![screenshot 2015-05-05 at 12 37 47 pm](https://cloud.githubusercontent.com/assets/5215893/7477703/8edb5a16-f323-11e4-8a80-457144a2b7b5.png)

**Comment by meetinghouse** [comment]
Actually, I get this error even if I just change the font of the main body section. So the error may have nothing to do with the image uploader.

**Comment by acavanagh** [comment]
Should be all set now, can you test again?

**Comment by meetinghouse** [comment]
Hmm, I'm still getting an error, but it seems to be a slightly different one. What I did to test was open the project, change the font size in the Main Body, and click Update Project.

http://coloralchemist.corbettresearchgroup.com/projects/15

![screenshot 2015-05-06 at 1 32 40 pm](https://cloud.githubusercontent.com/assets/5215893/7499266/7b66b774-f3f4-11e4-89f6-cf8f8703592d.png)

**Comment by acavanagh** [comment]
can you refresh a couple times and try again?  I just went through those
steps with no error.

**Comment by meetinghouse** [comment]
Cleared my cache and the errors are gone now. Also, subsequent project images upload and display fine now.

There is still the confusing problem of the three dark theme uploaders showing up. From my first comment in this issue, the light theme project create and edit screens:

"used to have two image uploader sections: Project Default Image Uploader, and Project Blowup Image Uploader. It now has three, like in the dark theme, and it is kind of confusing. Can we drop the Tile uploader from the light theme and go back to the older light theme verbiage easily?"

**Comment by acavanagh** [comment]
I thought that John had requested that change to be for the light theme
also.  If that was a misunderstanding I can make them different on a
per-theme basis.

**Comment by meetinghouse** [comment]
I just checked in with John, and maybe there is a miscommunication here.

If it's easier for you, the only thing that really needs to change is that the Tile Uploader section should not be present in the light theme. I was able to upload an image through it successfully, but there's nowhere for it to display in light theme, so it doesn't make sense to have it there. If you'd like to leave the other two sections as they are, it is fine, I can just adjust the help text to reflect the labels from the dark theme.

So either hiding the tile uploader from light theme only, or reverting back entirely to the original look of the project image uploaders is fine. Just let me know which you go with.

**Comment by acavanagh** [comment]
went with hiding the tile uploader on light.

**Comment by meetinghouse** [comment]
Andy,
The Tile Uploader still displays on the Light Theme UI preservationarts.corbettresearchgroup.com. This is a priority copy as our client is attempting to populate.
Best,
John C.

![untitled](https://cloud.githubusercontent.com/assets/5215893/7573220/2b661cd6-f7f2-11e4-93e5-9f58a882e5e3.jpg)

**Comment by meetinghouse** [comment]
This is all resolved now. Thanks.
