### ISSUE TITLE
Mobile friendly: Stacking change request

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#117]
In reviewing some of the new websites on smaller screens, or on a re-sized browser screen, I see some inconsistency in breakpoints. As an example, graneymetaldesign.corbettresearchgroup.com on a small screen shows the left sidebar stacked just below the banner, in the center. The main body can then fill the screen below that. That's good, and what I'd like to see. Here is a screenshot of that (kind of hard to see, sorry.):

![screenshot 2015-05-07 at 11 33 03 am](https://cloud.githubusercontent.com/assets/5215893/7519067/f08df162-f4ac-11e4-9070-d8fbb6cec220.png)

All the other recently updated sites I've checked, however, do not break this way. The left sidebar links are still in the left sidebar, even on a small screen, and the main body content is squeezed into a very narrow column. Not so good. For instance, ctmason.corbettresearchgroup.com and blackburnrestoration.corbettresearchgroup.com are like that. Here's a shot of blackburn:

![screenshot 2015-05-07 at 11 35 32 am](https://cloud.githubusercontent.com/assets/5215893/7519113/334cfb4c-f4ad-11e4-909e-3c5315259b35.png)

Why are they breaking differently, and can they be all made to break the same way, with the left sidebar stacking in the center under the banner when on a smaller screen in portrait orientation?

**Comment by acavanagh** [comment]
This is fixed.  I updated the two sites you mention above.  I'm slowly
moving them all over to the new codebase.  Current list is here:
https://docs.google.com/spreadsheets/d/1wtWio8D1WYI5WVmxyqPfPXbVbSbITIR8_ZB3aqEtBWQ/edit?usp=sharing

**Comment by meetinghouse** [comment]
This is good and it can be rolled out.
