### ISSUE TITLE
Mobile friendly: Logo resizing

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#118]
Here's another inconsistency I've found with the way the sites render on smaller screens. The logo above the banner should resize to fit the screen without running over to the right. When I hit any of the new sites, at first this is not happening, which it should be.

Oddly, for one site, I've found that switching to landscape orientation, then back to portrait orientation fixes the problem. For other sites, there's nothing I've found to get the logo to fit on the screen.

I don't know how to get a screenshot of this, as I can't get the orientation to change by flipping my Chromebook around. But if you look on a mobile screens, you should see the following:

graneymetaldesign.corbettresearchgroup.com will resize the logo after toggling between orientations.

blackburnrestoration.corbettresearchgroup.com and coastalclockandchime.corbettresearchgroup.com have an over-large logo no matter what.

Is it possible to fix this so the logo resizes immediately upon loading?

**Comment by acavanagh** [comment]
@meetinghouse is there a site that I can review this on?  It seems our previous test site (stepplejacksworld) has been commandeered for a client?

**Comment by meetinghouse** [comment]
Yes, of course. How about 
http://example103.corbettresearchgroup.com/

I know it's not updated to the latest software, which is annoying, and I'm sorry that will have to be done. I should hope that one will be forever safe from getting co-opted (although that's what I thought about steeplejacksworld, too.)

Let me know if that won't work for you.

**Comment by acavanagh** [comment]
should be fixed, check here: http://example103.corbettresearchgroup.com/

**Comment by meetinghouse** [comment]
Lookee there! That is super rad. Can we push it out to all sites?

**Comment by acavanagh** [comment]
yep

**Comment by meetinghouse** [comment]
This is working fine, so I'm closing. Thanks.
