### ISSUE TITLE
Light theme: Tags showing in project create/edit screens

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#119]
When I'm in the create or edit screen for projects on coloralchemist.corbettresearchgroup.com, there is a tags field, which doesn't really do anything in the light theme. Can it be removed?

I'm seeing it in all the sites I've been working on: preservationarts, ctmason, blackburnrestoration.

**Comment by acavanagh** [comment]
tag field is removed from the light theme.  You can see it (or not see it,
I guess) at coloralchemist.corbettresearchgroup.com.  The other sites need
to get updated to reflect the change.  Most of the ones we've been talking
about can be updated via forge.  There's a spreadsheet where I'm keeping
track here:
https://docs.google.com/spreadsheets/d/1wtWio8D1WYI5WVmxyqPfPXbVbSbITIR8_ZB3aqEtBWQ/edit?usp=sharing

**Comment by meetinghouse** [comment]
Thanks, this is good. I look forward to having it across all the sites.

I took the liberty of adding a column to your spreadsheet, which you can
use and delete as you wish. It's column E and it's for prioritizing
updates. I put an x in that column for all current clients who we'd like to
get moved over, and "xxx" for the four who we are actively working with
right now.

So the xxx are top priority, followed by the x, and then everybody else
whenever.

Sincerely,

Katherine Johnson, Content Developer
The Custom Building & Restoration Trades Directory
<http://www.restorationtradesdirectory.com/>
http://www.restorationtradesdirectory.com
(413) 584-0288

Published by:
Corbett Research Group <https://mail.google.com/>
"Building Websites that Work - - for the Building Artisans."
http://www.restorationtrades.com

**Comment by acavanagh** [comment]
thanks for the edit.  all of your xxx sites are updated now.  I should be able to get the rest done over the next few days.

**Comment by meetinghouse** [comment]
Thanks. I see the tags are gone from the light theme, and so I'm going to close this issue.

**Comment by acavanagh** [comment]
I see you reopened this - are the tags showing up in the light theme again?

**Comment by meetinghouse** [comment]
Yeah, they are. Funny, I typed up a comment on this, but I apparently didn't save it. Sorry for the confusion.

The tags field is showing on the Project Create screen only. It isn't on the Project edit screen or any of the Portfolio screens. Here's a screenshot of the Project Create screen at http://bronzedoorrestoration.corbettresearchgroup.com/projects/create

![screenshot 2015-08-20 at 11 18 12 am](https://cloud.githubusercontent.com/assets/5215893/9387162/3e9cc9dc-472d-11e5-8ce6-a5c8e967cdae.png)

**Comment by acavanagh** [comment]
This should be all set now.  see http://bronzedoorrestoration.corbettresearchgroup.com/projects/create

**Comment by meetinghouse** [comment]
That looks better. Many thanks. Closing this one now.
