### ISSUE TITLE
Light theme, edit Project img Captions.

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#120]
Andy, 
Please forgive if this thread has been started elsewhere.
Logged in as testit >> Portfolio >> Masonry Cleaning >> Masonry Cleaning With Water Only.
http://preservationarts.corbettresearchgroup.com/water_only_cleaning
Please enable Edit for Captions. Attempt to Edit causes Caption to delete.
Thanks.
John C.

**Comment by meetinghouse** [comment]
Andy, 
Perhaps I should note that the updated should be pushed everywhere, Dark theme, Light theme, all Captions should Edit.
Best,
John C.

**Comment by acavanagh** [comment]
this fix is in place, you can see it on preservation arts

**Comment by meetinghouse** [comment]
This looks great. We can roll it out. Thanks.
