### ISSUE TITLE
Light theme, Project image order display in UI same as page.

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#121]
Andy, 
(Logged in as testit >> Portfolio >> Masonry Cleaning >> Masonry Cleaning With Water Only.
http://preservationarts.corbettresearchgroup.com/water_only_cleaning)

In the UI, the Project Images are displayed in non-consecutive order, as follows: 1, 10, 16, 17, 2, 21, 3, 4, etc. This is confusing to the User as it is not as displayed on the page. In the UI, can the Project Images display in consecutive Image Position order? (Using above example, 1, 2, 3, 4, 10, 16, 17, 21.)

Thanks.
John C.

**Comment by acavanagh** [comment]
These should be sorting in natural order now

**Comment by meetinghouse** [comment]
That looks good, we can roll that out. Thanks.
