### ISSUE TITLE
Light theme, Image Position dropdown install request. 

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#122]
Andy,
(Logged in as testit >> Portfolio >> Masonry Cleaning >> Masonry Cleaning With Water Only.
http://preservationarts.corbettresearchgroup.com/water_only_cleaning)

Image Position field permits entry of any number, regardless of number of images in the Project. Image Position field permits any duplicates of numbers. They could all be "9", for example. Suggest that it would be clearer for the User if the display positions of all created Project Images were displayed in a dropdown.  The only option would be consecutive, Created Image Positions, starting with "1". If there were 4 Image Positions, they would be "1, 2, 3, 4" in the dropdown. If I selected "3" for a given Image Position, 1 and 2 would maintain their position, the Edited Image would become 3, 3 would become 4, 4 would become 5, etc.

Thanks,
John C.

**Comment by meetinghouse** [comment]
Katherine here, just adding some notes. For clarity, you can look at this page from Bones that shows how the option for image position works on the currently live sites.
![screenshot 2015-05-12 at 11 50 35 am](https://cloud.githubusercontent.com/assets/5215893/7591654/250a71f6-f89d-11e4-9f8d-0effababe3d9.png)

So, as you'll see here, the text for the position dropdown field is "Select position (currently 2):" That is useful. Can each image in the project edit screen in the new sites be similar?

This dropdown change should apply when adding a new image through the "Project Subsequent Images Uploader" on both the project edit and project create screens.

Is this feasible?

**Comment by acavanagh** [comment]
it's feasible, but it's not something I'm going to have the time for soon.  I'm actually looking for another developer to work with on this project so you don't get hung up by my schedule.

**Comment by meetinghouse** [comment]
OK. This should apply for both light and dark themes, by the way. The title says light theme, but it applies in both.  I will be creating similar issues also for two other places where sorting is done. I'll link them to this issue.

**Comment by acavanagh** [comment]
@serundeputy are you interested in taking this one?

**Comment by meetinghouse** [comment]
I am closing this issue, because there are other issues that duplicate it.
