### ISSUE TITLE
Light Theme: Need more numbers in sorting dropdown for Project order

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#125]
When creating or editing a project, the user can select the order in which the project will appear in its portfolio with a dropdown list of numbers 1-10.

We need more numbers! Can this be increased to, say, 50?

To see an example, see http://coastalclockandchime.corbettresearchgroup.com/projects/21/edit
![screenshot 2015-05-19 at 12 20 52 pm](https://cloud.githubusercontent.com/assets/5215893/7708097/86483ac8-fe21-11e4-8c74-5c572304031e.png)

**Comment by acavanagh** [comment]
This should be set now.

**Comment by meetinghouse** [comment]
Looks good, thanks.
