### ISSUE TITLE
Light Theme: Mobile Issue

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#131]
Related to the stacking issue for small screens that is already resolved, I notice that the content in the main body of the home page has pretty wide margins still. It looks like they're about the same as they were when the links were in the left sidebar. 

Can it be changed so that the content fills the width of the screen?

Here's a screenshot of an approximate smartphone view of preservationarts.corbettresearchgroup.com to show what I mean.

![screenshot 2015-05-20 at 12 04 06 pm](https://cloud.githubusercontent.com/assets/5215893/7730454/751ab95c-fee8-11e4-86c3-db1510a4e143.png)

**Comment by acavanagh** [comment]
I believe this is resolved but need to review

**Comment by acavanagh** [comment]
Should be set with this one now, see preservationarts.corbettresearchgroup.com.  you will need to update sites to the latest code to see the change.

**Comment by meetinghouse** [comment]
The margins look good to me. I've asked John to also take a look to make sure it's what he wants, too. I'll let you know, thanks.

**Comment by meetinghouse** [comment]
This is much improved, I'm closing this issue, as there are other current issues dealing with appearance on mobile devices. Thanks.
