### ISSUE TITLE
Software updates for specific sites

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#132]
Hi, Andy. Thanks for updating the top-priority sites identified so far. I've worked with all those sites getting them ready for launch soon. Now we have another batch of six higher priority sites to have updated so we can then update their content.

I've marked them on your spreadsheet (https://docs.google.com/spreadsheets/d/1wtWio8D1WYI5WVmxyqPfPXbVbSbITIR8_ZB3aqEtBWQ/edit?usp=sharing) with "please update 5.26.15" in the higher priority column (Column E).

Please note I needed to add one site to your spreadsheet that I didn't find there. So at the very bottom I added 

tradbuild.corbettresearchgroup.com

I'm just pointing this one out since it was't on your original spreadsheet and I don't know if there is some special case for it.

Can you just let me know when these six sites are ready to go?

**Comment by meetinghouse** [comment]
I lied! There are two more sites I've also marked. So we're looking for eight to be updated as soon as possible.

**Comment by acavanagh** [comment]
These guys all are updated now, and any future deployments can be done
quickly through forge.  Check them out when you get a chance and let me
know if I missed any.

-Andy

**Comment by meetinghouse** [comment]
Yay! Great news!

1.  Looks like you did miss three:

   - fitzgeraldtimberframes.corbettresearchgroup.com
   - bronzedoorrestoration.corbettresearchgroup.com
   - masonryrestoration.corbettresearchgroup.com


2. Here are five more, our next priority group:

   - westonmillwork,corbettresearchgroup.com
   - thayer52.corbettresearchgroup.com
   - woodwindowworkshop.corbettresearchgroup.com
   - woodenstormwindows.corbettresearchgroup.com
   - heartwoodcarpentryrenovation.corbettresearchgroup.com

3.  Requesting confirmation on where the most current deployment code is.
According to my records, it's, well, dangit, I don't know. I remember this
info is hidden in a GitHub comment somewhere, but my searches aren't
turning it up so far. So, at whatever point, I'll need to know where to
find the deploy code (including the line for the supplemental css file).
Then I'll do some test runs of deployment and update my procedure as far as
I can for now.


Sincerely,

Katherine Johnson, Content Developer
The Custom Building & Restoration Trades Directory
<http://www.restorationtradesdirectory.com/>
http://www.restorationtradesdirectory.com
(413) 584-0288

Published by:
Corbett Research Group <https://mail.google.com/>
"Building Websites that Work - - for the Building Artisans."
http://www.restorationtrades.com

**Comment by meetinghouse** [comment]
Andy, I thought that five of yesterday's requested site updates were fine, but I am now encountering a new error when trying to upload images via the Project Subsequent Images Uploader. I find this error on both Project create and edit screens. For instance:
http://custommetalroof.corbettresearchgroup.com/projects/create
and
http://clearywindowrestoration.corbettresearchgroup.com/projects/16/edit

Here is a screenshot of the Subsequent Images Uploader section of the screen, which doesn't look right:
![screenshot 2015-05-27 at 2 07 17 pmd](https://cloud.githubusercontent.com/assets/5215893/7843752/b70385a6-0479-11e5-9fcd-91fee5b80aa5.png)

If I do attempt to upload an image, here is the error I get:
![screenshot 2015-05-27 at 2 07 42 pm](https://cloud.githubusercontent.com/assets/5215893/7843761/d29cb422-0479-11e5-9f16-9f4f2ccb8f32.png)

Please help!

**Comment by acavanagh** [comment]
these should be set now - they were more out of date than I thought when I
initially updated them, required an extra step.
