### ISSUE TITLE
Dark theme, Title Tag edit.

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#134]
Andy,

The Dark Theme Title Tag ("Home Page SEO") seems uneditable, as there is no Admin Pages >> Home. Two options that I can imagine, (1.) to enable Home editing and (2.) to hard provision the field as "Custom Building & Renovation - - Greater Boston & Cambridge, MA."  

#1 is obviously a more permanent solution.

Best,
JC

**Comment by acavanagh** [comment]
This is fixed in the latest code and should be visible in preservationarts.corbettresearchgroup.com.  I fixed it by adding home to the editable pages listed in admin pages.  The only field a regular user should be able to edit is the title tag field.  Please let me know if that's adequate.

**Comment by meetinghouse** [comment]
Andy,

Your example preservationarts.corbettresearchgroup.com is Light Theme and was functioning as planned, no issue. Not sure if your update will create a problem, but it might be forward thinking and efficient to reverse it, just in case. I'm concerned that inputs for the field in two places might create an issue. If not, it is not a problem for it to be there.

That said, I note that the change was made to the Dark Theme as well, at shconstruction2.corbettresearchgroup.com. When I attempt to Edit the field at Admin Pages >> Home Edit >> (enter value) >> (click) Update Page >>, I get a UI "Error", for which I attach a screenshot. 

Best. John C.
![titletag](https://cloud.githubusercontent.com/assets/5215893/8108623/93f31a20-101f-11e5-80e8-82ac47fca843.jpg)

**Comment by acavanagh** [comment]
This should be all set now, some of the fields that aren't visible in the
dark theme were actually required.  Made some adjustments and now it saves
fine.  Should be updated on shconstruction2.corbettresearchgroup.com.

**Comment by meetinghouse** [comment]
Andy, All set, thanks.
Closed out.
John C.
