### ISSUE TITLE
Light Theme, link Portfolio thumbs.

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#137]
Andy,
On the Portfolio page(s), we would like to link the Project thumbnail images to the Project page, as well as the Project Name text.
http://preservationarts.corbettresearchgroup.com/terracottarestoration
In the screenshot, please note that the text "Hollywood American Legion Post 43" is the only link to that project. The thumbnail does not link, though we would like it to.
Best regards,
John C.
![thumblink](https://cloud.githubusercontent.com/assets/5215893/8024406/4998421a-0d00-11e5-9b7d-81c90fd9d39b.jpg)

**Comment by acavanagh** [comment]
This should be fixed now.  Over to you for review and closing if it's up to snuff.

**Comment by meetinghouse** [comment]
Andy,
Looks like it works! Thank you! One more down...
And Thanks,
John C.
