### ISSUE TITLE
Dark Theme: Cannot read caption on Project Edit page

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#139]
Right now, when in the project edit screen, in the Subsequent Images section, the image captions are not readable. They field box appears blank, even if a caption has successfully been entered. If you highlight the field you can read the caption, or click on it you get a dropdown and can see it. But you can't just read what the caption is. The client is bothered by this, and it does seem wrong. Can this be corrected?
![screenshot 2015-06-09 at 12 28 27 pm](https://cloud.githubusercontent.com/assets/5215893/8063511/0cfd8a64-0ea3-11e5-8fe4-b8f6a92b5660.png)

**Comment by acavanagh** [comment]
This should be all set now, it was just that the text was white because it was picking up some css that it shouldn't have been.

**Comment by meetinghouse** [comment]
Andy,
Reviewed, looks good, thanks...will close.
JC
