### ISSUE TITLE
Priority List (Dark Theme, Light Theme)

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#142]
Andy,
Here is a list of a dozen or so current most Priority issues. We'll try to keep all current.
Best,
JC

%%%%%%%%%%%

PRIORITY ISSUES
#148 Light Theme: Banner Width Changing
#131 Light Theme: Mobile Issue 
#130 Dark Theme: Architects field add entries, delete default text. 
#140 Light Theme, Top Image un-display Option
#118 Mobile friendly: Logo resizing 
#122 Light theme, Image Position dropdown install request.
#146 Project Sort Order Dropdown
#147 Portfolio Sort Order Dropdown
#157 Dark Theme: Formatting Requests

**Comment by acavanagh** [comment]
I think a number of the above are either ready for review or closing - can we update the list?

thanks!

**Comment by acavanagh** [comment]
notes:

#151 Current deploy code for staging sites
-- pending review

#155 Light Theme Stylesheet customProject.css Create
-- should be resolved, waiting for client review

#131 Light Theme: Mobile Issue 
-- should be resolved, waiting my review

#130 Dark Theme: Architects field add entries, delete default text. 
--pending

#140 Light Theme, Top Image un-display Option
-- pending

#118 Mobile friendly: Logo resizing 
-- should be resolved, waiting for client review

#114 Banner question. 
-- quoted

#111 Light Theme: Add Portfolios link to top nav bar 
-- closed

#113 houzz badge or button 
-- should be resolved, waiting for client review

#122 Light theme, Image Position dropdown install request.
-- pending

#146 Project Sort Order Dropdown
-- pending

#147 Portfolio Sort Order Dropdown
-- pending

#157 Dark Theme: Formatting Requests
-- pending

**Comment by meetinghouse** [comment]
I've updated the list. Thanks for the reminder.

**Comment by meetinghouse** [comment]
This is not being maintained, and I am prioritizing using labels, so I am closing this issue now. Thanks.
