### ISSUE TITLE
Portfolio Sort Order Dropdown

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#147]
This is similar to the request in Issue #122 and issue #146 . On the Portfolio create and edit screens, you can set the sort order for where the Portfolio appears in the left nav. Currently, there is a dropdown that can be selected from. It looks like this:
![screenshot 2015-06-11 at 11 52 49 am](https://cloud.githubusercontent.com/assets/5215893/8111560/96861a6a-1030-11e5-9e3a-636bf20c598a.png)

Can it be changed so it functions like in Bones, which looks like this:
![screenshot 2015-06-11 at 11 54 46 am](https://cloud.githubusercontent.com/assets/5215893/8111578/b00d1df8-1030-11e5-8fd8-2307c07a77c1.png)

**Comment by acavanagh** [comment]
@serundeputy are you interested in taking this one?

**Comment by acavanagh** [comment]
Do you mean that you just want it narrower, and to have text at the top that tells you the current position?

**Comment by meetinghouse** [comment]
Good question. The width of the sort dropdown is not important. The text stating the current position is something we are asking for.

In addition, there is other functionality behind the original position selection shown in the second screenshot. In the original (Bones) software, you cannot duplicate the same position rank. So, if you already have a portfolio ranked #3, and you select #3 for a new portfolio (or when editing), then all the previously ranked portfolios move down one level. The dropdown of numbers you can choose from only shows the current number of portfolios plus one. Is it possible to have the new software work this way?

**Comment by acavanagh** [comment]
I added some test logic to the portfolios editing pages on example103.  It's only on portfolio edit and not create yet.  If you like the way it works I'll roll it out to portfolio create and to projects edit/create and merge it into the regular code.

**Comment by meetinghouse** [comment]
I feel rather silly because this is marked "High Priority," and you responded and I dropped the ball. I have picked the ball back up now, though. 

I don't see any changes in the sort order section for the Portfolio or Project edit screens on example103. What am I missing?

**Comment by acavanagh** [comment]
I think we probably overrode them with a recent deployment, I'll put the
code back as soon as I get a sec and let you know when it's safe to look
again

**Comment by jboz62** [comment]
This has been added to the Admin Settings.
