### ISSUE TITLE
Light Theme: Banner width changing

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#148]
I noticed something really weird today. The banner on blackburnrestoration.corbettresearchgroup.com was displaying the full width of the screen rather than being lined up with the edge of the logo and the edge of the top menu. I figured I had just made it too big, and downloaded the image to edit it to be less wide. But I discovered it is already 1600 pixels wide (which is the width I have been using for all the other banners). Here is how it looks when it is displaying across the whole screen:
![screenshot 2015-06-11 at 11 58 58 am](https://cloud.githubusercontent.com/assets/5215893/8111691/4291077a-1031-11e5-9ca1-2023526f82d8.png)

I noticed that there is another active banner, so I downloaded it thinking it was probably really wide and that's why the other banner was displaying so wide, but no. It is actually a smaller image.

So I turned the other banner off (made it inactive) and voila! the other banner now shows the size I want it to be. Like this:
![screenshot 2015-06-11 at 12 00 23 pm](https://cloud.githubusercontent.com/assets/5215893/8111740/7a136562-1031-11e5-9a7e-094622a430a7.png)

Why is this happening? Can it be changed so the banners always show the size on the second screenshot, regardless of how many active banners there are?

**Comment by meetinghouse** [comment]
I see that this same thing is also happening with the banner for newenglandsoundproofing.

Both blackburn and newenglandsoundproofing are nearly ready to launch, so I am marking this issue as a priority now. Thanks.

**Comment by acavanagh** [comment]
huh, I don't think I've ever actually looked at the code for the carousel
banners before.  I needed just a little css to make it right, I updated the
two sites above.

**Comment by meetinghouse** [comment]
That looks better. The banner doesn't appear to be centered over the
content and nav bar, though. Is there a way for me to fix that by changing
the banner size, or is it easy to change through the css?

Sincerely,

Katherine Johnson, Content Developer
The Custom Building & Restoration Trades Directory
<http://www.restorationtradesdirectory.com/>
http://www.restorationtradesdirectory.com
(413) 584-0288

Published by:
Corbett Research Group <https://mail.google.com/>
"Building Websites that Work - - for the Building Artisans."
http://www.restorationtrades.com

**Comment by acavanagh** [comment]
I'm not seeing the off-centerness - check the red line guides in this
screenshot:
https://www.dropbox.com/s/6htp1ir13i75pjr/Screenshot%202015-07-07%2022.47.56.png?dl=0

**Comment by meetinghouse** [comment]
I see what you are saying. The left side of the main content section does line up with the banner. The layout has only become obvious to me now that we have a supplemental css file changing the color of the background, like on the newenglandsoundproofing site.

I'm going to request some changes to the way everything left-justifies. If you'd prefer I put this in a new issue, that's okay. For now I'll put it here:

Please left-justify all the following items in one line:
Logo
Banner
Left Nav panel (the one with the four links)

The place where the left edge of the banner is would be a good spot for them all to be. Like this:
![left justify elements line](https://cloud.githubusercontent.com/assets/5215893/8574869/e49f3812-2566-11e5-9f33-147d3126bf08.jpg)


The main body content is currently shaped like a backwards L -- it extends underneath the left nav panel, but that whole section is empty of content. I don't think we need it to be there. Would it be possible to re-shape the main content section to just be a straight line, straight down from where it is at the top of the section? Like this:
![main content shape line](https://cloud.githubusercontent.com/assets/5215893/8574872/eb7a2a66-2566-11e5-895b-36d005d0529c.jpg)

I am also going to putting in a request about not cutting off any images or media embedded in the main body section for mobile screens. I am just throwing that in here so I'm not going at cross-purposes.

**Comment by meetinghouse** [comment]
I am seeing changes to this now and the site is looking a lot better. I'm happy to close this if you are done with it.

**Comment by acavanagh** [comment]
I'm happy if you're happy.  closing.
