### ISSUE TITLE
Current deploy code for staging sites

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#151]
We've already talked about this, but I just want to get it into Git Hub so there's a safe place to put the deploy code when it's ready for me.

Can I get the current deploy code for creating a new staging site in Forge with all the most updated software, and including the creation of the supplemental css file?

**Comment by acavanagh** [comment]
current deploy code should be this:
```
CUSTOM_NAME=whateverthesitenameis

BRANCH=blog

date

cd /home/forge/$CUSTOM_NAME.corbettresearchgroup.com
git checkout -f $BRANCH
git pull origin $BRANCH

composer update

php artisan migrate

bower install

touch public/assets/css/customProject.css
```

and remember that when you spin up a new site you should use the blog
branch.

**Comment by meetinghouse** [comment]
Thanks.

This is the old deploy script I was using. It seems to me that the new script will launch a staging site that has the default Bootstrap content rather than the default Corbett Research Group content. Is that correct? 

How should I change the updated deploy script to do everything it does now plus load it with the CRG content?

Also, I notice that the checkbox Forge used to have for "Run Migrations" when creating the site is now missing. I don't know if that is a problem, though.

Here's the old code, which I would run once, then delete lines 11-18 after.

CUSTOM_NAME=example2
BRANCH=master

date

cd /home/forge/$CUSTOM_NAME.corbettresearchgroup.com
git pull origin $BRANCH
composer install
php artisan migrate
bower install
cd /home/forge/$CUSTOM_NAME.corbettresearchgroup.com/app/database
cp /home/forge/example1.corbettresearchgroup.com/app/database/production.sqlite .
cd /home/forge/$CUSTOM_NAME.corbettresearchgroup.com/public/assets/files
cp -R /home/forge/example1.corbettresearchgroup.com/public/assets/files/* .
cd /home/forge/$CUSTOM_NAME.corbettresearchgroup.com/public/img
cp -R /home/forge/example1.corbettresearchgroup.com/public/img/* .
cd /home/forge/$CUSTOM_NAME.corbettresearchgroup.com/public/assets
cp -Rv /home/forge/example1.corbettresearchgroup.com/public/assets/img .

**Comment by acavanagh** [comment]
right, sorry, I forgot about the database copy step and the other bits that
aren't under version control.  basically, the first time you run that
script you need to include all of those cd and cp statements at the bottom
of it.  after the first deploy, you'll want to remove them.  That will set
up the site with everything it needs.  Make sure that you remove those
lines after the initial setup or you'll wipe out their data next time you
deploy.

**Comment by meetinghouse** [comment]
OK. I will try that. I just ran the deploy code you provided a few minutes ago, though, and the deploy failed. The details are in the deployment log, of course. Probably best to check there than for me to copy paste or screenshot here. Any idea why this would fail for me?

**Comment by acavanagh** [comment]
yes, I see it - what site is that?

**Comment by acavanagh** [comment]
Also, and this is apropos of nothing in this ticket, I created two new labels for issues called 'High Priority' and 'Please Quote'.  Seemed like they might be useful.

**Comment by meetinghouse** [comment]
Got it, Andy. I'll try to make use of them. Have been updating the #142
Priority file, as I go. John C.


Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748

**Comment by meetinghouse** [comment]
This was a brand new site I was trying to deploy:
rebuildpennstation.corbettresearchgroup.com

**Comment by meetinghouse** [comment]
Hey, Andy, I've marked this one as high priority. I suspect that #158 will be affected by this, as I may need to redeploy light theme sites to get help text links to update.

**Comment by acavanagh** [comment]
In terms of the rebuildpennstation.corbettresearchgroup.com - it looks like there's something wrong with the dns for that.  All of the corbettresearchgroup.com subdomains should resolve to the IP address of the server - 162.243.84.17.  For some reason this address resolves to 64.74.223.44.  I have no idea where that is.  Where are the dns settings for these sites managed?  Righty now it doesn't look like it's an issue on the forge side.

**Comment by meetinghouse** [comment]
Andy,

I don't understand. This is a staging site, so it is a subdomain for
corbettresearchgroup.com. There is no DNS provisioned specifically for any
of these staging, subdomain websites that you have deployed for us, so this
request for DNS for rebuildpennstation seems new to me. Let me know.


Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748

**Comment by meetinghouse** [comment]
Andy,

...That said, it may have to do with Dan's setup, so I'll fwd this to him
and see if he understands the issue...


Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748

**Comment by acavanagh** [comment]
currently, I don't understand either.  Your analysis of the situation is
correct - and yet, when I ping  rebuildpennstation.corbettresearchgroup.com I
get a different IP address than when I ping corbettresearchgroup.com
<http://rebuildpennstation.corbettresearchgroup.com/> or any of the other
subdomains.  I'll look into it further tonight.

**Comment by meetinghouse** [comment]
Andy -- I unfortunately do not have any helpful input, but I hope to hear back from you on this shortly, as I've been directed that deploying this staging site is one of my top priorities.

**Comment by acavanagh** [comment]
I'm not actually sure that just adding a random subdomain in front of
corbettresearchgroup.com is going to resolve to the server that
corbettresearchgroup.com is pointing to unless you've set up a wildcard
subdomain.  Who manages your dns settings?

**Comment by meetinghouse** [comment]
Interesting. It has worked fine in the past. I've attached a copy of the
procedure I've used in the past to launch new staging sites (it has old
deploy code in it and references the wrong branch, I realize). Note that
"Allow WildCard Subdomains" is left unchecked in my procedure. That sounds
relevant.



Sincerely,

Katherine Johnson, Content Developer
The Custom Building & Restoration Trades Directory
<http://www.restorationtradesdirectory.com/>
http://www.restorationtradesdirectory.com
(413) 584-0288

Published by:
Corbett Research Group <https://mail.google.com/>
"Building Websites that Work - - for the Building Artisans."
http://www.restorationtrades.com

**Comment by meetinghouse** [comment]
I'm afraid I've broken the site woodwindowworkshop.corbettresearchgroup.com. I attempted to just run the deploy code as it stood, but changed the branch to "blog." So now it doesn't work anymore --- I don't think I've even seen this error screen before. It needed some updates to it software, probably the manual shenanigans that you have to do for each site. Sorry to have borked it.

**Comment by acavanagh** [comment]
I just did the necessary round of manual updates so that it will work with
the new code, you should be able to update that site as usual now.

**Comment by meetinghouse** [comment]
HOT DOG. I re-deployed with the deploy code above and woodenstormwindows is back up.

Two issues, however:

1. It doesn't look like it has the latest code, still, because I am not able to use the "Project Subsequent Images Uploader."
2. I had to remove the last line, for the supplemental css file. This site may already have a supp. css file created for it, and that's fine, but I don't want it to crash if I'm creating a new site.

**Comment by acavanagh** [comment]
do you get an error when using the subsequent image loader, or just no
images?  It's probably not the code, I may have to actually make the
directory on the server for those images to go in.

**Comment by meetinghouse** [comment]
I get an error.
![screenshot 2015-06-29 at 1 52 49 pm](https://cloud.githubusercontent.com/assets/5215893/8414468/31ceb534-1e66-11e5-875b-17cf25e4a459.png)

**Comment by acavanagh** [comment]
thanks - pretty sure that's missing a directory on the server for the
images to go in.  I'll check it out later this afternoon and let you know
as soon as it's fixed.  It's another one of those things that only needs to
happen once when we update something to use the new code.

**Comment by acavanagh** [comment]
I think this is all set now.  I had to do one more thing to finish updating
to the new code.

**Comment by meetinghouse** [comment]
OK, I re-deployed the woodenstormwindows site, but I am still getting the same screen when I attempt to add subsequent images to a project (I did clear cache).

I also notice that the Subsequent Images section looks messy and funky, not like the ones that are working. The two screenshots below show it. The first is from connecticutmason.com, which is launched and working well. The second is from woodenstormwindows. 
![screenshot 2015-06-30 at 12 15 42 pm](https://cloud.githubusercontent.com/assets/5215893/8435883/29cd80ba-1f22-11e5-9c3c-248cb4e3b92d.png)
![screenshot 2015-06-30 at 12 18 04 pm](https://cloud.githubusercontent.com/assets/5215893/8435887/2d712cee-1f22-11e5-92fa-e9d532105688.png)

**Comment by acavanagh** [comment]
try it now without re-deploying.  I may have to make a change to the deploy
code, depending on whether or not it works for you right now without
re-deploying

**Comment by meetinghouse** [comment]
I was able to upload a subsequent image, and the uploader area looked
right. I was also able to delete all the other images that were in there
but hadn't uploaded properly all the way. So from my perspective, this is
good to go. I'll look for your updated deploy code in this issue. Thanks.

Sincerely,

Katherine Johnson, Content Developer
The Custom Building & Restoration Trades Directory
<http://www.restorationtradesdirectory.com/>
http://www.restorationtradesdirectory.com
(413) 584-0288

Published by:
Corbett Research Group <https://mail.google.com/>
"Building Websites that Work - - for the Building Artisans."
http://www.restorationtrades.com

**Comment by acavanagh** [comment]
It looks like this is set now, closing

**Comment by acavanagh** [comment]
Actually, the original issue is with the deploy code, which I'm not confident is totally resolved.  Re-opening.

**Comment by meetinghouse** [comment]
Hey, Andy. Hope you had a good holiday. I just tried using the deploy code again today to deploy a staging site, and it failed again. I was just testing. The custom name is testdeploy. Can you see why this is timing out?

**Comment by acavanagh** [comment]
I just updated the deploy script on
MOULTONCUSTOMDOOR.CORBETTRESEARCHGROUP.COM so that you shouldn't get the
timeout error any more.  If you use that script on any of the recently
updated sites you should be fine.

**Comment by acavanagh** [comment]
Also, in the immediate future until we're sure we have the deploy stuff worked out, please feel free to pull me in to the deployments.  I won't charge you for the time I spend deploying sites until such time as I'm sure that you have a good working code setup in forge.  I think that the fastest way to get to smooth deployments is for me to do a few of them with someone from your team, so I can see and resolve errors as they come up and provide instruction as they go.

**Comment by meetinghouse** [comment]
Here is the latest deploy code you provided to me in late July, taken from the Moulton Custom Door site. It is working for me now! So I'm going through and redeploying code for all sites that haven't already been updated. I'm just putting it in here as a comment so there's a record of it in this issue. Rejoicing!

CUSTOM_NAME=example103
BRANCH=blog

date

cd /home/forge/$CUSTOM_NAME.corbettresearchgroup.com
git checkout -f $BRANCH
git pull origin $BRANCH
rm composer.lock
composer install
php artisan migrate
bower install

**Comment by acavanagh** [comment]
great.  Getting this all ironed out is really important - if you hit any further issues please let me know right away, if at all possible I'll drop everything and jump in with you to get it straightened out.

**Comment by meetinghouse** [comment]
It seems that the deploy code is working, although I do get a timeout
message in Forge when I click Deploy. I don't know why, since it appears to
be actually working. So from my point of view there isn't a problem, but
there might be one.

Sincerely,

Katherine Johnson, Content Developer
The Custom Building & Restoration Trades Directory
<http://www.restorationtradesdirectory.com/>
http://www.restorationtradesdirectory.com
(413) 584-0288

Published by:
Corbett Research Group <https://mail.google.com/>
"Building Websites that Work - - for the Building Artisans."
http://www.restorationtrades.com

**Comment by acavanagh** [comment]
when you say it's working, you mean that it seems to complete succesffully
and then when you look at the site you do see the updates?

**Comment by meetinghouse** [comment]
That's exactly what I mean.

Sincerely,

Katherine Johnson, Content Developer
The Custom Building & Restoration Trades Directory
<http://www.restorationtradesdirectory.com/>
http://www.restorationtradesdirectory.com
(413) 584-0288

Published by:
Corbett Research Group <https://mail.google.com/>
"Building Websites that Work - - for the Building Artisans."
http://www.restorationtrades.com

**Comment by acavanagh** [comment]
cool.  yay!
