### ISSUE TITLE
Light Theme Stylesheet customProject.css Create

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#155]
Andy,
Writing to ask can you guys create a customProject.css stylesheet for connecticutmason.com? The layout is fine like it is, but we would like to apply some simple design values to the work, similar to fitzgeraldtimberframes.com or customwindowstexas.com. If we had one example customProject.css file to work with, we'd be able to edit it sufficient to update other websites. Let me know if this is something you could/should do.
Best regards,
John C.

**Comment by acavanagh** [comment]
I think that there's already one there
in public/assets/css/customProject.css

**Comment by meetinghouse** [comment]
Andy,
Certainly, that is the file, but it is a blank document. We want to add
some simple design values to the websites, similar to what the Clients have
with Bones. Is this something you can help us with? You did the work on the
Dark Theme, I see there is an anomalous file there dark.css. If you
furnished one doc, we'd be able to modify it for all the other websites.
Best regards,
John C.


Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748

**Comment by meetinghouse** [comment]
Andy,
Writing to add that you might just be able to tell me what I need to know, enabling me to take care of this myself. It is very possible that I am UNCLEAR ON THE CONCEPT, when I have the skills to get the job done, but just don't know it. 

I've worked with css files a lot, but in every case I was editing, as necessary. But I would start by duplicating and modifying an existing file. In this instance, I have no place to start as customProject.css is blank. Every stylesheet references specific parts or aspects of the page (fonts, footers, bg's, etc.), and it is difficult for me to reverse engineer those reference points. 

I wish to ask what you think about three questions that might get me started in the right direction:

#ONE: Do you think it might work to rename dark.css (from shconstruction2.corbettresearchgroup.com) to customProject.css, make changes and upload it to to the connecticutmason.com css folder?
#TWO: Or maybe another file in the Light Theme css folder? I have reviewed all the files, and a couple of them look pretty interesting - - main.css and colorfrog.css especially. Might main.css be a good departure point for a document to be renamed to customProject.css and uploaded to the css folder?
#THREE: Do you know, is the UI look on the same file as the website look and feel?

Best regards,
John C.

**Comment by meetinghouse** [comment]
Andy,
...And if I don't hear from you, I'll just try it with those files on a staging website...;-)
Can't hurt, I don't think...
John C.

**Comment by meetinghouse** [comment]
Andy,
I went to fitzgeraldtimberframes.corbettresearchgroup.com and in the css folder found NO customProject.css but did find a dark.css. I'm confused - - isn't dark.css the setup for the Dark Theme and isn't fitzgerald Light Theme? Shouldn't fitzgerald have the same supplemental css file (customProject.css) as connecticutmason.com, since they are both Light Theme?
Wondering,
John C.

**Comment by meetinghouse** [comment]
Andy,
I tried my experiment (rename colorfrog.css to customProject.css) with fitzgerald, made changes to the file and posted it and no changes are visible. Per previous Github post, I am concerned that fitzgerald has a different css folder than does connecticutmason, though they are both Light Theme. I'm going to go ahead and try posting direct to connecticutmason.com...
Try try again,
John C.

**Comment by meetinghouse** [comment]
Andy,
At connecticutmason.com (actually, ctmason.corbettresearchgroup.com, on the server, though it seems to resolve to connecticutmason.com) I have updated customProject.css with colorfrog.css and made numerous changes to the header and footer. My understanding is that customProject.css will load last, and rule. None of my changes were visible, so I conclude that I am on the wrong track and request your review and consult.
Best regards,
John C.

**Comment by acavanagh** [comment]
Hi John - I'll look into this as soon as possible, probably this afternoon.

**Comment by acavanagh** [comment]
Sorry for the delay - I just moved this back down to the bottom of the css stack, so code in customProject.css should now override the other style sheets.  If in doubt, you can end your style declaration with !important - ie:
```
.footer {
color: #ffffff!important;
}
```

**Comment by meetinghouse** [comment]
Thanks, Andy.


Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748

**Comment by meetinghouse** [comment]
Thanks, Andy.
We still aren't able to update these files. I have fwd'd you Shane B's attempt to do an update. I thought it best to leave it intact, outside Github, because his presentation was so clear. Please let me know what we are doing wrong.
Best,
John C.

**Comment by acavanagh** [comment]
As per the email thread, I believe that this issue is resolved.

**Comment by meetinghouse** [comment]
I think this is well on its way. For the moment, John would like to keep this open as we slog through getting just one supp. css file updated (at least partially) and implemented to make sure wrinkles are ironed out. I've removed it from the priority list and removed the priority label also.

**Comment by meetinghouse** [comment]
This is done, thank you so much.
