### ISSUE TITLE
Help links updates automatically push?

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#158]
Hey. I'm trying to update the help links from the Portfolio create and edit pages. I did so on the blog branch, but I don't see any changes. Would this change get pushed automatically to all the sites that have been updated at this point?

**Comment by acavanagh** [comment]
There's some forge related issues with autodeployment that I still need to look in to.  In the mean time, you should be able to log in and press the deploy button on a site by site basis.  I'm getting a little anoyed with forges deployment - it doesn't allow for a lot of flexibility, which I think you guys need.  Looking in to other to handle updating existing sites.

**Comment by meetinghouse** [comment]
OK, this answers my question. Deploy procedure changes are being addressed in other issues too, so I'm going just close this issue now. Thanks!
