### ISSUE TITLE
Weston Millwork site error when viewing projects

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#159]
I have just gone through all the sites, looking to see which seem to be fully updated and which may need software updates still.

I noticed a strange thing at westonmillwork.corbettresearchgroup.com I get an error page whenever I try to view a project. This happens whether I am logged in or looking at the site as a visitor.

I can access the project edit pages through Admin Projects. But I get the same error when trying to view a project whether I navigate from the left nav bar or from the Admin Projects page. Here's a screenshot.

![screenshot 2015-06-30 at 2 11 29 pm](https://cloud.githubusercontent.com/assets/5215893/8438123/ebc7115e-1f31-11e5-977e-25fd000a612b.png)

**Comment by acavanagh** [comment]
should be fixed now, just needed an update

**Comment by meetinghouse** [comment]
I don't get that error anymore. Thanks!
