### ISSUE TITLE
Launch plan, request review.

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#161]
Andy,
I just sent Dan P. an urgent request to launch the existing website steeplejacksworld.corbettresearchgroup.com at rebuildpennstation.com. I understand that you are using this website for testing. Please make no more use of it for that purpose so that Dan can launch.

If you know of any reason that this won't work, please let me, or Dan P. know, right away. I regret the inconvenience of commandeering your test site, but we have been serially promising this important client delivery while we have been working out our deploy code issues and today he ran out of patience.

We do have an early version of the website launched at steeplejacksworld.com. If Dan sees any issues with it whatsoever, he may possibly delete steeplejacksworld.com, entirely.

Again, sorry for the sudden move. Let me know any comments or questions.

Best,

John C.

**Comment by acavanagh** [comment]
No problem.  Also, if you ever need a site deployed quickly, let me know.
Other than the dns part I can set up a new site in ~2minutes.

**Comment by acavanagh** [comment]
I'm closing this, it looks like it's all set now.
