### ISSUE TITLE
Launch priority, push issues.

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#162]
Andy,

We are addressing issues at newenglandsoundproofing, preparatory to launch, and note that it has not had "pushed" the following 2 features:

1. "PORTFOLIO" link in top nav
2. Banner left justify to Logo and Left Nav and fit to screen.

Examples of both features in place can be seen at:

westonmillwork.corbettresearchgroup.com
historicstructuresdc.corbettresearchgroup.com
graneymetaldesign.corbettresearchgroup.com
connecticutmason.com

Examples of only the second (2.) in place can be seen at:

blackburnrestoration.corbettresearchgroup.com
masonryrestorationandconstruction.corbettresearchgroup.com
clearywindowrestoration.corbettresearchgroup.com
coastalclockandchime.corbettresearchgroup.com
coloralchemist.corbettresearchgroup.com
bronzedoorrestoration.corbettresearchgroup.com
fitzgeraldtimberframes.corbettresearchgroup.com
customwindowstexas.corbettresearchgroup.com
moultoncustomdoor.corbettresearchgroup.com
preservationarts.corbettresearchgroup.com
shconstruction2.corbettresearchgroup.com
tradbuild.corbettresearchgroup.com

Can we get these features "pushed", if possible, to newenglandsoundproofing and to the second group, as well?

Very best regards,

John C.

**Comment by acavanagh** [comment]
newenglandsoundproofing.corbettresearchgroup.com is updated.  I'll work on
the rest tonight.

**Comment by acavanagh** [comment]
fyi, the custom css on that page is making the links in the dropdown
portfolio top menu item white on white, so you can't see them.

**Comment by acavanagh** [comment]
also, projects seem to be missing quite a few images

**Comment by meetinghouse** [comment]
THANKS Andy, for noticing!
JC


Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748

**Comment by meetinghouse** [comment]
Andy,
Those Project images were there at one time, though I can't say for sure that they were there just before your recent "push". Is this Project content loss an effect of "pushing" images? Should we prepare ourselves, and our clients, for such a loss?
Best regards,
JC

**Comment by acavanagh** [comment]
the images still exist, there's an issue with the path that I'm fixing
now.  Should be all set shortly.

**Comment by meetinghouse** [comment]
Andy,

Thanks for noticing and taking care of that. My recollection is that this
has happened before, though Katherine, alas, is on vacation and not present
to confirm. Let me know if there are any measures that we can take to
mitigate the issue. I note that it only seemed to happen with "Subsequent"
images.



Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748

**Comment by acavanagh** [comment]
Hi - I'm on the server now, there's a fair number of these images that
actually just don't exist.  Not sure if they had an error uploading them
and didn't notice at the time, or if they uploaded fine and were somehow
lost after the fact.  I don't think there's any provision in the code for
deleting images from the disk.  This is one of those instances where it
would be nice to have site by site backups to look through.

**Comment by meetinghouse** [comment]
Yes, makes sense. I'll mention to Dan.




Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748

**Comment by meetinghouse** [comment]
Andy,

Got it, we've been talking with Dan P. on that, maybe now is the time.


Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748

**Comment by acavanagh** [comment]
I can't stress enough how important it is.  As far as the woodenwindows
goes, I found some of their images in the wrong folder - I'm guessing they
started uploading them some time ago, before one of the semi-recent code
changes - but most of the missing images don't appear to be on the server
anywhere.  All of the other sites I checked looked fine.

**Comment by acavanagh** [comment]
Can this ticket be closed?

**Comment by meetinghouse** [comment]
Yes, this can be closed, I think. The left justification and lining up of elements that is still outstanding is in issue #148, so I think this one can go away now. Thanks.
