### ISSUE TITLE
Light Theme Mobile: Images in body getting chopped off

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#165]
I am liking the new margins I see on a mobile screen. However, I notice that on one site (newenglandsoundproofing) the images, etc. that are embedded in the main body get cut off on the sides.

This may be related to to where the actual main body section edges fall right now (Issue 148). But if not, can we force all the main body content to fit onto a small screen, maybe using breakpoints to avoid making them tiny?

Here are a couple of screenshots of how it is looking right now.
![screenshot 2015-07-08 at 11 49 58 am](https://cloud.githubusercontent.com/assets/5215893/8574968/7d1879be-2567-11e5-865f-f04a50a7bf2e.png)
![screenshot 2015-07-08 at 11 49 35 am](https://cloud.githubusercontent.com/assets/5215893/8574969/841e7c18-2567-11e5-888c-308fb4745d97.png)

**Comment by acavanagh** [comment]
In the example above, it looks like they have set the image size in the editor.  If they set the image size to a set pixel width/height it won't resize.  https://www.dropbox.com/s/6sstnidts5okiwp/Screenshot%202015-08-03%2021.48.15.png?dl=0

**Comment by meetinghouse** [comment]
I see. I think you have to set an image width (meaning, when you upload an image, the size is already pre-filled in for you. You can delete them, but the images still don't resize. So, is there no way to get media in the body?

**Comment by acavanagh** [comment]
I think if you specify the width in the editor it overrides the settings I
have.  I did just push up some code that might help, so check it out again
and see if it's better.

**Comment by meetinghouse** [comment]
Yeah, whatever change you made works. When I delete the width and height settings for an embedded image, it does resize on all screens. This offers some good flexibility. Thanks.
