### ISSUE TITLE
Light theme: Uncollapse portfolios in menus for just one site

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#166]
I know we changed the way the portfolio links show in the left nav (and the top menu mirrors it) some time ago so that all the separate portfolios that may be created get collapsed into one link that is just named "Portfolios." We requested this to reduce the number of clickable buttons on the homepage, to be more mobile friendly.

One client (newenglandsoundproofing) is certain that they would like all their portfolios to show on the left nav as a default, and not make visitors have to click to get to them. Other sites should remain as they are.

I don't know the best way to do this. Can you suggest a way or two, with a ballpark quote for each? This client is nearing launch, so we have some pressure on this question. Thank you.

**Comment by meetinghouse** [comment]
So basically, one client wants the left nav bar to look more or less like it used to, as seen here (all other requests about justification, etc. would still apply)

![screenshot 2015-07-08 at 11](https://cloud.githubusercontent.com/assets/5215893/8575205/cd26c73e-2568-11e5-901a-e9b72f498ce2.jpg)

**Comment by meetinghouse** [comment]
Here are more details on this request from the client. He is actually being pretty specific about how he'd like the left nav to be, and it's not quite as above. He would like to group Portfolios into super Portfolios, basically. Here is a rough outline from the client ofhow they'd like the left nav. The all-caps headings are either pages/links as they stand now, or super-portfolios that are not links in and of themselves. What do you think?


HOME

ACOUSTICS
——— What is acoustics
——— REVRB Acoustics
——— Restaurant Acoustics
——— Products (this will link to a single products page that is continuously used throughout the site)

I WANT TO SOUNDPROOF...
——— Existing Wall Soundproofing
——— New Wall Soundproofing
——— Ceiling and Floor Soundproofing
——— Door Soundproofing
——— Products (this will link to a single products page that is continuously used throughout the site)

WHAT TO SOUNDPROOF
——— Condo/Apartment
——— Commercial Soundproofing
——— Mechanical/HVAC
——— Marine
——— Products (this will link to a single products page that is continuously used throughout the site)

ABOUT US
——— Consulting
——— Our History
——— Glossary / FAQ
——— Drago GC
——— Products (this will link to a single products page that is continuously used throughout the site)
——— Online Store
——— Contact Us

EVENT / MEDIA
——— 2015 Home Show
——— 2015 ABX Show
——— Video
——— Testimonials

CONTACT US

**Comment by acavanagh** [comment]
I think that it's going to be tricky to do that and leave the site in a
condition that will allow it receive and future updates.  Right now if we
add a feature - like the blog on the light theme, for instance - we can
push that out to all the clients.  Therefore the cost of development is
really spread across all the clients.  If one client diverges from the
general codebase in a significant way, they're basically going to be going
to diverge from the main project and head down their own separate fork.
It's sort of your call, with the caveat that with the work that I'm already
trying to get done we're looking at a month or so out before I could start
it.  I do have someone else in the stable now, but they have limited
availability also.  I'm training up two more people but it'll be a month or
so before they're ready.

**Comment by meetinghouse** [comment]
I understand what you're saying. Aside from your availability, here's an idea for this project to avoid the fork. I'd like to avoid forking (as would John) because of the expense and the difficulty recovering it from one client. But if we can do something that could be available across the board, then maybe it's okay.

What we've thought of is to create a higher level of organization, something like Super Portfolio. Portfolios would be assigned to a Super Portfolio, and the only function of this would be to create an item label on the left nav. This would probably require an Admin Super Portfolio page too. This structure could even apply to current sites if we make all portfolios default to belong to the Super Portfolio "Portfolios."  There would be no separate page for each of the Super Portfolios -- they would only exist to group the Portfolios in the nav bar. It could even apply to the top menu too, if that's easiest.

The thing is, we would want this option to default to not being visible. We would only turn it on (from the Admin Settings page as an admin) if asked.

Does this sound easier? Reaonable?

**Comment by KathJohnson** [comment]
This client request was resolved through adding menu management and the ability to add custom pages. Closing.
