### ISSUE TITLE
Light Theme: Images getting cropped on portfolio pages on small screen

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#168]
We've noticed that images on the portfolio page (for example, http://graneymetaldesign.corbettresearchgroup.com/custom_driveway_gates)
are getting cropped. This ends up looking really strange for some clients (the above is a good example of how the image cropping is really destroying the value of the images).

Can the images on the portfolio page instead be re-sized to fit the screen? On the project pages, the top image is always sized for the screen and that looks good, so if the portfolio page can display the top image the same way, that is what is needed.

For instance, if you open the project http://graneymetaldesign.corbettresearchgroup.com/simon_entrance_gate, which is the first project in the above linked portfolio, the top image looks great.

**Comment by acavanagh** [comment]
Looks like you need a little padding in there too.  I'll have this fixed up
for you by tomorrow.

**Comment by acavanagh** [comment]
If I'm understanding the issue correctly, this should be fixed now.  See http://graneymetaldesign.corbettresearchgroup.com/custom_driveway_gates

**Comment by acavanagh** [comment]
If I'm understanding the issue correctly, this should be fixed now. See http://graneymetaldesign.corbettresearchgroup.com/custom_driveway_gates

**Comment by meetinghouse** [comment]
You understood correctly, and it looks great. Can we push it across the board?

**Comment by acavanagh** [comment]
yep, it's in the blog branch and ready for deployment.

**Comment by meetinghouse** [comment]
So I'm clear on this, will the get pushed automatically to all sites once it's in the blog branch, or do I need to redeploy each site individually?

**Comment by acavanagh** [comment]
you'll need to deploy manually.  Automatic deployment A). isn't working for
most of your sites (either a forge or github issue, not sure, they blame
each other), and B).  would blow up your server anyway since you have so
many sites that would try to update at once.

**Comment by meetinghouse** [comment]
OK. I will wait a little before doing this, since I have one troubleshoot in with you already re: deploy code.

Should I enter an issue to get automatic deployment working, or is this already going? I'd mark it at the second tier, by the way.

**Comment by acavanagh** [comment]
Automatic deployment is going to be tricky with all these sites on the same
server.  If they all update at once you're server is going to lock up.

**Comment by meetinghouse** [comment]
Hnnh. I'm going to enter it as an issue, but not as a high priority one, because I don't want to forget about this. I'll close this issue now, though. Thanks.
