### ISSUE TITLE
Dark Theme: Published blog posts not accessible

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#169]
![screenshot 2015-07-28 at 2 02 16 pm](https://cloud.githubusercontent.com/assets/5215893/8939332/cfb8f49e-3531-11e5-8226-77e78ebb76d2.png)
We are having some problems with creating blog posts. Three people have been testing this and we are getting inconsistent results. John is not having an issue, but when I (Katherine) or Erica (who is offsite) tries to create blog posts, the problems are coming up.

Blog posts are being created, but when you try to navigate to them from the Builder's Notebook page, you get Page Not Found.

For example, try opening the post 999. I created this while logged in as admin, in Chrome.

When John creates a post (whether logged in as admin or test user) the post is accessible, so this is not consistent from our perspective.

**Comment by acavanagh** [comment]
what url?

**Comment by meetinghouse** [comment]
Sorry, it's at shconstruction2.corbettresearchgroup.com.

The URL for 999 should be /999

I am also noting that is we have an Admin Blog page as mentioned in #76 would be helpful. I don't know if these posts would show up on such a list or not.

**Comment by acavanagh** [comment]
They would, because the posts are there.  I'm not sure yet, but at the
moment it looks like it's more of an issue with unpublished posts
occasionally showing up in the list.  I found the 999 post at
http://shconstruction2.corbettresearchgroup.com/posts/57/edit, it was
unpublished.  I turned on the published switch and then it worked fine.  It
should never have been visible in the list in the first place.

**Comment by acavanagh** [comment]
Actually, on further research, it looks like the above is actually not the case.  There's duplicate posts in the database for all of the ones that not accessible.  I'm not sure how we're ending up with duplicate records, and you shouldn't even be able to save a post if you give it the same url as another post.  Now that I've got this narrowed down I should be able to clear it up tonight.  Are you seeing this issue on any other sites or just this one?  Did you try to re-create the same post multiple times at some point?  I'm seeing the issue on 'The Radiance of Radiant Heating' and 'A Win For Solar Energy Installations in Massachusetts', among a few others.

**Comment by meetinghouse** [comment]
We may have created duplicate posts, so unfortunately that is not a controlled factor right now. When we test, we will be more cautious with this. I think there was a bit of, "hmm, maybe I didn't save it. Better try again going on," and duplicates may have been created.

We concur that the program should not allow you to save a post with the same URL as another one. Or any page, for that matter, not just blog posts. So if the user tries to do that, the post should not get saved and there should be some message saying why not. A good message would be "That URL has been taken. Please enter a unique URL." 

This is not happening on any other sites because no other sites have the blog enabled (yet).

**Comment by acavanagh** [comment]
Assuming that this is really the problem (I think it is), I'll be able to
take care of it tonight.  There's already a check for duplicate urls on the
other content types, it looks like it's either not implemented or not
working on the blog.

**Comment by acavanagh** [comment]
I pushed up code that will prevent you from having blogs with duplicate url's, which I think is the root of this problem.  It won't fix the ones that are already there, you'll have to edit them to have a different slug or delete them.

**Comment by meetinghouse** [comment]
All fixed up now. Thanks.
