### ISSUE TITLE
Dark Theme: Blog post top images

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#171]
When a blog post is created and nothing is uploaded for the Default Image, it looks like an error message on the Builder's Notebook and individual tag pages, like this:

![screenshot 2015-07-28 at 2 12 06 pm](https://cloud.githubusercontent.com/assets/5215893/8939481/a6b51234-3532-11e5-9526-5116f33e100a.png)

Can it be changed so that nothing at all appears to the right of the blog post on the Builder's Notebook and tag pages if no image has been uploaded? If it's easier, some default image can be displayed instead. Just let me know which is easier from a programming standpoint, and I can provide a default image if needed.

**Comment by acavanagh** [comment]
it's really the same either way, so it's your preference.

**Comment by acavanagh** [comment]
I just removed it if there's no image.  I can add a default one in no time if you'd prefer that.

**Comment by meetinghouse** [comment]
OK, then let's leave the space blank. Leave the space there so all the text is still lined up the same way, but it can be empty. If keeping the text justification is harder, let us know. Thanks.

**Comment by acavanagh** [comment]
Also should be fixed now.  See http://shconstruction2.corbettresearchgroup.com/posts.

**Comment by meetinghouse** [comment]
Yes, this looks good. Thanks, I'm closing.
