### ISSUE TITLE
Dark Theme: Portfolio page has blank spaces

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#172]
On the main portfolio page, there are apparently random blank spaces. We haven't noticed these before and don't know why they are showing up. We're not asking about the place-holder project where there is no image (because we know those need to have images uploaded). The concern is the completely empty spaces.

Here is a screenshot:
![screenshot 2015-07-28 at 2 18 12 pm](https://cloud.githubusercontent.com/assets/5215893/8939626/8097bcfe-3533-11e5-9ad9-b431dd1d277a.png)

**Comment by acavanagh** [comment]
Those will likely go away when there's actual images, but I'll check on it

**Comment by acavanagh** [comment]
This should be all set now as well.

**Comment by acavanagh** [comment]
I think this one has been fixed.  Check http://shconstruction2.corbettresearchgroup.com/portfolio.

**Comment by meetinghouse** [comment]
Yes, this looks good now. Thanks, I'm closing.
