### ISSUE TITLE
Deploying: One site won't deploy all the code

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#173]
I've been going along, happily deploying latest code to all the client websites, when I hit a snag. For the last two sites I tried, Forge gives me the message that "We were unable to deploy your project to your server (corbettresearchgroup-one," and indeed those sites do not appear to have any updates to them.

The two sites that have failed thus far are
highlandrestorationinc.corbettresearchgroup.com
historic-architecture.corbettresearchgroup.com

Before, though the deployment appeared to be working, I did get the message that the deployments had timed out. It looks to me like they went fine, so I was ignoring this for the present. But now there is this different server alert message and the code doesn't appear to be getting pushed out.

**Comment by acavanagh** [comment]
I'm in a meeting from 12-1, will check this out as soon as I'm out.

**Comment by acavanagh** [comment]
These guys were just still way behind on old code.  should be all set now.

**Comment by meetinghouse** [comment]
That makes sense. I'll be deploying everybody over today and tomorrow, so if I run into any others I'll put them in this issue and send them over. So I'm keeping this open in the short-term.

**Comment by meetinghouse** [comment]
Hey, I'm trying to deploy code for agricolacorporation.corbettresearchgroup.com

It deployed all right, which is nice, but I notice that is showing the default site (just like the ctmason.corbettresearchgroup.com site does after it got launched live) and now that I've set that ctmason site to be in maintenance mode, suddenly this site is also in maintenance mode. So the server is pointing to the wrong place for this site. I don't know how to correct this. If it's something I can do, can you share with me how I should go about it? Alternately, if it's best left in your hands, that's fine too.

**Comment by acavanagh** [comment]
That's actually one for Dan.  Either your dns for the  agricolacorporation
<http://agricolacorporation.corbettresearchgroup.com/> subdomain isn't set
right, or there's something wrong in the nginx config for that site.

**Comment by meetinghouse** [comment]
Okay.

Sincerely,

Katherine Johnson, Content Developer
The Custom Building & Restoration Trades Directory
<http://www.restorationtradesdirectory.com/>
http://www.restorationtradesdirectory.com
(413) 584-0288

Published by:
Corbett Research Group <https://mail.google.com/>
"Building Websites that Work - - for the Building Artisans."
http://www.restorationtrades.com

**Comment by acavanagh** [comment]
oh - I think that is your default site.  I think it goes alphabetical and
defaults to the first on the list.  ctmason.etc doesn't go anywhere
anymore, it just hits the default.  You need dan to set up default site on
that server - you could probably do it yourself in the shorterm by making
one that's like aaaaaaa.corbetetc.

**Comment by meetinghouse** [comment]
Cool, I'm forwarding this info to Dan.

**Comment by meetinghouse** [comment]
Andy, I am running again into an issue that some sites won't update. Forge just tells me the deployment failed (not that it timed out, but that it was unable to deploy the project, and indeed, it doesn't appear that the sites updated.)

The sites where I am encountering the problem so far are:
kcrestorationinc.corbettresearchgroup.com
landmarkservices.corbettresearchgroup.com
lelandtorrenceenterprises.corbettresearchgroup.com

**Comment by acavanagh** [comment]
These are probably sites that haven't been updated in a long time and need
to get over that spot that requires me to do it manually.  I'll get these
updated today.

**Comment by meetinghouse** [comment]
That may be the case, but I have also had the same problem with http://bronzedoorrestoration.corbettresearchgroup.com/

and I think you updated that one recently with a fix you were applying for another issue (I'm just going through and redeploying all so they are all on the same code base, that's why I was deploying that one as well.)

So far I can't see any pattern to it, but I'm sure you'll turn one up.

**Comment by acavanagh** [comment]
yeah, bronzedoors was definitely updated recently.  it might be failing for
a different reason though.

**Comment by meetinghouse** [comment]
When you get to this one, there's one more site I can't seem to redeploy successfully, and I'd like to have it for the purpose of testing changes:
example103

It's been deploying all day now. I think it was too far behind as well, maybe. Anyway, that's the whole list of active sites, meaning all sites belonging to actual current clients are updated except for the ones noted in this issue. Yay.

**Comment by meetinghouse** [comment]
We are finding some weirdness with site software. Before going into it too much, I'd like to just point out that deployment always times out for all sites, as I've mentioned before. It has always appeared that code deployed successfully, anyway, so I haven't worried about it much. But it is possibly not deploying completely? I don't know. If you look at the server alerts you will see. I am continuing to deploy anyway, to get everything on the same level, but wanted to let you know. We are working on a list of sites that are now showing anything for the Top Image on the edit pages (though the top image is showing up fine on the visitor version of the project). So if that persists once I've redeployed the problematic sites, I'll send it to you. In the meantime, I did want to let you know about the timing out thing.

Example103 is still trying to deploy, two weeks later. It is stuck in a loop.

**Comment by acavanagh** [comment]
I'm going to put in a ticket to forge about the timeouts.  Your deployments are just often going to take more than two minutes.  As you noted, once started they should generally finish even with the timeout, but the errors are confusing and annoying.

Also, I see that there is one site that you tried to update recently that failed - I'm guessing that it didn't have the new update script.  I can't tell which it was.  It looks like you ran the update at 12:58pm today (8/18).  Any idea which one it was so I can fix it?

Lastly, if a site gets stuck deploying in forge (like example103 did), you can go down to the bottom of the page and click on the little self-help button.  It will let you reset the deployment state.

**Comment by meetinghouse** [comment]
Thanks for working with Forge on this.

The site that failed yesterday was bronzedoorrestoration. In addition,
deployment fails for lelandtorrenceenterprises

Thanks for the tip on resetting the deployment state. I noticed that
example103 has quickdeploy enabled. Al originally recommended enabling
QuickDeploy, but I'm not sure if it's still a good idea.

Sincerely,

Katherine Johnson, Content Developer
The Custom Building & Restoration Trades Directory
<http://www.restorationtradesdirectory.com/>
http://www.restorationtradesdirectory.com
(413) 584-0288

Published by:
Corbett Research Group <https://mail.google.com/>
"Building Websites that Work - - for the Building Artisans."
http://www.restorationtrades.com

**Comment by acavanagh** [comment]
I think that you're going to want quickdeploy if/when you break out
production sites onto their own servers.  I think that if your pricing
scheme can support an additional $5/month per site that your best bet would
be to use the big server you have now for staging, then when a site is
ready to go live spin up a separate server for it, turn on autodeploy, and
copy over the files directories.

**Comment by meetinghouse** [comment]
OK, that's what I was hoping to hear. We are thinking of creating multiple smaller servers specifically in order to allow auto-deploy to work, but it will involve a different backup setup, of course, and a (probably small) change to launching process.

The overall problem in this issue, however, of deployment either timing out or failing, is still there. Today I had two failures on sites I've previously only had timeouts for: coloralchemist and historicstructuresdc. The inability to deploy code is starting to be a real problem, as it hinders our ability to test and rollout the fixes you are making for us, and in some cases is preventing us from populating the sites with data (especially the top image uploader. That one is such weirdness that I will open another issue about it, but it may be related to the deploy problems).

**Comment by acavanagh** [comment]
I just deployed coloralchemist with no issues.  historicstructuresdc was
using the old deploy code, which is more prone to timeouts - I updated the
code and ran an update with no issues.  When you run updates, do you end up
with multiple updates running simultaneously?  For example, do you click
through several sites quickly and hit 'update', so that they end up all
overlapping?  I just ran three overlapping updates that seemed to have no
issues, but then errors started popping up after the updates had completed,
apparently successfully.  I've started removing the
~~~
rm composer.lock
~~~
 line from the deployment script - it's not really necessary and removing
it should speed up the deployments significantly and reduce timeout
errors.  I actually prefer to not have that line in there, regardless of
the timeouts - I'm not sure what the original reasoning for it was.  I
removed it from a half dozen-ish sites and was able to run the deployments
simultaneously with no errors.  That might be enough to solve the timeout
issue, even when running concurrent updates.

I just checked some logs and saw that for lelandtorrenceenterprises, it was
a git error - this one hasn't been updated since we started this new code
branch and needs the manual update before it'll work in forge.  That's done
now..

The other thing that can cause git errors is github being down - they've
had issues for the past day or so.  Every once in a while github has minor
service interruptions - a month or so ago they were attacked by the Chinese
government, that was a mildly annoying couple of days.  You can check their
service status here: https://status.github.com/ or subscribe to their
twitter feed here: https://twitter.com/githubstatus.  If github is down you
can't deploy until it comes back up.  Luckily that's almost always soon, as
they're the biggest software repository in the world.

**Comment by meetinghouse** [comment]
Very helpful info, thanks. I don't know why historicstructuresdc had old code. That must have been my screw-up.

I've removed the composer.lock part from all the client sites' deploy code, and yes, they are running way faster and not throwing any more time-outs. That is great! I deployed code to all sites, mostly successfully, and was able to run three at once (didn't try more -- they complete fast now, so three is all I'd really be able to fire off at once).


Three sites still failed (I admit having deleted some of the server alerts from the list, so you won't see them all. I hope that does not cause a problem). The three that failed are:
armanirestoration
blackburnrestoration
bronzedoorrestoration

All others completed fine, as far as I can tell.

Here is the deploy code I've been using, to clarify the record here in GitHub if nothing else:

CUSTOM_NAME=[name]
BRANCH=blog

date

cd /home/forge/$CUSTOM_NAME.corbettresearchgroup.com
git checkout -f $BRANCH
git pull origin $BRANCH
composer install
php artisan migrate
bower install

**Comment by acavanagh** [comment]
Looks good.  I'll check out the three stragglers this weekend, they're
probably just old code that needs that last push to get up to speed.

**Comment by acavanagh** [comment]
Just went over these - the first two had the name in all caps in the deploy
script, but the folder on the server is lowercase.  It's a case sensitive
server so these didn't match up.  I fixed the deploy script and it works
now.  For the bronzedoor one there's a typo in the name of the folder on
the server - it's ...corbettresearchgroupcom <- not the lack of a dot
before the 'com'.  I fixed in the deploy script and left a comment so
you'll remember.  We could fix it on the server side (probably should) but
you'll have to change the vhost for the site and reboot the webserver - Dan
will know how to make that work if you want to go that route.  The site
deploys fine now, as long as you leave the typo in the deploy script so it
matches the folder on the server.

**Comment by meetinghouse** [comment]
I had no idea about the case sensitivity! Thanks for telling me that! And I feel stupid about the bronzedoors typo -- you already told me about that before. Thanks for adding the note. Once I get Dan added as a collaborator here, I will route this over to him.

**Comment by meetinghouse** [comment]
Hey, Dan. Here is a note from Andy:

"For the bronzedoor one there's a typo in the name of the folder on
the server - it's ...corbettresearchgroupcom <- not the lack of a dot
before the 'com'.  I fixed in the deploy script and left a comment so
you'll remember.  We could fix it on the server side (probably should) but
you'll have to change the vhost for the site and reboot the webserver - Dan
will know how to make that work if you want to go that route.  The site
deploys fine now, as long as you leave the typo in the deploy script so it
matches the folder on the server."

**Comment by meetinghouse** [comment]
Thanks for taking care of this, Dan. Looks good, so I'm closing now.
