### ISSUE TITLE
Question: After launch, can original staging site be deleted?

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#174]
I am just wondering if it's okay to delete the original staging site once a site has been launched. So far we have only launched connecticutmason.com

The staging site for that is ctmason.corbettresearchgroup.com. For whatever reason, that site isn't even reflecting the right content. Unless that's a global problem, I don't really care about that, but the site should probably get killed off so it isn't confusing and it isn't taking up space. 

If I delete it in Forge, what will I break?

**Comment by acavanagh** [comment]
I think if you delete it in forge you'll end up deleting the live site.  My
understanding of your deployment process is that you just point the live
url at the same folder as the staging site when it's ready.  Forge doesn't
know anything has changed, 'cause it doesn't know anything about urls, so
it still lists the site as whatever.corbettetc.com

**Comment by meetinghouse** [comment]
OK, that is good to know, for sure. It looks like the content diverges after launch, if I'm seeing that correctly. So if we need to delete content on the staging site (to make room or something -- I don't really expect that to be necessary,but I can imagine it if I'm feeling creative), would that cause a problem?

**Comment by acavanagh** [comment]
I think what you're seeing is the default site that the server kicks up
when it doesn't know what to do with a request.  Once you switch the dns to
the live url, the old staging url still points to the server but the server
is now listening for the live url.  It doesn't know what to do with the
request so it serves up whatever is set as the default site.

**Comment by meetinghouse** [comment]
OK. I've updated the staging site ctmason.corbettresearchgroup.com to be in maintenance mode so hopefully there will be no more confusion. 

I'm closing this now, thanks for the info.

**Comment by acavanagh** [comment]
might want to think about replacing it with a static advertising/info page
so if someone hits the server by accident they get something useful to you.

**Comment by meetinghouse** [comment]
Yeah, that makes sense. So can I change the content on the staging sites
individually as we launch?

Sincerely,

Katherine Johnson, Content Developer
The Custom Building & Restoration Trades Directory
<http://www.restorationtradesdirectory.com/>
http://www.restorationtradesdirectory.com
(413) 584-0288

Published by:
Corbett Research Group <https://mail.google.com/>
"Building Websites that Work - - for the Building Artisans."
http://www.restorationtrades.com
