### ISSUE TITLE
Automatic deployment not working

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#175]
According to a conversation we had earlier today, automatic deployment is not working and is going to be tricky anyway because there are so many sites on one server and if they all try to update at once the server may lock up.

You mentioned that the issue is either with GitHub or Forge, don't know which. 

I'm entering this issue as a sort of placeholder to come back to later and address if possible.

**Comment by meetinghouse** [comment]
I have a question about this issue. If we were to split the sites up onto multiple smaller servers, do you think the auto-deploy may work again and not seize things up?

**Comment by KathJohnson** [comment]
This issue is no longer current.
