### ISSUE TITLE
Light Theme Top Image Won't Delete, Replace, Update.

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#176]
Logged in http://bronzedoorrestoration.corbettresearchgroup.com/forsyth_dental_center_metal_restoration, Edit >> Project Top Image Uploader >> Choose File >> Update. Image Updates, but doesn't Delete existing image, but rather stacks it on top. We want the Uploader to Delete the existing Image and to display only one, single Image.

I attach screenshot stacked in UI and on page.
![stacked1](https://cloud.githubusercontent.com/assets/5215893/9013629/2c1be1be-378b-11e5-9849-b5a73a8e2abd.jpg)
![stacked2](https://cloud.githubusercontent.com/assets/5215893/9013633/310dd06a-378b-11e5-9fe5-fbc8b123dd36.jpg)

**Comment by acavanagh** [comment]
This is fixed now, and the fix is merged into the main codebase so the
other sites should get it as they get updated.
see
http://bronzedoorrestoration.corbettresearchgroup.com/forsyth_dental_center_metal_restoration
.

**Comment by meetinghouse** [comment]
Andy, I tried to replicate your fix, but could not in entirety. Here are the remaining issues:

TOP IMAGE DISPLAY: The images (uploaded and existing) no longer stack in the web display, but the image displayed as the Top Image is the supposedly deleted, existing image, not the Uploaded image. The Uploaded Image is not displayed at all EXCEPT......

...in the UI, where the Image is still stacked with the deleted, existing image and ....

...on the Portfolio page, where the Uploaded Image appears to display as thumbnail.

Repeating myself, but the Uploaded image is forsythnew.jpg, 850 x 400 pixels, attached:

![forsythnew](https://cloud.githubusercontent.com/assets/5215893/9112478/d2944730-3c1c-11e5-891c-8bbfe7073dc0.jpg)

**Comment by acavanagh** [comment]
can you post url's?  when I go here:
http://shconstruction2.corbettresearchgroup.com/construction_of_new_porte_cochere
or here: http://shconstruction2.corbettresearchgroup.com/projects/36/edit
the top image stuff looks correct.

**Comment by meetinghouse** [comment]
Andy,
You may be confusing the issue with another thread, analagous issue, perhaps resolved. That is for the Dark Theme. The URL this thread is http://bronzedoorrestoration.corbettresearchgroup.com/forsyth_dental_center_metal_restoration, Light Theme.

**Comment by acavanagh** [comment]
I'm not seeing any issues on that page, or it's edit screen - am I missing
something?  What's the url for the related portfolio page?

**Comment by meetinghouse** [comment]
Andy, Looks good, Thanks - - Closed.
