### ISSUE TITLE
Images Won't Load, Project.

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#177]
At http://bronzedoorrestoration.corbettresearchgroup.com/forsyth_dental_center_metal_restoration, click on Project thumbnails, get "This Image Failed to Load" error, see screenshot.
![stacked3](https://cloud.githubusercontent.com/assets/5215893/9014416/3d0f4790-3790-11e5-8a31-39a2524b0c20.jpg)

**Comment by acavanagh** [comment]
This should be fixed now as well.

**Comment by meetinghouse** [comment]
Andy, So it is,
Thanks.
