### ISSUE TITLE
Tile image won't load, Dark Theme.

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#178]
shconstruction2 >> logged in >> (Project: Additions to Mansard Victorian) >> Choose File -  Project Portfolio ‘Tile’ Image Uploader (att, 282 x 400px) >> Update Project >> Error Message "Whoops, looks like something went wrong."

![forsyth1 1](https://cloud.githubusercontent.com/assets/5215893/9066045/643585f8-3aa3-11e5-83fa-fae49853e289.jpg)
![tile](https://cloud.githubusercontent.com/assets/5215893/9066057/7359a94c-3aa3-11e5-976a-1148363f61fc.jpg)

**Comment by acavanagh** [comment]
Please test again, I believe this is fixed now.

**Comment by meetinghouse** [comment]
Andy, It works, Thanks, JC
