### ISSUE TITLE
Project Top Image Uploader fails to load, Dark Theme.

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#179]
shconstruction2 >> logged in >> (Project: Additions to Mansard Victorian) >> Choose File -  Project Top Image Uploader (att, 850 x 400px) >> Update Project >> Error Message "Whoops, looks like something went wrong."

![forsythnew](https://cloud.githubusercontent.com/assets/5215893/9066228/564b313a-3aa4-11e5-83f5-efbf5ebeb125.jpg)

![top](https://cloud.githubusercontent.com/assets/5215893/9066255/895a48e0-3aa4-11e5-976a-acd449c4d941.jpg)

**Comment by acavanagh** [comment]
I can't recreate this problem

**Comment by meetinghouse** [comment]
Andy, It works now, maybe fixed w Tile issue, Thanks, JC

**Comment by meetinghouse** [comment]
Probably it occurred while the site was in process of being updated via Forge. That is the message you get during that time. Closing.
