### ISSUE TITLE
Project Top Image Uploader fails to load, Dark Theme. (Existing)

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#180]
shconstruction2 >> logged in >> (Project: Construction of New Porte Cochere) >> Choose File - Project Top Image Uploader (att, forsythnew.jpg 850 x 400px) >> Update Project >> fails to display, clear cache

Image fails to display, but does display in the UI, stacked with the un-deleted existing image, see att

![forsythnew](https://cloud.githubusercontent.com/assets/5215893/9086152/84218d82-3b50-11e5-8175-6789cb2a7926.jpg)

![top](https://cloud.githubusercontent.com/assets/5215893/9086210/dd9ba622-3b50-11e5-8d8e-3f3a83bc4def.jpg)

.

**Comment by acavanagh** [comment]
should be set, please see 
http://shconstruction2.corbettresearchgroup.com/projects/36
and 
http://shconstruction2.corbettresearchgroup.com/projects/36/edit

**Comment by meetinghouse** [comment]
Thank you. Closing.
