### ISSUE TITLE
Light Theme, Top Image fails to load.

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#181]
http://coastalclockandchime.corbettresearchgroup.com/ >> logged in >> Project Top Image Uploader >> Choose File (immaculate2.jpg, 850 x 179 px) >> Update Project

Image fails to load, but double stacks in UI, with existing, previous, un-deleted image. See attachment. Link is http://coastalclockandchime.corbettresearchgroup.com/projects/14/edit

![topscreen](https://cloud.githubusercontent.com/assets/5215893/9202371/7f03b252-401f-11e5-9bc8-8a12a89f2a2c.jpg)

**Comment by acavanagh** [comment]
Has this site been updated?

**Comment by meetinghouse** [comment]
Andy,

I don't know that it has, I'll run this by Katherine...


Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748

**Comment by acavanagh** [comment]
I'm pretty sure she just needs to go into forge and update it.  if she runs
into any issues with that let me know.

**Comment by meetinghouse** [comment]
Katherine here. I have re-deployed code for coastalclockandchime and it is working fine now.

Disturbingly, though, I have in my notes that I deployed on August 4 also, so I should think it should have "taken" then. One other site behaved the same way until I deployed again this morning (westonmillwork), and yet I deployed for that site on August 5, so once again, it is surprising that there should have been an issue. It appears that sometimes the code is not actually deploying completely. Could that be?

**Comment by acavanagh** [comment]
I think I put in the fix for that after Aug 4

**Comment by acavanagh** [comment]
but you might still hit timeout issues on some sites - if you see any red
errors when deploying please let me know.

**Comment by meetinghouse** [comment]
Andy,
Issue also current for coloralchemist.corbettresearchgroup.com. I attach screenshot and link:
 http://coloralchemist.corbettresearchgroup.com/projects/15/edit
![coloralchemist](https://cloud.githubusercontent.com/assets/5215893/9290026/8cf1b81c-4350-11e5-9da2-eaf8f2caf658.jpg)

**Comment by meetinghouse** [comment]
Andy,
Another website, same issue, screenshot attached:
http://masonryrestorationandconstruction.corbettresearchgroup.com/projects/13/edit
![masonryrestorationandconstruction](https://cloud.githubusercontent.com/assets/5215893/9290049/64fe220e-4351-11e5-9373-5a711b36a4e4.jpg)

**Comment by meetinghouse** [comment]
Andy,
Same issue, screenshot attached, link at:
http://moultoncustomdoor.corbettresearchgroup.com/projects/14/edit

![moultoncustomdoor](https://cloud.githubusercontent.com/assets/5215893/9290063/4879701a-4352-11e5-8eb6-d6809eae13b1.jpg)

**Comment by meetinghouse** [comment]
Andy,
Same issue here, screenshot attached, at link:
http://fitzgeraldtimberframes.corbettresearchgroup.com/projects/15/edit

![fitzgeraldtimberframes](https://cloud.githubusercontent.com/assets/5215893/9290080/07cb32e6-4353-11e5-9a7e-bfa7c31e10d1.jpg)

**Comment by acavanagh** [comment]
Pretty sure this issue is already resolved and you just need to update
those sites.

**Comment by meetinghouse** [comment]
Andy,
Thanks for your reply! Please advise:
By update do you mean test with an image to see if it works? Happy to do so.
Or do you mean to re-deploy the code with the latest code? I'll have to get Katherine to do that. 
Best regards,
John C.

**Comment by acavanagh** [comment]
I mean Re deploy. You just need to go into forge and click update fort any
site with the issue

**Comment by meetinghouse** [comment]
Thanks, Andy,

Will do....


Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748

**Comment by meetinghouse** [comment]
I redeployed all sites, and it looks okay now. On some sites, the top images are viewable as a visitor, but when on the edit page the preview is missing. That's kind of weird, but we aren't reproducing it in a way I can really describe right now, and it can be corrected by re-uploading the top images. That is labor-intensive, so if/when we manage to reproduce it, I'll let you know. I'll close this one out for now.
