### ISSUE TITLE
How to safely update launched sites?

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#184]
As I go through all the sites an update software, I am uncertain about how to handle the already-launched sites. This may be a question for Dan, but I'm asking you first, since code deployment is under your umbrella. 

There are currently two deployed sites: rebuildpennstation.com and connecticutmason.com

I don't see either one on the list in Forge, by those URL's. Should I update the staging sites on which they are based?

**Comment by acavanagh** [comment]
they are the staging sites on which they are based.  In other words, there
is no 'staging' site anymore - what's in forge is just the name of the
folder that all of the code is in.  it was initially given the name of the
staging site - that's just how forge works.  The real url -
rebuildpennstation.com or whatever - now points to that folder.  Anything
you do to that folder in forge you do to the live site.  If you're updating
the site, it's unavailable for a minute or two, so it should probably be
done at a low traffic time for the client.  I can always do those at night
if your clients are EST and if that's helpful - especially when we're still
deploying some large changes, I can roll back quickly if something breaks.

**Comment by meetinghouse** [comment]
Thanks for the answer. At the moment timing of updates doesn't matter, since most sites are not live. But I will keep this in mind for the future.
