### ISSUE TITLE
Question about Bootstrap layout

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#186]
We have someone working on the supplemental css files for many of the sites. He has a question about changing some appearances for the nav bar:
Is there is a control panel or settings page for Bootstrap on a website level (to alter just one website not the whole collection). We want to make the left column wider.

**Comment by acavanagh** [comment]
each site has it's own supplemental css file, you could override the
bootstrap css there if you need to.

**Comment by meetinghouse** [comment]
Thanks, I've passed it along.
