### ISSUE TITLE
Light Theme: Suppress the Company Name when Logo is removed

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#187]
Currently, in the light theme, on the Admin Settings page, we can Remove the logo, which is a great option. However, the default for when you Remove Logo is for "Company Name will show."  

The company name then shows in blue (or orange, or whatever) text at the top of every page. It looks... pretty bad. Like this (hard to see because the text is blue and the background is blue, but you can see it if you squitn!)
![screenshot 2015-08-19 at 12 00 50 pm](https://cloud.githubusercontent.com/assets/5215893/9361570/03e35c5c-466a-11e5-8910-b21c5c6927f9.png)

Can it be changed so that when the logo is removed, there's just nothing in the logo spot? It's okay if all the content shifts upward if that is what needs to happen.

**Comment by acavanagh** [comment]
this one should be all set, see http://bronzedoorrestoration.corbettresearchgroup.com/

**Comment by meetinghouse** [comment]
That looks great. Thanks!
