### ISSUE TITLE
Light Theme: Footer not resizing on some mobile screens

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#188]
We noticed that at least one footer is overflowing the screen on some smaller mobile screens. Can it be changed so that the footer re-sizes for the screen, just as the logo does?

Here is the example of the not-adequately-resizing footer. It's for historicstructuresdc. I don't see any options for setting the size in the Footer section of the Admin Settings page or anything, so I don't know what to do about this other than ask you to look at it.

![screenshot 2015-08-19 at 12 02 13 pm](https://cloud.githubusercontent.com/assets/5215893/9361625/4aa20652-466a-11e5-9b62-e0bca921c42a.png)

**Comment by meetinghouse** [comment]
This is also occurring for moultoncustomdoor. 

I notice that both these have a pipe character in them. I doubt that is the cause, but I just wanted to point it out.

**Comment by acavanagh** [comment]
I'm not seeing this on either of them - what device or browser/os are you using?
https://www.dropbox.com/s/nhf3cfe790jfrj7/Screenshot%202015-08-19%2016.18.51.png?dl=0

**Comment by meetinghouse** [comment]
It gets cut off on an IPhone 5S. I have a Moto G and it renders just fine there. The IPhone is slightly narrower.

**Comment by KathJohnson** [comment]
This was resolved with a later change, so I am closing.
