### ISSUE TITLE
Possible to add new GitHub user?

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#191]
Hey, Andy. Shane Brenizer has been doing the supplemental css work, and since we are liking to keep everything in GitHub with you, and sometimes tasks drift between you and Shane, I wonder it it's possible to add Shane as a user here so documentation on items can be in one place. I know you use GitHub for a lot, so I don't want that to mess anything up for you. Basically, he should be able to access the Issues and be an assignee. If that's advisable, let's do it.

**Comment by acavanagh** [comment]
Hi - It's actually your github account.  I'm not sure that I can add users
- I'll check.

**Comment by meetinghouse** [comment]
Oh, hey, no don't bother. If I should be the one to add collaborators, I
will. I just don't want to mess up your system of time accounting or
whatever. I will add him as a collaborator. Sorry to bug you.

Sincerely,

Katherine Johnson, Content Developer
The Custom Building & Restoration Trades Directory
<http://www.restorationtradesdirectory.com/>
http://www.restorationtradesdirectory.com
(413) 584-0288

Published by:
Corbett Research Group <https://mail.google.com/>
"Building Websites that Work - - for the Building Artisans."
http://www.restorationtrades.com

**Comment by meetinghouse** [comment]
I've added Shane as a collaborator. Closing this issue.
