### ISSUE TITLE
Light Theme: Inconsistency in Top Image uploader

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#192]
We are running into multiple instances of inconsistency in being able to upload or change out already-uploaded images in the Top Image uploader for Projects.

I can't give you a good set of steps because I haven't been able to pin down how to reliably re-create it, but it is happening very frequently and has become pretty disruptive.

For an example, you can look at masonryrestorationandconstruction. You may not see it occurring now, but it's the one for which I've kept closest track and can give you a run-down.
-I deployed code to it yesterday
-Afterward, all top image uploads and changes went fine for about an hour and a half. Then suddenly, we were unable to change the Top Image on a particular project, "The Tuckaway Fireplace and Chimney Restoration Greene County." (http://masonryrestorationandconstruction.corbettresearchgroup.com/tuckaway_fireplace_and_chimney_restoration_greene). This problem was occurring on a Mac.
-I tested the problem on my Chromebook and was able to change the top image with no problem.
-Back on the Mac, the problem with this one project persisted, but we were able to upload and change out top images for other projects. It then started occurring in other projects as well, with no apparent pattern.

There have been several other sites that have not allowed the uploading of top images in the past couple of days also. Here is a list of them. I tried to deploy code to several, and at least three of them failed (noted in issue #173). 

HEARTWOODCARPENTRYRENOVATION
coloralchemist
fitzgeraldtimberframes
custommetalroof
moultoncustomdoor
woodenstormwindows

I'm sorry to not have a better set of steps for you, but the problem is as much the inconsistency as the top image uploading failure.

**Comment by acavanagh** [comment]
are they large files (>2MB)?

**Comment by meetinghouse** [comment]
Andy,
These files are all 1MG or under, mostly much under. They are all taken
directly from our existing Bones websites, where the files are cut down in
size and saved by the program.
Best,
John C.


Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748

**Comment by acavanagh** [comment]
can you send me some of the files that you've been having issues with?  I
haven't been able to replicate the problem.

**Comment by meetinghouse** [comment]
Katherine here. I concur with John that these are not overly large files. But for your research, here is one, the one from the specific project I mentioned above, actually, from http://masonryrestorationandconstruction.corbettresearchgroup.com/tuckaway_fireplace_and_chimney_restoration_greene

![top_tuckaway](https://cloud.githubusercontent.com/assets/5215893/9509561/333189d2-4c2f-11e5-8d83-8749c264a105.jpg)

**Comment by acavanagh** [comment]
I just uploaded that file to that page three times in a row with no issues.
 are there other examples?  Are there any pages where you feel certain you
can recreate the error so I can check the logs while it's happening?

**Comment by meetinghouse** [comment]
Andy,
I agree, this is frustrating because it is inconsistent. This morning I was unable to do top image uploads from a Mac, a Chromebook and a PC. We kept trying and I did manage a single upload on the PC. The issue isn't that it never works, but that it only sometimes works. This is enough to prevent our updates. I attach screenshots, an image, links and image stats:

The link is:  http://coloralchemist.corbettresearchgroup.com/projects/21/edit

The upload image stats are porch new top.jpg, 850x900px, 147KB.

The image is:

![porch new top](https://cloud.githubusercontent.com/assets/5215893/9525031/12eebd94-4cb0-11e5-8129-982588fc3584.jpg)

The error is:

![whoops](https://cloud.githubusercontent.com/assets/5215893/9525059/384ff620-4cb0-11e5-8ee0-4dd039cce62e.jpg)

The UI message (post-Update) is:

![ui](https://cloud.githubusercontent.com/assets/5215893/9525088/60409cf2-4cb0-11e5-9d9b-808db1a9cecf.jpg)

I hope this helps!

John C.

**Comment by acavanagh** [comment]
thanks - I see the error in the logs from this morning, and with the image
attached I can replicate the problem every time so I should be able to
either fix it or find out what it is about the image that causes it to
fail.  Since this image fails every time, even on my local install, and
other images work on the same page, it looks like it's something about the
image itself.

**Comment by meetinghouse** [comment]
Andy,

This isn't the only image that didn't work, it is an example. Since this is
such a critical issue for us, would it be premature for us to document
other images that don't work, so you have a spectrum of failed images to
review? I only documented the single image because I didn't want to muddy
the issue with redundant information.

Best,
John C.


Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748

**Comment by acavanagh** [comment]
I think I found the problem - i didn't mean that it would be only this
image, but rather something about this image and any other image that
shared whatever property this one has that causes failure.  I think I've
identified that property and found a solution, will push up a potential fix
in a minute.

**Comment by acavanagh** [comment]
alright, just pushed code up and updated coloralchemist, I think that will
solve the problem.

**Comment by meetinghouse** [comment]
Andy,
Thanks for taking care of this. It has addressed the problem. I have asked Katherine to push out the code to the other websites.
Best,
John C.

**Comment by acavanagh** [comment]
no problem, sorry it was an issue.  remind Katherine to remove the
```
rm composer.lock
```
line from the deploy code before running the updates.  that should prevent
most of the timeout errors that you've been having on forge.  I removed it
from a bunch of them already, but there's a lot of sites in there.

**Comment by meetinghouse** [comment]
Thanks for the reminder, I will....


Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748
