### ISSUE TITLE
Dark Theme: Unpublished blog posts not visible

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#193]
This is a kind of weird request, but I would like for unpublished blog posts to be viewable (even by visitors) by browsing to the exact URL for them. They should still not be visible on the Builder's Notebook page or any of the tags pages. But it would offer some much-desired flexibility if they could be seen outside of edit mode.

**Comment by meetinghouse** [comment]
I know I asked about issue #206, and I am still interested in resolving that. But I also want to touch base on this issue too. I know this sounds like a weird request. I do have a reason for it, but if it's difficult to accomplish, I could explain why I'm asking for it in about five minutes, and you may have an alternate suggestion that would be more workable.

**Comment by acavanagh** [comment]
@barryaprogrammer - this is a good one, as it's fairly easy but will expose you to some core laravel/eloquent  functionality.  Basically, in the show() method for in the posts controller, there's going to be some code that prevents unpublished items from being displayed.  That restriction needs to be removed, and then you'll have to check the index() method to make sure that the builders notebook page - which is the list of posts - still has a restriction in place that only shows published content.

**Comment by barryaprogrammer** [comment]
following up - thx

**Comment by acavanagh** [comment]
This is actually super easy - all you have to do is remove the or condition in https://github.com/meetinghouse/cms/blob/blog/app/controllers/PostsContrtoller.php#L106

if you look at https://github.com/meetinghouse/cms/blob/blog/app/controllers/PostsContrtoller.php#L33 you'll see that the index method is already restricting unpublished posts.  Read up on Eloquent in the laravel 4.2 docs at http://laravel.com/docs/4.2/eloquent

**Comment by barryaprogrammer** [comment]
Thanks,

following up.

**Comment by meetinghouse** [comment]
Barry, can you complete this? Let me know if any problems.

**Comment by barryaprogrammer** [comment]
Katherine,
I have started on this. There needs to be some clarification on what exactly they need. I am not sure Andy focused on the question and proposed solution. He helpfully zeroed in on where the code lies, but a closer look at the request raises issues. Specifically there isn't any need to necessarily go through builders notebook to get the image-text for the post  if you are going to allow the user to go straight through with a url.  it will be helpful to speak with Andy and get some clarification oh his thoughts.

**Comment by meetinghouse** [comment]
I am the user in this case. You are correct, it is not necessary to go
through the builders' notebook, but I submitted it this way because it
seemed easier than asking for an entire new ability to create
pages/sub-pages and edit the menus. It is a workaround, but it is needed
somewhat urgently, which is why I suggested starting with it. It is all
right if we also pursue the ability to make pages, and I could even
transfer the content to pages in the future for the sake of clarity. But
unless making it possible for me to create pages and manage the menus is as
quick to do as this, please proceed with this. Thanks. I'll be around for
question answering tomorrow, and my phone is 413-225-3153.

Sincerely,
Katherine Johnson, Research Director
Corbett Research Group
http://www.restorationtrades.com
"Web Marketing that Works"

Publishers of:

The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

The Building Arts Notebook, "Journal of the Guild of Building Artisans"
http://buildingartisansguild.com/

Email:  katherine@restorationtrades.com
Phone: 413-586-4748

**Comment by barryaprogrammer** [comment]
I will call tomorrow morning. This email originally was tied to #193
unpublished blog posts becoming accessbile via url to non administrators.
We resolved with Andy's help.
Andy, put them up on Git.

I have started looking at #167 add blog option. Would like to review again.

Will call tomorrow around 10 AM.

thanks
barry

**Comment by jboz62** [comment]
Should this issue be closed, looks like it was resolved?

**Comment by meetinghouse** [comment]
This is now resolved, thank you. I am closing.
