### ISSUE TITLE
Content for staging sites

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#195]
Andy, there are a number of sites on the server that are badly, badly out of date. Rather than asking you to update them, I am going to delete them and deploy them again as if new. 

I need to update some of their content also, but it really isn't worth doing manually. If I had a way to access the database behind each site separately, and do some append queries, that would really be a great thing. Can you tell me where those are located, and if I have access to them? I can probably poke around the tables themselves (for a test site) and figure out the data structure on my own, but at present I don't even know where to look for that. Thanks.

**Comment by acavanagh** [comment]
All of the sites are using an sqlite database that's located at databases/production.sqlite inside the site's folder.  You could just edit one site to be have the content you want, and then copy that production.sqlite file and the old file with the new file in any site that you wanted to have the new content for.  Sqlite is limited (no table alter queries, number of other things) but it's incredibly fast and it's just a file - no database server required.

**Comment by meetinghouse** [comment]
Interesting. I may need to do append queries, I'll look at it more closely. I'm sorry to be very dull about this, but I'm not actually sure how to get to the site's folder. I've been looking around in Forge and directly on the server on Digital Ocean, but I don't really see how to get to the individual site folder within the server. Dan, can you enlighten me on this?

**Comment by drpdev** [comment]
If you login to the Digital Ocean server with the 'forge' account, all of the site directories are right there in forge's home directory.  For example, for New England Soundproofing the database file would be:

/home/forge/newenglandsoundproofing.corbettresearchgroup.com/app/database/production.sqlite


Replace 'newenglandsoundproofing.corbettresearchgroup.com' with whatever site you want to update and that's where you'll find the database.

**Comment by meetinghouse** [comment]
My question has been answered, so I am closing.
