### ISSUE TITLE
Dark Theme: Cannot edit main pages

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#197]
For some reason, we have lost the ability to edit the heading or Main Body of the main pages on shconstruction2.corbettresearchgroup.com

We can go to the edit screen and make changes, but the changes are not saved. This is happening in  both the admin profile and the user profile.

This includes 
http://shconstruction2.corbettresearchgroup.com/about
http://shconstruction2.corbettresearchgroup.com/our_process
http://shconstruction2.corbettresearchgroup.com/testimonials
http://shconstruction2.corbettresearchgroup.com/news_awards
http://shconstruction2.corbettresearchgroup.com/contact

We are able to edit the Title tags on all these pages, however.

**Comment by acavanagh** [comment]
should be all set now, for all pages.

**Comment by meetinghouse** [comment]
Yes, that looks good now. Thanks, and closing.
