### ISSUE TITLE
Dark Theme: Project Top Image not behaving like subsequent images

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#198]
When you view a project page in the dark theme, the top image does not behave the same as the subsequent images, and is not reliably the same width. All the screenshots I will attach below are shots of this page: 
http://shconstruction2.corbettresearchgroup.com/smart_house_technology

When viewed full-size on my Chromebook screen, the top image is slightly less wide than the subsequent images, like this:
![screenshot 2015-09-08 at 12 52 00 pm](https://cloud.githubusercontent.com/assets/5215893/9741426/6c1af140-5628-11e5-9d65-ee3558e6aa35.png)

If I view it on a slightly minimized screen, the top image is quite a bit wider than the subsequent images, which shrink to fit the screen:
![screenshot 2015-09-08 at 12 53 39 pm](https://cloud.githubusercontent.com/assets/5215893/9741495/b2fc050e-5628-11e5-8e52-ec117d9fe09c.png)

As you size the screen smaller and smaller (and this is reflected on a smart phone as well), the top image does NOT resize, while the subsequent images do:
![screenshot 2015-09-08 at 12 55 20 pm](https://cloud.githubusercontent.com/assets/5215893/9741560/1392e162-5629-11e5-8940-f9730dfd67af.png)

The top image should be displaying the same width as the subsequent images all the time.

If you think this is a CSS issue, please let me know and I will send this over to Shane. Thanks.

**Comment by acavanagh** [comment]
These guys should be all set now.

**Comment by meetinghouse** [comment]
This definitely looks better now at full-screen, but if I reduce the size of the screen (or look at it on a phone) the top image is still not behaving the same as the subsequent images.

**Comment by acavanagh** [comment]
oh - just looked at it, it's actually the subsequent images that are
wrong.  The should flex with the size of the screen like the top does, and
they don't beyond a certain size.

**Comment by meetinghouse** [comment]
Yeah, looks like you're right. Can the subsequent images behave like the top image, then?

**Comment by acavanagh** [comment]
The subsequent images here should now flex to the screen properly.

**Comment by meetinghouse** [comment]
Thanks, this looks good. Closing this issue now.
