### ISSUE TITLE
Dark Theme: Tile Image sometimes not displaying on tag page

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#199]
There are a number of projects for which tile images *have* been uploaded, and they display fine on the project pages and on the Portfolio page, but they are not displaying on the tags page. 

For example, the project at http://shconstruction2.corbettresearchgroup.com/Brookline_Residence has an image shows here, on the Portfolio page:
![screenshot 2015-09-08 at 1](https://cloud.githubusercontent.com/assets/5215893/9741839/b504708c-562a-11e5-86ed-f46b9ed0ec90.jpg)

Displays fine here, on the dedicated project page:
![screenshot 2015-09-08 at 1 06 42 pm](https://cloud.githubusercontent.com/assets/5215893/9741808/7bb69472-562a-11e5-96a4-9ba37579cc7b.png)

But does not display here, on the tags page.
![screenshot 2015-09-08 at 1](https://cloud.githubusercontent.com/assets/5215893/9741863/d57836d2-562a-11e5-9f08-42688c39d132.jpg)

As you can see, there are several project for which the tile image isn't showing on the tags page. We can't find any features of the projects or images that tell us why this would be. And trying to replace the image with another one does not fix the problem -- the new image still does not display.

**Comment by acavanagh** [comment]
This is set.  Note that the images aren't all the same height, because they have to be the same width and we don't want to crop or to distort the aspect ratio.

**Comment by meetinghouse** [comment]
Thank you. We understand why they aren't all the same height. I'm closing this now.
