### ISSUE TITLE
Dark Theme: S+H site keeps reverting to light theme

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#200]
This just cropped up in the last few minutes. Twice, the shconstruction2 site has suddenly changed to light theme. We are in process of updating the settings page, but the person doing this edit has only user level access, not admin level. I've changed it back (as admin) to dark theme twice, but wanted to let you know it was happening. Maybe you're in there working and that's all it is?

**Comment by acavanagh** [comment]
no, it might be an issue with it being edited by the user level person -
I'll check on that and the other issues from yesterday tonight.  If I
recall, this happened once before and we chalked it up to user error but
now that you mention the different roles I think it's likely that it's
because the settings are edited by a user level person.

**Comment by meetinghouse** [comment]
That sounds like it might be the source of the problem, doesn't it? Glad we have tracked it to this point.

**Comment by meetinghouse** [comment]
I'm just bumping this issue up a bit, too. In general, the dark theme issues are higher priority right now than others.

Someone at the client logged in noticed that they had inadvertently bumped the shconstruction2 site to the light theme. They were logged in as a user (not an admin), and we fixed it, but it was a significant blip for them because they were in the middle of creating content for the Builder's Notebook, which isn't available in light theme, so they couldn't continue with their work.

We're not sure exactly what steps led to the change to light theme. Probably the user made a change to the Settings.

**Comment by acavanagh** [comment]
I just made some code changes that will prevent this from happening again.  They're in the latest blog branch.

**Comment by meetinghouse** [comment]
Thank you. This looks great and works fine. Closing.
