### ISSUE TITLE
Dark Theme: Uploaded Blog Images Do Not Display

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#205]
Sort of related to Issue #204, I also have trouble with the Project Blowup Images Uploader in the blog. I seem to be able to upload images, but then they do not display. 

See here for an example:
http://testdeploy.corbettresearchgroup.com/TEST2
![screenshot 2015-09-15 at 2 37 09 pm](https://cloud.githubusercontent.com/assets/5215893/9886246/446899ce-5bb7-11e5-96db-7a6e51421aae.png)

**Comment by meetinghouse** [comment]
The client is running into this problem, so this is a high priority. Thanks.

**Comment by acavanagh** [comment]
Both these should be fixed now, there was a permission problem on the server

**Comment by meetinghouse** [comment]
Yup, this looks good, thanks.
