### ISSUE TITLE
Main Body text wraps strangely around embedded images/media

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#206]
Something keeps cropping up on small, mobile screens about the way the information of the Main Body is organized. If there is embedded media/images in the body field, the text sometimes breaks in a funny way that is pretty much impossible to predict for all screen sizes. Is there a way to handle this so that if there are going to be large line spaces in the text due to an image, the text will instead stack above or below the image instead of wrapping? I don't know the easiest way to make this happen, so I'm asking if there is an easy way. It seems that many other mobile-friendly sites do handle this, but I don't know how.

Here is a page from the light theme that looks good on a large screen, but the way the text breaks looks bad on a small screen.

Large screen:
![screenshot 2015-09-16 at 1 02 38 pm](https://cloud.githubusercontent.com/assets/5215893/9912182/2712a4ba-5c74-11e5-991c-e936087819fb.png)

Small screen:
![screenshot 2015-09-16 at 1 10 19 pm](https://cloud.githubusercontent.com/assets/5215893/9912209/53c63ddc-5c74-11e5-87bf-066ff915e4f5.png)

**Comment by meetinghouse** [comment]
Hey, Andy. Katherine here. I know I gave you some direction about the Dark Theme issues being the top priority. In general, that is still the case, because the Dark Theme client is the most important single client. However, we launched five more light theme sites last night (yay!), and realize that this issue becomes more and more important as more clients are launched in the light theme. Can you consider this Light Theme issue (and only this one) as more important that the Dark Theme items for now? I look forward to your opinion on the best way to fix this mobile appearance thing. Or, hey, if you can just fix it quick without going back and forth on it, do feel free. Thanks.

**Comment by acavanagh** [comment]
I don't actually have much control over text breaking inside the editor.
That's all html that's generated by the user.  If they put the image in a
place that causes the text to break badly, the text is going to break
badly.  Those editors are notoriously imprecise.  You can add some padding
to the top of the image or try to move it a little higher or lower or
surround it in it's own paragraph tags to force a text break, but it's
really something the user has to do on a case by case basis.  The downside
of giving users an html editor for their page body content is that then
they're editing the html in their page body content, which is less easy
than it sounds.

**Comment by meetinghouse** [comment]
I hear you. Before we just leave this and try to deal with it by tweaking things ourselves, I have one more possibility to suggest. I notice that when I look at, say, the GBA blog (which is in wordpress, so totally different, I know) on a mobile screen, the embedded images (which are mostly right or left justified) all instead display as centered, and are sized to fit the screen. The screenshots below show a page from that blog, at both full desktop size and shrunk to be like a phone. Would a relative simple rule like "portrait orientation on a smaller screen, show all images as centered instead of any other justification, and size for width of screen" be doable?

The page in the screenshots is 
http://buildingartisansguild.com/2015/09/17/underground-fabrication-continues-production-of-an-indispensable-american-building-stone/

Full desktop size (image is from the screen scrolled down a bit):
![screenshot 2015-09-17 at 1 18 27 pm](https://cloud.githubusercontent.com/assets/5215893/9940584/c3cbefee-5d3e-11e5-8f77-0e2d813456a6.png)

Small screen size, also scrolled down a bit:
![screenshot_2015-09-17-13-33-36](https://cloud.githubusercontent.com/assets/5215893/9941119/3b17c008-5d41-11e5-9f16-ec54cdb2b41c.png)

**Comment by meetinghouse** [comment]
Hey, Andy. I know you sent an answer saying no can do as far as changing the way that text breaks. But since I haven't heard from you, I'd just like to see if the comment I sent back to you is of any help in making a change. If not, then okay, but I would love to hear from you on it. Thanks.

**Comment by acavanagh** [comment]
Hi - thanks for bringing this up again, I actually missed your comment.
Seeing that example that you sent helps, I think that we can set it so that
on narrow (ie, phone) widths the images inside the editor go to ~full width
and centered regardless of what the user specifies for the desktop.  Good
idea!

**Comment by meetinghouse** [comment]
Andy, thanks for your work on the dark theme yesterday. It is awesome to close issues. Have you had a moment to look at this one?

**Comment by acavanagh** [comment]
I did, still in progress.  one issue with this particular example is that
the image is in a table, which makes it much more difficult.  I'll come up
with a general solution for images first - probably a varient on your
suggestion - and then see what can be done about tables.

**Comment by meetinghouse** [comment]
I see. This one is a table so we could put some text underneath and have it look sort of caption-y. Using the built-in caption option puts the text above the image, and that looked weird. It's not the norm to have tables inserted in the main content, but it may happen sometimes. I like your approach of dealing with image settings first, then getting to tables later. Seems like the right priority to me. Thanks for your work on this.

**Comment by jboz62** [comment]
@KathJohnson Hi Katherine, in the editor you can right-click on the table and select "table properties". Once in there, click on the "advanced" tab and you will see a couple text inputs to add an ID or a class:

![screen shot 2016-03-17 at 10 54 42 pm](https://cloud.githubusercontent.com/assets/11739120/13867297/f916f6a0-ec93-11e5-839f-01c88af60977.png)

I added the class "image-right":

![screen shot 2016-03-17 at 11 02 47 pm](https://cloud.githubusercontent.com/assets/11739120/13867345/77ddc324-ec94-11e5-8d44-9b1e3601b462.png)

If you do that, you can target that table and make the fixes you need. I did that already and added a few style changes in the custom css file for mobile to fix that. Looks like this now:

![screen shot 2016-03-17 at 10 51 29 pm](https://cloud.githubusercontent.com/assets/11739120/13867265/b17437f4-ec93-11e5-8a2f-23fe205b8d28.png)

I'm not sure there's anything you can do to prevent that from happening, like Andy was saying, those kind of editors are a problem sometimes.

**Comment by jboz62** [comment]
@KathJohnson This CKEditor plugin might be useful for adding a CSS styles drop-down to the editor toolbar. http://docs.ckeditor.com/#!/guide/dev_styles  We could then have some predefined styles in there for clients to use on images (and whatever else) so that we could then set them up in the stylesheet for desktop, tablet and mobile screens. Something like, "align-right", "align-center" and "align-left" (like WordPress does), etc. If they then use those, all screen sizes would be handled with the predefined styles. Something to think about...

**Comment by KathJohnson** [comment]
Hey, neat. I fussed around with the Advanced table properties way back when this problem cropped up, but I know nothing of stylesheet-classes.''

I took a quick look at that plugin, and it seems like adding something like that to the toolbar would be a good idea, especially if the button could be labeled something like "Align." 

I don't know why your changing the stylesheet-class for the table to align-right made it appear in the center on a small screen, so I don't think this would necessarily always be self-explanatory, but having it in the toolbar is at least more accessible than having it in the advanced properties. 

I don't see a style-sheet class field anywhere for image properties, either, so would the plugin work for images, not just for tables?

**Comment by jboz62** [comment]
Having a predefined style/class like “align-right” allows you to set up the CSS so that when they use that class, the object would align right for desktop screens down to iPad portrait. Below that, 767px on down, you would have what’s called a “media query” in the CSS that changes the style at that view size to align everything centered to view properly on smaller screens. That way they don’t have to worry about messing things up for mobile display, it will already be set up simply by using the right class for the desktop view to look the way they want.

Hope that make sense.

**Comment by KathJohnson** [comment]
Oh, I see. That sounds. Well, it sounds completely ideal, I'd say. Can it apply to both tables and regular old images?

**Comment by jboz62** [comment]
Yeah, that should work for tables and images.

**Comment by jboz62** [comment]
If John is ok with add this, can you please add it as an issue on git?

Thanks!
John
--
John Bozaan
Bozaan Design
413-437-0097
www.bozaandesign.com <http://www.bozaandesign.com/>

**Comment by jboz62** [comment]
This has been added to the new CKEditor, fixed.
