### ISSUE TITLE
Can't deploy new staging site in Forge

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#207]
Hey, Andy, I was just trying to deploy a new site in Forge today, and I get an error after I hit Deploy now (before I go back in and edit the deploy script to remove the css and content stuff). I am probably doing something wrong, but I've tried a couple of times and it still gives me an error. Probably it's easiest to check the error log rather than have me explain it all.

The site I was trying to deploy is 
stephenpeabody.corbettresearchgroup.com

**Comment by acavanagh** [comment]
In the new site deployment script, change the line that says 'composer
update' to 'composer install' - that's what we did in the regular
deployment script to deal with the timeout issue.  That's what I did for
this one, and when I re-ran it it went fine.

**Comment by meetinghouse** [comment]
Much appreciate, thank you.
I've fixed my documentation, and I'm going through all sites and doing a software push today anyway, so I'll make sure they all have the right word in there. Closing this one.
