### ISSUE TITLE
DARK THEME: Content in left nav in different spot on Sub-Portfolio pages

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#208]
This issue is springing from the requests in Issue #203. 

This right-justification edge for the text and logo in the left nav should be the same on all pages. Currently it is the same everywhere except on the Sub-portfolio pages (for example, http://shconstruction2.corbettresearchgroup.com/projects/tags/New%20Construction)

Shane has provided the following feedback on this:

 I looked at the code and there is a DIV missing. Styling is applied to the missing Div which makes it line up properly. With the Div, it's not going to line up. Can Andrew add this Div? See attached jpeg. The code on the left is a page with proper left column alignment. The code on the right is missing the Div with the class "sidebar-nav".
![missing_code](https://cloud.githubusercontent.com/assets/5215893/10519007/cb0e200c-7331-11e5-94e7-51a837ee30cd.jpg)

**Comment by jboz62** [comment]
Fixed.
