### ISSUE TITLE
DARK THEME: Update background pictures on home page

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#209]
John just asked me to upload some different pictures to the S+H homepage (you know, the full-bleed slide show that's just on the homepage). But when I went to do that, I don't see that I'm able to do so.

Could you upload these pictures and tell me how to do so? One was too large to upload here, so I've attached them to an email to you.

They should run in alphabetical order as they are named now (1-3, 5-8), and have a 5 second dwell time. Otherwise formatted like the current pictures.

**Comment by meetinghouse** [comment]
Andy, we figured out where on the server we could upload new pictures, so we did that on our end. But we haven't found how to change the dwell time to 5 seconds. It seems to be about 3 seconds now. Can you tell me where to find that? Or just change it? Thanks.

**Comment by acavanagh** [comment]
Do you folks have sftp access to the individual sites?  I can replace these slides - I'll do it over the weekend - but you should have a way to do it yourselves.  If you have sftp access set up you can just replace the slides in the public/slideshow directory for each site.  Otherwise I could build an admin page, but it would take a couple hours (of billable time, about 3 weeks in real time).

**Comment by acavanagh** [comment]
also, how many sites are currently using the dark theme?  is it just this one?  It looks like the slides got caught up in version control, I want to be able to double check the they don't get deleted on any sites that might still be using them when I pull the slideshow folder out of version control.

**Comment by meetinghouse** [comment]
We do have sftp access. John actually uploaded the images last week successfully. But he was unable to find where the dwell time is controlled. Is there a spot we can find to edit that ourselves? 

No need to put this into an admin page at present. If you direct us, we'll just manage it from sftp.

Only one client site is in dark theme, but we do have another one that we are populating as a sample site too. So two, technically. Thanks for making that catch earlier than later!

**Comment by meetinghouse** [comment]
This has been handled, so I am closing now.
