### ISSUE TITLE
How are project thumbnails sorted on the portfolio and sub-portfolio pages?

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#21]
This is just a question, but I foresee it being relevant. How are the project thumbs sorted on these pages?

![screenshot 2015-01-22 at 12 42 14 pm](https://cloud.githubusercontent.com/assets/5215893/5861130/7a406e56-a234-11e4-8a85-67ed43d94b0d.png)
![screenshot 2015-01-22 at 12 42 57 pm](https://cloud.githubusercontent.com/assets/5215893/5861132/7c600f48-a234-11e4-9995-9a165c547b61.png)

**Comment by acavanagh** [comment]
currently I think it's by date added.

**Comment by meetinghouse** [comment]
OK, thanks. I will close this, but open a related request to make a change.
