### ISSUE TITLE
DARK THEME: Slideshow Request

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#211]
John has uploaded 10 images that are being used on http://shconstruction2.corbettresearchgroup.com/ as a rotating background slideshow for the homepage.

When I spoke with you on the phone, I was only seeing three images in the carousel, but now I am seeing all 10 and they are rotating in my browser (Chrome) as expected. So that's good for the moment. I'm also going to skip dwell time in this issue because it is already listed as an issue elsewhere.

To keep this simple: the problem is, currently, the order in which they are appearing. They need to appear in the order in which they appear in the in the directory (which happens to be alphanumerical). You can find them in the /public/slideshow directory. 

This is the beginning of the order in which they are actually appearing. John does not see a pattern here, but hopefully you will be able to.
Slide1
Slide5
Slide9
Slide4
Slide6 . . . 

We just need to know a way to control the order in which they rotate, whether it's a setting or some naming convention or upload order. 

If you run into any problems with logging in anywhere, let me know, I will try to help you with that.

You might check Issue #209 for other notes on this same general topic.

**Comment by barryaprogrammer** [comment]
OK got it - thx.

**Comment by acavanagh** [comment]
@barryaprogrammer - the js that controls the dwell time is here:
https://github.com/meetinghouse/cms/blob/blog/public/assets/js/app.js#L62

and the slide order can be tweaked here:
https://github.com/meetinghouse/cms/blob/blog/app/controllers/BaseController.php#L159-159

It's using a standard backstretch plugin - see https://github.com/srobbin/jquery-backstretch for documentation.

The way it works is that Laravel reads the content of the slideshow directory into an array and then pushes it into a javascript global object, which is then pulled into the backstretch plugin via the code in app.js linked above.

Keep in mind that the main production branch for this project is 'blog' - it should probably be changed to production or something eventually.

Please don't hesitate to contact me if you have any questions about implementation or how things are set up, this is a big and sometimes confusing app - but once you get a sense of where things are and how they're set up it's pretty easy to work with.

**Comment by barryaprogrammer** [comment]
thx Andrew,

I will look over what you just sent - you anticipated some of my questions.

Barry
413 587 9842

**Comment by barryaprogrammer** [comment]
Hi Andrew,

Thanks  for your offer of help.   
Probably easiest to chat sometime to get to know each other a bit. I hope i'll be able to be of assitance to you. I know i always felt better working on projects where there is someone to back me up.
my phone number is 413 587 9841 my email rothcomputers7@gmail.com 

Here are a few notes on my background and some immediate questions :

I haven't worked with GitHub before. Used TFS, microsofts versioning system so am familiar with the basic concepts.  I did maintance/development work on a drupal related cms insurance site. But when testing changes i would upload the module to a test site. Also, the model here is a little different in that i was working from a fixed site.
 
I am not sure if there is a dark theme test site which i believe this is for. (client drawing on it http://shconstruction2.corbettresearchgroup.com/)
 Also i have filezilla on my system for ftp  but noticed your quesion about site containing the images. I probably need to be able to see the folder where the images are stored. 
But i am wondering if there is a special methodology  used for testing once changes are pushed. 

thanks, later
barrry

**Comment by acavanagh** [comment]
you're going to need to bone up on git and laravel, and set up a local
development environment.  There a nice (though very basic) introduction to
git here https://laracasts.com/series/git-me-some-version-control/episodes/1
and
whole series on getting started with Laravel here:
https://laracasts.com/series/laravel-5-fundamentals.  The first two
episodes will get you started on composer and homestead (which will be what
you use for developing).

**Comment by barryaprogrammer** [comment]
ok - great - thanks

**Comment by barryaprogrammer** [comment]
John, I'd like to stop by your place tomorrow (Tues)  and take a look at github and git with Katherine and yourself.
I think I have played around with it enough  that i could benefit pretty quickly by getting some feedback on questions I have.     Thanks Barry

**Comment by meetinghouse** [comment]
Barry,

Sounds good. How about 1 PM?


Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748

**Comment by barryaprogrammer** [comment]
Great, see you then.

**Comment by meetinghouse** [comment]
Barry,

Good to talk. Sounds like you are on track. I look forward to you getting
up to speed so we can get started on our outstanding punchlist.......

Let me know any issues or questions. Please feel free to call, anytime.


Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748

**Comment by meetinghouse** [comment]
Hi, Barry. How are things going with the whole new world of the GitHub code repository?

**Comment by barryaprogrammer** [comment]
Github and access to files  is fine. Comfortable with that, and using the
git commands.
Issues arose when running site on a windows environment.  Necessary to
create a virtual Linux machine on my computer. Setting that up to match
your frameworks is taking some time. Partly cause I'm used to a windows
environment. but its coming along. I'm motivated.

**Comment by meetinghouse** [comment]
Cool. Is there anything I can help you with? Not to pressure you, but just
to get a feel for where we are, do you have any time estimate on when you
think you'll be ready to work on the details of this issue?

Sincerely,

Katherine Johnson, Research Director
The Custom Building & Restoration Trades Directory
<http://www.restorationtradesdirectory.com/>
http://www.restorationtradesdirectory.com
(413) 586-4748

Published by:
Corbett Research Group <https://mail.google.com/>
"Building Websites that Work - - for the Building Artisans."
http://www.restorationtrades.com

**Comment by meetinghouse** [comment]
Please ignore this: I know you're sending updates to John, so I don't want
you to waste time duplicating all that. I'll just see what you've said over
there. Thanks.

Sincerely,

Katherine Johnson, Research Director
The Custom Building & Restoration Trades Directory
<http://www.restorationtradesdirectory.com/>
http://www.restorationtradesdirectory.com
(413) 586-4748

Published by:
Corbett Research Group <https://mail.google.com/>
"Building Websites that Work - - for the Building Artisans."
http://www.restorationtrades.com

**Comment by barryaprogrammer** [comment]
John,
When its something i know the solution to and its just a matter of doing i
can give an honest time. Right now am trying to resolve some issues which
are needed to have the site up on my virtual machine and running as a
reflection of how it  runs on the www. It's running (yea) but its bombing
(sigh).
Just getting it to run involved quite a few installations and tinkering.
More needed.

But i feel its close.  Hopefully have it up tomorrow sometime. Then can
look at the issue.

Longterm it might make sense to have a virtual machine set up on a host -
that can be used by developers. Just a thought.

**Comment by barryaprogrammer** [comment]
John,
I have made the fixes to code on my machine which I think will work. Next need to establish how to test without impacting production.

**Comment by meetinghouse** [comment]
I believe this issue has been resolved, so I'm closing it now. Thanks.
