### ISSUE TITLE
DARK THEME: Default Image Uploader in Blog not working

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#213]
We're not able to upload any images to blog posts through the Default Image Uploader. We're doing it on a site other than the client one, that is also set to dark theme:
http://steeplejacksworld2.corbettresearchgroup.com/

All the same login credentials should apply and I did redeploy code in Forge in case it was an issue of outdated code. 

It seems that the image uploads all right (though there's no way to verify it). The error occurs when you click "Update Blog Post" after uploading a default image. The error received is the "Whoops, looks like something went wrong." msg. Screenshot below.

![screenshot 2015-11-03 at 1 10 21 pm](https://cloud.githubusercontent.com/assets/5215893/10916965/5048e1fe-822c-11e5-84f7-b698bdfd55d5.png)

Reference issue #205, also, which is the latest issue I'm aware of that dealt with any image uploaders in the blog. May not be related, but I'm just linking it here in case it is.

**Comment by jboz62** [comment]
There's an error on the editor, might be the problem.

**Comment by jboz62** [comment]
This seems to only be an issue on this site, so let's deploy the latest code on here and that should fix whatever the issue is.

**Comment by jboz62** [comment]
Fixed.
