### ISSUE TITLE
MAIN BODY fields not visible in MS browsers in edit or create screens

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#216]
We don't normally use Microsoft IE or Edge here at CRG, but this week we have discovered that the Main Body field does not show up on the edit or create screens for Pages, Projects, or Portfolios. I've confirmed this in MS IE (version 11) and MS Edge. This is not a problem in Firefox, Opera, Safari, or Chrome. It occurs in both the light theme and the dark theme.

Can this be corrected so that people using MS browsers can use the product? For the moment, I've advised the one client who has run up against this to download and use Firefox, but that is something of a learning curve for some folks. 

![image](https://cloud.githubusercontent.com/assets/5215893/12754117/0999c896-c998-11e5-9235-90c4baef9189.png)

**Comment by barryaprogrammer** [comment]
will follow up with Bozaan

**Comment by jboz62** [comment]
This is an issue with CKEditor, Barry and I took a look at it, but haven't found a solution yet. Will ask Andy if he knows of the bug. When we view the textarea with the inspector it has the style of "display:none" and "visibility:hidden", not sure if that's related.

**Comment by jboz62** [comment]
This issue seems to have something to do with the Fitvids script conflicting with CKEditor. https://www.drupal.org/node/2078821#comment-8174193

If you look at that comment and uncheck the class .cke that is "visibility: hidden;", the editor appears. Not sure how to fix yet, just wanted to post that.

**Comment by jboz62** [comment]
The simple fix for this is here: https://www.drupal.org/node/2078821#comment-8263377
Is mentioned here too: https://github.com/davatron5000/FitVids.js/issues/147
`.cke_chrome {
    visibility: inherit;
}`

Changes to:

`.cke.cke_chrome {
    visibility: inherit;
}`

Files that need changing are /ckeditor/skins/moono/editor_ie.css and /ckeditor/skins/moono/editor.css
Looks like they were going to update ckeditor, but still haven't in the latest version.

**Comment by jboz62** [comment]
Committed changes, need to do pull request.

**Comment by jboz62** [comment]
@vivek-chaudhari Hello Vivek, I thought I already added this to the repo, but it doesn't seem to be in there. Can you add this and do a pull request, please? Thanks!

**Comment by vivek-chaudhari** [comment]
@jboz62 Okay John I will look at it and let's what is actual causing this issue.

**Comment by jboz62** [comment]
This only happens in Internet Explorer because of the way it reads the CSS. You just need to make the CSS more specific so it isn’t overridden, that fixes it.

**Comment by vivek-chaudhari** [comment]
@jboz62 Can you please review it? I had added css for ie.

**Comment by jboz62** [comment]
Thanks Vivek, I’ll check that out.

**Comment by jboz62** [comment]
Fixed.
