### ISSUE TITLE
DARK THEME: Collapse "About" submenus when in "News & Awards" page

### ISSUE THREAD

**Issue by KathJohnson** [meetinghouse/cms#218]
Katherine here. I've added myself as a collaborator here in this repository, as I should have done long ago for better clarity. So now it will be obvious when messages are coming from me or from John. 

In a client discussion this morning it was pointed out to me that when on the "News & Awards" page (http://shconstruction2.corbettresearchgroup.com/news_awards) in the dark theme site shconstruction2, the sub-menu for the "Our Company" page (http://shconstruction2.corbettresearchgroup.com/about)shows uncollapsed in the left nav. 

I hadn't noticed that before, but that surely should not be. Hand-in-hand with issue #217, child pages should only be uncollapsed in the left nav if the parent page is opened, or if some other related child page is open. I don't know if I'm using the right bootleg terminology here, so please let me know if what I've said isn't clear. If this needs to be a piecemeal fix for now, that's okay, but in the end the menus should follow this rule in general.

![screenshot 2016-02-04 at 1 42 43 pm](https://cloud.githubusercontent.com/assets/5922040/12826034/2095a79e-cb47-11e5-8f37-003ac12ad680.png)

**Comment by jboz62** [comment]
Great idea, Katherine! I figured it was you doing the commenting, anyway, but this is better.

We actually fixed that before, my guess is the code got overwritten as it wasn't added to Github but added via FTP. I still have it if you want to add it back in. Those three sub-menu items should only be visible under "our company", I believe. Let me compare the code that is in there with what I have. You should also have the files in your email, if you search back a ways.

**Comment by KathJohnson** [comment]
Argh, dangit. That is super annoying that your work got overwritten. You
are certain to be able to find it faster than I can, so if you don't mind
doing so it would be helpful.

**Comment by jboz62** [comment]
No worries, I'm still getting up to speed with the Github thing. Was learning it, but then got very busy with work and had to put it aside. Once I get that, I can add directly so it doesn't get overwritten.

I'll go through the files, won't take but a minute. I've been keeping backups of everything until I get this Git thingy.

**Comment by jboz62** [comment]
Took a sec, just missing a fix on line 41-42 of the _sidebar-dark.blade.php:
```
<!-- Removed from end of parenthesis: || $settings->menu_name == 'sub_nav' -->
@if($settings->theme == true && $settings->pageId == 2)
```

**Comment by barryaprogrammer** [comment]
john, i can work side by side with you to get this in via github - we can do that anytime for all issues - fri thru weekend - thank katherine can just pull them in -

**Comment by jboz62** [comment]
That sounds good, Barry, I added it back to the s+h site.

**Comment by jboz62** [comment]
Hmm, looking at s+h on my phone I see some other code is missing. The mobile menu is missing and not working too, some messed up formatting with the layout as well. 

Barry, we need to get the Github thing going ASAP. Let's go over that tonight or in the morning. 

I'll replace what's missing.

**Comment by KathJohnson** [comment]
John B, I know you already fixed this problem, but that you hadn't yet put it into the GitHub code base. When I deployed code to shconstruction2 this morning in order to get the new page create functionality, it unfortunately overwrote the fixes you made for this older issue. I know you're aware of this, but I am re-opening this issue to document getting it into the blog branch code base. The client would like to launch today, so it is an urgent item. They may not be fully ready to launch and will need to delay, but we'd like to be sure that we're ready on our end, so is it possible to get this into the blog branch code today? I'd hate to overwrite your work again in a future code push.

**Comment by jboz62** [comment]
Yikes! I didn't know we had a launch date set, still need to make some changes to my code to fix a couple things I didn't quite do right. I'll see if I can do that, is it possible to delay to give me a little more set up time?

Maybe we need to have a community calendar where we can post launch dates and any other pertinent info so we're all on the same page.

**Comment by KathJohnson** [comment]
Sorry to spring it on you. I think the launch is getting delayed, anyway, but I don't have a firm date yet. I will let you know when I do.

**Comment by jboz62** [comment]
If it's an emergency, I can also just merge my code with the updated code via SFTP by comparing files, then push the changes later via git. If we have more time, I'll do it via git after I fix my code.

**Comment by jboz62** [comment]
This issue is part of the pull request I just added, that should fix this and then this can be closed.

**Comment by KathJohnson** [comment]
I merged and deployed and this looks like it's cleared up. Closing now, thanks.

**Comment by jboz62** [comment]
Yes, everything looks good. Thanks for taking care of that.
