### ISSUE TITLE
DARK THEME: Change appearance of project titles on Project page

### ISSUE THREAD

**Issue by KathJohnson** [meetinghouse/cms#219]
This request came from Nick Frigo at S+H during a call last week:
In reference to the section of the project page that shows the Project Title and Architect, as outlined in the red box below (for example, http://shconstruction2.corbettresearchgroup.com/smart_house_technology)
![screenshot 2016-02-08 at 1](https://cloud.githubusercontent.com/assets/5922040/12895366/1ada172e-ce6a-11e5-93cb-7efbfd966b27.jpg)

Nick would like this section to be centered vertically and horizontally in that white space it is sitting in right now.

**Comment by barryaprogrammer** [comment]
jb -  i'll assist you with utilizing git on this

**Comment by jboz62** [comment]
That's just a CSS tweak, Barry, that doesn't get overwritten so don't think we need to bother with git on this.

Katherine, I'll make that change.

Best,
John
--
John Bozaan
Bozaan Design
413-437-0097
www.bozaandesign.com

**Comment by barryaprogrammer** [comment]
great!
