### ISSUE TITLE
Project duplicated within one sub-portfolio

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#22]
When I view the sub-portfolio page "tag" I see the same Project twice. It doesn't seem this should be possible.
http://cms.zigbop.io/projects/tags/tag

![screenshot 2015-01-22 at 12 48 49 pm](https://cloud.githubusercontent.com/assets/5215893/5861196/0b1f89a2-a235-11e4-9854-8d64b2535931.png)

**Comment by acavanagh** [comment]
This is actually just an artifact of the seed data.  I have to clear out some of those tables.

**Comment by meetinghouse** [comment]
Does this answer also apply to seeing multiple copies of one blog post within a tag? If so, it'll save us entering/looking at another issue.

**Comment by acavanagh** [comment]
^ yes, and both should be fixed
