### ISSUE TITLE
BOTH THEMES: Menu Management

### ISSUE THREAD

**Issue by KathJohnson** [meetinghouse/cms#221]
As the next step from completing Issue #217, we now need to make it possible to customize the menus.

Can you make it possible for users (both adminstrator and user level) to add, remove, re-order, and re-name links in the left sidebar? 

The "Portfolios" link already behaves in a specific way, and for now, please leave its behavior as-is, so the only possibility for that one is to rename or re-order it. If that throws a big monkey wrench into this request, we can talk it over and maybe drop it. Thank you.

**Comment by jboz62** [comment]
@barryaprogrammer Barry, have you had a chance to look at this yet? It's next on the hit list. Take a look at the BaseController.php file at the $portfolios variable, this if statement:
    if ($portfolios) {
        foreach ($portfolios as $key => $portfolio) {
            $portfolio_links[$portfolio->title] = $portfolio->slug;
        }
    }
Something like that could be done for the sidebar menu and top menu for pages. You can see that code being used in _sidebar-dark.blade.php and _sidebar-light.blade.php. in app/views/shared.

Let's discuss.

John

**Comment by barryaprogrammer** [comment]
ok John - looking into.

**Comment by barryaprogrammer** [comment]
JOhn - i have taken a first look.  Would like to get your impressons, possiblly speak with Katherine..

**Comment by jboz62** [comment]
Do you need me to do anything on this, Barry?

**Comment by barryaprogrammer** [comment]
i'll stop by for blue a little later, we can touoch bases. I'm not clear on what needs to be done. Have a vague idea.

**Comment by KathJohnson** [comment]
I have a client asking for the ability to customize his menu right away. We can charge him for this (at least partially), but I'm commenting here to ask for an approximate time frame. The client would like to be able to both change labels of the existing links, and also add/subtract links and control where they point. 

The full interface doesn't necessarily need to be perfect in order to offer this to the client, in my view. He would be happy for us to simply customize his menus as he requests, although we of course do want to have a smoothly working interface at some point.

**Comment by jboz62** [comment]
@KathJohnson @1sp Katherine, I’m discussing with Sudhir what the best setup would be on the menu system. I mentioned about making the left menu on light theme optional and what that would take. Is that something we want to address now that he's working on this or later? 

We are planning to use a multi-select setup that will have top nav, left nav and sub nav checkboxes. When you select "sub nav", you will then select the parent menu item it would be under. If you have any suggestions or comments on functionality, please advise. I'm still not totally clear on the setup, if we can get a working model posted on a test site, it would help us better understand the way forward. Can you do that, Sudhir? Even if it's just the admin part, it would be helpful, I think.

Sudhir informed me that he's still has more to do on this, not ready to do pull request. I thought I'd post on here so we could discuss. 

Barry if you have any ideas on this, feel free to chime in. 

Thanks,
John

**Comment by jboz62** [comment]
Some screenshots might work, as well, Sudhir, as you make progress. You can post them here so Katherine and John can also follow along and comment.

**Comment by 1sp** [comment]
Thanks @jboz62 

The sneak peak at new menu management interface 

![1](https://cloud.githubusercontent.com/assets/60359/14315948/e09d3a6e-fc1d-11e5-8346-f25d749e1a82.jpg)
![2](https://cloud.githubusercontent.com/assets/60359/14315947/e09cec58-fc1d-11e5-9ff4-7226e492cb32.jpg)
![3](https://cloud.githubusercontent.com/assets/60359/14315949/e0a1f45a-fc1d-11e5-983e-c9015915c19b.jpg)

**Comment by 1sp** [comment]
So I am done with the coding except for the part of integrating portfolio base menu which is causing great confusion (probably due to my incomplete understanding of the complete system).


The current system has the the menu statically defined in two templates  - one each for dark and light themes. So when I am making the menu(s) dynamic i.e menu will now be generated based on the pages created from the dashboard. 

My confusion here is that how can I calculate the order of Portfolio base menu item. Will it be always at 2nd position , or there is some other way to it.

![chrome_2016-04-06_17-49-31](https://cloud.githubusercontent.com/assets/60359/14316403/6661719a-fc20-11e5-8217-3fa6a182e73a.jpg)

**Comment by jboz62** [comment]
Looks like it’s coming along great, Sudhir, thanks for the screenshots. I’m not sure what the others will say on portfolio menu item problem, but my vote is to make the portfolios menu default to the 3rd position allowing at least one page above it. Is that a possibility? It’s typical for clients to want the “about” page menu item to be after the “home” item. Maybe on the “sort” drop down it could say “reserved” in place of #3? 

What do you think, Katherine? We could try that out and see how it works with clients change it later if there’s some other preference.

**Comment by 1sp** [comment]
Very practical suggestion @jboz62 indeed , Thanks!

Another solution coming in my mind for Portfolios position issue is :
1. Let's have a new setting "Portfolio Menu Position" in Settings page. This will store a integer position value
2. Inject "Portfolios" at the position saved in the settings while rendering sorted page menu.

This will give clients a bit more flexibility. Please let me know what you guys think of this.

**Comment by jboz62** [comment]
That sounds like a great idea, Sudhir, but what happens if they select, for example, #3 for Portfolio Menu Position. Will that make position #3 unavailable in the pages settings? In other words, they wouldn’t be able to select #3 in the "portfolio menu position” setting and then accidentally select #3 in the pages setting?

**Comment by 1sp** [comment]
Good question John , I will explain a bit more.

The attribute in page is a sort order value which, while helping in sorting , doesn't necessarily indicate absolute position ( There can be pages with identical sort value, system will sort them accordingly).

The new setting ""Portfolio Menu Position"" will be the absolute position value using which client can absolutely say that "I want portfolio on 3rd position in the menu" -  which in-turn means that system will inject the portfolio menu item at 3rd position after preparing a sorted list of page's menu items. The setting will be smart enough to not let user select out of bound values for position (e.g user may only select a value from 1 to number of pages in the menu )

**Comment by jboz62** [comment]
Thanks, Sudhir, I think that clarifies thing a bit. I’m guessing once we have a working model we can test there might be more modifications to make. I spoke with Katherine and I believe she is going to post some comments.

**Comment by KathJohnson** [comment]
Hello. I am so pleased to see this wonderful progress. Sudhir, I have a couple of comments and questions for you: 
(1) There is a pre-existing page for drag-and-drop sorting of the menu items. It doesn't currently have any impact on the menu, since as you say, it has been hard-coded, so it has been non-functional up to now. But if it is feasible to make it usable again, you can find it at the /menus page. It would be helpful for clients to have this interface to adjust sort orders, as they sometimes have trouble with integer sort order. Perhaps it could even be used to resolve final sorting where the sort order integer for two items has been set equal. 

Only the main menu items are present here, not the sub menu items. It would be most useful if the Portfolio menu item were also here and were movable. The absolute Portfolio Menu position could still exist in the Settings page (defaulted to 2, I think), but would be impacted by adjustment on the Admin Menu page. Is this feasible?


(2) Will the sorting work the same way for the main Nav items and also the Sub Nav items?


(3) May I suggest an alternate set of labels? Instead of labeling the field "Menu Name" could it instead be labeled "Type of menu item"? And then in the drop-down of choices, could they please be "Top & Left Menu" and "Sub-menu"? Hopefully that will be a tiny bit clearer to our clients, who aren't typically power users at all.


(4) I know you already adjusted the label for the toggle to turn this whole thing on to "Enable menu item," but could it be changed further to read "Make this page a menu item"?

**Comment by 1sp** [comment]
Thanks @KathJohnson for your feedback. I will answer your questions one by one:

1) The current sorting component on /menus is made to handle flat list. I suggest that we replace it with a nestedSortable component (Which will allow us to move around menu item hierarchy correctly) . It would look like http://mjsarfatti.com/sandbox/nestedSortable/

2) Yes

3) No problem, I can change the label

4) Yes sure, I can do that

**Comment by 1sp** [comment]
Hi guys, I am back.

Really unfortunate that this bout of hay fever took my work days.

Update is that I just started on drag sort menus page (/menus). I am trying to get this through asap!

In the meanwhile, I have raised a pull request with the changes so far.

**Comment by jboz62** [comment]
Hi Sudhir,

Glad you’re back and feeling better! Thanks you for doing the pull request, that’s exciting news, looking forward to testing that out. 

Thank you for getting this done!

John

**Comment by 1sp** [comment]
Hi John, the sub-nav now works on light theme too. There is a weird issue with menu alignment though (in top menu). Please see it in screenshot below.
![chrome_2016-04-21_00-18-23](https://cloud.githubusercontent.com/assets/60359/14686759/e257d8ce-0757-11e6-80bb-71f7cb99dd6a.jpg)

Please checkout the i221 branch for testing the latest changes.

**Comment by jboz62** [comment]
Hi Sudhir, thanks for the update! The top nav issue is probably just a CSS issue, as this is a new drop down setup, there probably isn’t any CSS to control it. I can check that out when you commit the changes. Please let me know when you have that done and what the branch name is.

Thank you.

**Comment by 1sp** [comment]
Thanks John, you can pull the changes from i221 branch

**Comment by 1sp** [comment]
In the sub-nav on light theme, I have duplicated the parent menu as first item on the sub-nav. The reason behind this is original parent menu item stop being a hyperlink when there is a sub-nav under it so we need to duplicate parent menu item as normal hyperlink in sub-nav.

**Comment by jboz62** [comment]
Ok, thank you, I’ll check it out.

**Comment by jboz62** [comment]
Hi Sudhir,

I pulled down the changes and they look good. Something I haven’t been able to get to work. Is there a limit on the number of menu items that can exist at the same time? I can’t seem to get them all to show up even if I go through and check the order on each one. Maybe the problem is the “all projects” is listed in the menu admin, but it’s not actually a menu item (At least it’s not on lightthemetest) The “projects” get assigned to a portfolio item and are display as a "related project". There may also be some limitation on the number of menu items allowed? Not sure what the issue is, can you make all the menu items show up on your local copy?

Thank you,
John

**Comment by 1sp** [comment]
Hi John, can you please share some screens of the problem you have described? I don't think there is a limit on number of items shown in navigation.

**Comment by jboz62** [comment]
Hi Sudhir,

I’ve marked these up below to indicate the issues:

**Comment by 1sp** [comment]
is there a screenshot ?

**Comment by jboz62** [comment]
I sent 3, you didn’t get them? I’ll check git.

**Comment by jboz62** [comment]
![screen shot 2016-04-21 at 12 40 06 pm](https://cloud.githubusercontent.com/assets/11739120/14717703/9fb7dc26-07c0-11e6-9991-de3d4d619e94.png)
![screen shot 2016-04-21 at 12 31 25 pm](https://cloud.githubusercontent.com/assets/11739120/14717701/9fb603c4-07c0-11e6-88f8-4ef660859989.png)
![screen shot 2016-04-21 at 12 30 42 pm](https://cloud.githubusercontent.com/assets/11739120/14717702/9fb6a5ea-07c0-11e6-88c6-1d6e335d2351.png)

**Comment by jboz62** [comment]
Doesn't seem to include my screenshot when I send them, that's not good. I uploaded them here, but all the markdown indications have been removed. What a pain. I'll have to do it in another program and upload again.

**Comment by jboz62** [comment]
![screen shot 2016-04-21 at 1 00 31 pm](https://cloud.githubusercontent.com/assets/11739120/14717788/115885ec-07c1-11e6-9a10-378628f1d276.png)
![screen shot 2016-04-21 at 1 00 22 pm](https://cloud.githubusercontent.com/assets/11739120/14717789/1158d308-07c1-11e6-81b9-b231453bb025.png)

**Comment by jboz62** [comment]
That's weird, I deleted "testimonials" and recreated it, didn't fix the problem. However, I created a new page and that shows up fine. Something must be wrong with "testimonials" in the database, I would think.

![screen shot 2016-04-21 at 1 07 38 pm](https://cloud.githubusercontent.com/assets/11739120/14718014/31f84f70-07c2-11e6-916f-9a85703d82f1.png)

**Comment by 1sp** [comment]
I think I caught the bug. The old pages menu type need to be updated according to new menu type values. 
You try editing the page - select "enable menu item", sort value and menu type. Save the form and then verify again.

**Comment by jboz62** [comment]
Yes, that was the problem, thank you. I just deselected the "enable menu item", updated and then reselected it and updated it again.

**Comment by jboz62** [comment]
Still having some trouble with that, if I try to move things around, "testimonials" disappears again. I tried the last procedure and it's not working this time. Are you having any issues like that?

**Comment by jboz62** [comment]
The order looks correct on the drag and drop, but the "testimonials" is missing again:

![screen shot 2016-04-21 at 1 22 55 pm](https://cloud.githubusercontent.com/assets/11739120/14718357/32cfad7e-07c4-11e6-9f1f-45c299081686.png)

**Comment by jboz62** [comment]
If you want to do a join.me and try controlling from your end, we can do that so you can see what's going on.

**Comment by 1sp** [comment]
If you are sorting via /menus then it won't work as it won't understand the new menu type values and would happily override them with old menu types.

**Comment by 1sp** [comment]
lets have a join.me session , please share the url

**Comment by jboz62** [comment]
https://join.me/655-362-474

**Comment by KathJohnson** [comment]
Hello. I spoke with John B. yesterday and today I have been testing the changes made thus far on a new site I created for this purpose, menus.corbettresearchgroup.com

I know I'm the one who requested making the Admin Menus functional, but since it pushes us too far out of budget, I guess we'll have to abandon it, at least for now. I see that it does have some functionality, but I think we'd better focus on working out issues on the Page Creation/Edit screens.

I have some screenshots for that, and I will create separate issues for them here in GitHub. But I know there has been some work in the interim, so please do let me know where to find changes so I can deploy them to my test site and then we can hopefully all working from the same thing.

**Comment by jboz62** [comment]
You should have all the current changes, Katherine. Sudhir hasn’t made any new changes, he’s waiting for sFTP credentials and the login for the admin for the menus site. I’ll send those separately. Sudhir, I’ll send you the details on Upwork.

**Comment by KathJohnson** [comment]
There are some outstanding items related to this issue, but I think they need to be addressed separately and reference this issue as needed. So I am closing this one in order to create a bit of order in the Git Hub issues list.
