### ISSUE TITLE
BOTH THEMES: Error when creating page

### ISSUE THREAD

**Issue by KathJohnson** [meetinghouse/cms#222]
I've tried to create a page in shconstruction2 using the new page creation feature. When I clicked "Update Page" I got a big nasty error page (see screenshots. I took two screenshots, one at the top of the error page, and one after scrolling down a bit). This is springing from my testing of issue #217.

![screenshot 2016-02-23 at 11 56 09 am](https://cloud.githubusercontent.com/assets/5922040/13259391/1c28f9a8-da25-11e5-9813-f30f4d6fe445.png)
![screenshot 2016-02-23 at 11 59 53 am](https://cloud.githubusercontent.com/assets/5922040/13259394/206ae3be-da25-11e5-95c9-0ca2eced74ac.png)

**Comment by KathJohnson** [comment]
After speaking with you, John, we figured out that the error only occurs when I try to save the page when the page is not marked as published. So this should still be corrected, but it is not as urgent as I at first thought.

**Comment by jboz62** [comment]
This issue can be closed, right Katherine? Wasn't this error related to the url/slug field not visible for users, issue #225? #225 can probably also be closed, unless you need it open.

**Comment by KathJohnson** [comment]
The user is now able to create a page, but the error when trying to create an UNpublished page still occurs. This happens whether logged in as a user or as an admin and doesn't appear to be related to the URL field being available. 

I did close #225, though, that was was all wrapped up. But this one is still outstanding. Thanks.

**Comment by jboz62** [comment]
Ok, thanks. We can take a look at that.

**Comment by 1sp** [comment]
I faced this issue while working on #221 . It is small fix

**Comment by jboz62** [comment]
Sudhir, If this is something you can fix quickly, please do.

**Comment by 1sp** [comment]
This was fixed in an earlier commit to i221 branch

**Comment by jboz62** [comment]
Ok, thanks. That branch wasn't merged, so when you do a final pull request with all the changes, we can merge that. Have you committed all of your changes yet?

**Comment by 1sp** [comment]
Yes , I have posted an update to #221 already

**Comment by jboz62** [comment]
Ah, ok, thank you for that. I’ll pull it down and try it out. I’m not sure if Katherine is in the office today, but I’ll show them when they are available.

Thank you

**Comment by 1sp** [comment]
@KathJohnson  I believe this can be closed now.

**Comment by KathJohnson** [comment]
I would dearly love to close it, because I see the error is resolved on the site that is running on the i221 branch code. But I don't think it's been pulled into the blog branch yet.

**Comment by jboz62** [comment]
This has been fixed.
