### ISSUE TITLE
BOTH THEMES: No URL field visible to user-level access

### ISSUE THREAD

**Issue by KathJohnson** [meetinghouse/cms#225]
It has come to my attention that the URL field isn't available on the Create Page page to a person logged in wth user level access (as opposed to administrator level access). First screenshot below shows this.

This means that when the user clicks "Update Page," they get a big nasty error.
Second screenshot below shows the error.

This will need to be fixed so users can successfully create pages. Thanks.

![screenshot 2016-02-24 at 12 22 46 pm](https://cloud.githubusercontent.com/assets/5922040/13294323/651dd1c0-daf1-11e5-904f-44d0a65c3efe.png)

![screenshot 2016-02-24 at 12 22 50 pm](https://cloud.githubusercontent.com/assets/5922040/13294328/6a6e805c-daf1-11e5-8367-9bfa11fa0128.png)

**Comment by jboz62** [comment]
Hmm, should be, it was working on testdeploy.corbettresearch.com, but that code seems to be missing on there as well now. No create page ability on there now. My guess is that Barry may have missed some code when comparing files? Everything from admin_pages_feature branch matches up with what’s was deployed?

**Comment by jboz62** [comment]
Katherine, not exactly sure what, if anything, changed, but this seems to be working now. I'm seeing the URL field on both light and dark themes in the admin. Please close if you agree. Thanks

**Comment by KathJohnson** [comment]
I'm having difficulty deploying the current code from Git Hub to the testdeploy site right now. So I'd recommend checking lightthemetest for the most up-to-date test site at the moment. I toggle it back and forth between light and dark theme pretty freely as I check things over, just so you're prepared for that.

Anyway, the problem is related to access level, I think. I can see the URL field when logged in as admin also. But if I log in as a regular level user (for all un-launched sites, there is a dummy user profile set up where UN = testit@test.com and PW = rainmake), then the URL field does not appear in either theme and therefore when the users tries to create a page and save it, an error occurs. Probably because they weren't able to populate a required field.

**Comment by jboz62** [comment]
Got it, didn't know about the user access. That error is definitely because it's expecting a slug (the url field) and there isn't one. I'll see if I can figure that out, might need to talk to Andy about access levels.

**Comment by jboz62** [comment]
Andy pointed me to the code that needed changing, it was "authentication" that we needed, I was looking for permissions. So that's fixed on the next set of changes for light theme. Will need to be pushed out for light and dark theme sites that have page creation functionality.

**Comment by meetinghouse** [comment]
Great, thank you. I see there's a fun, new error when I try to deploy to
lightthemetest, so I haven't been able to see it live (if it is actually
live, I'm not sure that it is ready yet, but I thought I'd check in that
way to see.) I would have thought it would have been in the permissions
too. I don't know what authentication is, but that's okay. Good to know you
located it.

I personally like your idea of finding someone who is knowledgeable with
Laravel Forge, because it has been a bottleneck point in the past, and it
looks like it is becoming one again.

Sincerely,
Katherine Johnson, Research Director
Corbett Research Group
http://www.restorationtrades.com
"Web Marketing that Works"

Publishers of:

The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

The Building Arts Notebook, "Journal of the Guild of Building Artisans"
http://buildingartisansguild.com/

Email:  katherine@restorationtrades.com
Phone: 413-586-4748

**Comment by jboz62** [comment]
What changes were you trying to deploy, the change to remove the authentication? Is the error related to that?

**Comment by meetinghouse** [comment]
When I deploy code, I don't choose which changes to deploy. It's all or
nothing. If there haven't been any changes to the code base, then no
changes occur, which hasn't been any problem in the past.

In this case, I was deploying code specifically to test for the
authentication update, yes, but I don't know if the error is related.

I've put the error in GitHub Issue #224 for Andy to look at. You are
welcome to look too, if you think you can make more sense of it than I.

Sincerely,
Katherine Johnson, Research Director
Corbett Research Group
http://www.restorationtrades.com
"Web Marketing that Works"

Publishers of:

The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

The Building Arts Notebook, "Journal of the Guild of Building Artisans"
http://buildingartisansguild.com/

Email:  katherine@restorationtrades.com
Phone: 413-586-4748

**Comment by KathJohnson** [comment]
This is interesting. It looks like the authentication change to allow someone logged in with user-level access IS available on the klitsas.corbettresearchgroup.com site. 

I tried to deploy to the newenglandsoundproofing site, but the change doesn't show up there. Is this change something you put into the individual site files rather than into the Git code base? Or is it not merged into the Git code base yet? Curious.

**Comment by jboz62** [comment]
Yes, I added the changes to the Klitsas site and committed the changes to a branch, but I need to do a pull request when I'm done. That's probably why they're not showing up.

I'll commit the rest of the changes and do a pull request.

**Comment by jboz62** [comment]
When you do a deploy, do you do site specific deploys or does it go to all the sites? Some of that code, like the main.blade.php change shouldn't go to all the sites yet. We need to discuss how to deploy everything tomorrow. That change for the user access can be deployed, though. Call me if you want to discuss. 413-426-7618

**Comment by meetinghouse** [comment]
Let's discuss tomorrow. But to answer your question when I deploy:

   1. I do it site-by-site. So I can deploy to just one site and not others.
   2. The code gets deployed whole-hog from the branch specified in the
   "Deploy Code" saved to Forge for that site, to the one site that was
   selected. I will hold off deploying to any sites for now.
   3. There is an auto-deploy option in Forge. I have it turned off at
   present. The distant goal is to enable it, but that will probably involve
   splitting the sites up across several smaller servers so as not to
   overwhelm the one server by trying to deploy to a bunch of sites at once.
   4. I will check to make sure I actually do have auto-deploy turned off
   for all the sites. I don't know a way to do that other than one-by-one, so
   that's what I'll need to do. Hopefully done by the time of our meeting
   tomorrow.


Sincerely,
Katherine Johnson, Research Director
Corbett Research Group
http://www.restorationtrades.com
"Web Marketing that Works"

Publishers of:

The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

The Building Arts Notebook, "Journal of the Guild of Building Artisans"
http://buildingartisansguild.com/

Email:  katherine@restorationtrades.com
Phone: 413-586-4748

**Comment by jboz62** [comment]
Ok, thanks for the info on that, appreciate it. If you need that user auth fix on a specific site, we can do it via FTP for now, until you can deploy all the changes. I should have done that separately, sorry for the holdup.

Best,
John
--
John Bozaan
Bozaan Design
413-437-0097
www.bozaandesign.com <http://www.bozaandesign.com/>

**Comment by meetinghouse** [comment]
If it's pretty easy to do, I would appreciate the change being immediately
available on the site

newenglandsoundproofing

Just let me know if you get to it, I'll take a look, and then tell the
client. Thanks.

Sincerely,
Katherine Johnson, Research Director
Corbett Research Group
http://www.restorationtrades.com
"Web Marketing that Works"

Publishers of:

The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

The Building Arts Notebook, "Journal of the Guild of Building Artisans"
http://buildingartisansguild.com/

Email:  katherine@restorationtrades.com
Phone: 413-586-4748

**Comment by jboz62** [comment]
Yes, quick change. It’s live and working on their site now.

Best,
John
--
John Bozaan
Bozaan Design
413-437-0097
www.bozaandesign.com <http://www.bozaandesign.com/>

**Comment by KathJohnson** [comment]
This has been resolved, thanks. Closing.
