### ISSUE TITLE
Light Theme: Admin tablet view, both toggle buttons open admin nav.

### ISSUE THREAD

**Issue by jboz62** [meetinghouse/cms#227]
When viewing the light theme admin on a tablet computer and the admin nav shows as a toggle button, when clicked, both the top menu and the admin menu open. There's a toggle button for the top menu and one for the admin menu, they should open and close independently, but they both open and close together. The reason is probably because they have the same classes instead of different classes. Whatever script is controlling it is probably using that class so both menus open and close together.

I have looked for the script that controls that, but no luck finding yet.

![screen shot 2016-03-03 at 8 32 05 pm](https://cloud.githubusercontent.com/assets/11739120/13515467/8686a014-e17f-11e5-87e7-3baf65416ad2.png)

**Comment by jboz62** [comment]
Fixed this by adding an ID to the top light theme menu to differentiate it from the admin menu.

**Comment by meetinghouse** [comment]
Thank you for noticing this and fixing it. I clearly haven't been trying to
do admin stuff on a mobile device, but only looking at the visitor view.

Sincerely,
Katherine Johnson, Research Director
Corbett Research Group
http://www.restorationtrades.com
"Web Marketing that Works"

Publishers of:

The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

The Building Arts Notebook, "Journal of the Guild of Building Artisans"
http://buildingartisansguild.com/

Email:  katherine@restorationtrades.com
Phone: 413-586-4748
