### ISSUE TITLE
BOTH THEMES: Place image captions below image as default

### ISSUE THREAD

**Issue by KathJohnson** [meetinghouse/cms#235]
Please change the main.css file so that captions appear centered below the image as the default. 

Attachediis an email sent by John B. on 3-26-16 detailing how it appears now and how it can be fixed, just for reference:

[Corbett Research Group Mail - Captions on tables.pdf](https://github.com/meetinghouse/cms/files/194050/Corbett.Research.Group.Mail.-.Captions.on.tables.pdf)

**Comment by jboz62** [comment]
Katherine, 

I forgot one step in doing this, it’s not a pure CSS fix. After creating the table with the caption filled in, you have to click on the “source” button and edit the table code:



However, all this might be a pointless as I just found a better solution, yet another CKEditor plugin: http://docs.ckeditor.com/#!/guide/dev_captionedimage <http://docs.ckeditor.com/#!/guide/dev_captionedimage>
Demo: http://sdk.ckeditor.com/samples/captionedimage.html <http://sdk.ckeditor.com/samples/captionedimage.html> Note: you can also see the styles drop down in action on this demo.

Looks like we need to add some updates to the CKEditor.

**Comment by jboz62** [comment]
This is now an option in the new CKEditor. Done.
