### ISSUE TITLE
BOTH THEMEs: Blog post sort order

### ISSUE THREAD

**Issue by KathJohnson** [meetinghouse/cms#241]
It looks like in the dark theme the, blog posts default to sorting oldest to newest. 

Could this be changed to the reverse, so newest posts show first, and older ones below? Thanks.

**Comment by KathJohnson** [comment]
I know you have a lot on your plate, but when you have a second, I'm hoping this is an easy change. John C. has expressed some worry that we need to get this fixed before it is noticed by the one client (S+H) who is using the blog currently.

We are also moving toward enabling the blog as an option on the light theme, so this will be applicable for other sites in the future. Let me know if you think you can get this done.

**Comment by jboz62** [comment]
I was actually looking at that over the weekend, but I don’t see what you mean. Looks to me like they are in the right order on S+H. I’m not actually sure how the menu on S+H works, where is the “builder’s notebook” coming from and how does that get populated? Are all the dark theme site going to have that same title in the menu? Maybe a screen share is in order today? I can do that at 1pm if that works for you.

**Comment by meetinghouse** [comment]
We can do that. I'll be at home, as I have a sick kid today, and I'll be
leaving the office momentarily. I have a list of things to go over with
you, and a screenshare would be good.

**Comment by jboz62** [comment]
Ok, great, let’s do that. We can push it back a little if you need to.

**Comment by meetinghouse** [comment]
John,

I'm home now, so if you want to send me a joinme link, I'm ready. Phone
here at home is 413 225-3153.

**Comment by jboz62** [comment]
Here you go: https://join.me/932-335-928

**Comment by jboz62** [comment]
@vivek-chaudhari Vivek, this is the next issue after we get the menu setup working. We need to see if we can make the blog posts sortable.

@meetinghouse  John/Erica, how do we want these to be sorted, are you just interested in changing whether it's ASC or DESC or do you want more of a drag and drop kind of interface?

Thanks,
John

**Comment by jboz62** [comment]
Closing issue #241
