### ISSUE TITLE
BOTH THEMES: Portfolio disappears from menu when position greater than 4

### ISSUE THREAD

**Issue by KathJohnson** [meetinghouse/cms#244]
@1sp @jboz62 If I set the Portfolio menu disappears or pushes other items off the menu depending on position.

I have five pages set to appear (as parents) in the menu currently, with sort order designated for them 1-5.

If I set portfolio menu position to:
0, or 6-10  - Portfolios disappears from the menu completely. All other menu items are there and in their proper order. (first screenshot below)
1, 3, 4 , or 5 - Portfolios replaces the other page that was set to that same integer. That page doesn't show up on the menu anymore. (second screenshot below)
2 - When I click update on the Admin Settings page after setting Portfolio Menu Position to 2, it defaults back to 1, and the menu appears as described above. It doesn't want to be set to position 2, for some reason.
![ss port disappears entirely](https://cloud.githubusercontent.com/assets/5922040/14895340/2544818e-0d46-11e6-8ea9-81e8667b087d.jpg)

![ss_port replaces other menu items](https://cloud.githubusercontent.com/assets/5922040/14895356/2fae2cba-0d46-11e6-8605-7fae7551d5f0.jpg)

**Comment by 1sp** [comment]
@KathJohnson I think this is related to a similar issue already mentioned by John in another thread. I have received sftp access from john to review and debug the issue.

**Comment by jboz62** [comment]
Any update on this, Sudhir? Thank you.

**Comment by 1sp** [comment]
Sorry @KathJohnson & @jboz62 for the delay. I plan to start on this and other issues tomorrow.

**Comment by 1sp** [comment]
Few changes I made regarding this issue

1. Portfolio menu position now has a default i.e 2 
2. Removed the '0' position in the options list for Portfolio position

**Comment by jboz62** [comment]
Thanks for the update, Sudhir. Does this also fix the issues with old pages not showing up when put in order?

Are these changes on branch i221?

**Comment by 1sp** [comment]
Yes, but the old pages would still need to be saved once (so that their menu information is updated as per the new structure). Please let me know if there are any further issues with this.

**Comment by 1sp** [comment]
Above comment is invalid after https://github.com/meetinghouse/cms/commit/7424287e43f552b23f287bfee80fc9fc3faeb762

The old menu items will now be automatically converted into new format at the time of deployment (using a migration)

**Comment by jboz62** [comment]
Great! Better solution, then clients won’t have to deal with it. Thank you.

**Comment by jboz62** [comment]
Closing this issue as it no longer seems to be a problem. Portfolio can now be moved to whatever position.
