### ISSUE TITLE
Light Theme: Leave Submenus expanded when a page clicked

### ISSUE THREAD

**Issue by KathJohnson** [meetinghouse/cms#256]
I'm moving this into GitHub so I can keep track of it more easily. This request came from Steve Drago at New England Soundproofing on May 11, 2016:
So I love the left nav but had one repetitive complaint. When you click on the drop down for the left nav and pick a option it will bring you to that page but closes the left nav. The complaint is the customer/user doesn’t remember what drop down they picked because it closes. Is there a way to keep it open when it navigates to the next page?

For example, If i click on “Types of rooms” and it drops down and you click “commercial Soundproofing” it brings you to that page. BUT when you on that page, the drop down isn’t expanded and the client doesn’t know where he picked. It would be nice to have that still open and the blue to show where they went to. 

John Bozaan made this comment May 18, 2016:
On this site: newenglandsoundproofing.corbettresearchgroup.com which I think went live today, although their old URL doesn’t seem to be loading. In the below email, Steve is asking for the _active_ sub-menu to be visible, meaning the sub-menu would remain open on page load showing the active page in the sub-menu. I can do this with a client side script, but I’m wondering if it’s possible to do this server side. A class, “in”, and some pseudo-classes need to get added if there’s an active sub-nav item:
![image](https://cloud.githubusercontent.com/assets/5922040/15369778/1dc55912-1d02-11e6-93f4-6b01676a5e38.png)
Sounds like a client side task to me, but thought I’d ask. Thoughts?

Then John Bozaan further commented May 18, 2016:
That wouldn’t take too long, maybe 1.5 hours? But I need to do some testing to see if it will work and not mess with the Bootstrap script that controls it, could conflict with the functionality. Did Sudhir respond on this? I didn’t see anything.

@1sp, do you have any thoughts on how long this might take for you to make this work across the board?

**Comment by 1sp** [comment]
As per the bootstrap documentation we would need to play with two classes here based on whether the current url's menu item has a parent or not(as shown in screen below). Should take around an hour or so.
![expanded](https://cloud.githubusercontent.com/assets/60359/15370055/d467d046-1d52-11e6-9d9f-646106044d05.png)
![collapsed](https://cloud.githubusercontent.com/assets/60359/15370056/d4692518-1d52-11e6-99e3-0358065dcc85.png)

**Comment by jboz62** [comment]
Katherine and I both agree, this is better to do server side as it will be available for all the sites. Let’s wait for Katherine’s go ahead on this. Thank you for the input, Sudhir.

**Comment by jboz62** [comment]
Katherine, what’s going on with the DNS setup on this site? Their main domain is still dead: newenglandsoundproofing.com <http://newenglandsoundproofing.com/> It doesn’t load the new site?

**Comment by meetinghouse** [comment]
This site isn't actually launched. It was delayed, I think just because he
is busy and doesn't have much time this week to review. Sorry I didn't
notice your comments about that earlier. Their current site at
newenglandsoundproofing.com is live and looks fine from where I'm sitting.
It's on the Servint server, not the Digital Ocean server.

Client would like to launch next week. Tuesday night is the target right
now.

**Comment by jboz62** [comment]
Yes, I looked at it earlier, it does seem to be working now, probably a server glitch when I was trying to view it before.

Speaking of server glitches, it looks like the cPanel for the RTD site is working again too.

**Comment by jboz62** [comment]
@vivek-chaudhari Vivek, this is a request from one of the clients, but is also something that should probably be part of the menu function. Can you review this issue and let me know if you can do this and how long it would take? Thanks! John

**Comment by vivek-chaudhari** [comment]
@jboz62 John, Client needs dropdown in expanded mode when they are on expand menu item, right? I have reviewed this and it will take 1-2 hours approx.

**Comment by jboz62** [comment]
Ok, that’s sounds good, Vivek. Please proceed with the changes, but don’t commit anything until I get this Github issue resolved.

Thanks,
John

**Comment by vivek-chaudhari** [comment]
@jboz62  We have implemented it as part of Light Theme doing on server side, let me know whenever I want to commit it.

**Comment by jboz62** [comment]
Ok, thanks Vivek. I’ll take a look.

**Comment by jboz62** [comment]
Done.
