### ISSUE TITLE
HEIRLOOM WINDOWS: Top nav menu portfolios not stacking

### ISSUE THREAD

**Issue by KathJohnson** [meetinghouse/cms#257]
@jboz62  - I'm pretty sure this will be a css thing and not a code base thing, but I'm putting it into GitHub anyway.  If it ends up being a server-side code base thing, we might need to pause on it, as the procedure is getting formed.

Erica noticed yesterday that on the Heirloom Windows site, where you created a custom top menu, when you click "Portfolios" the drop-down of portfolios doesn't stack in one column. We don't see any extra spaces or tabs or anything that might cause weird formatting, so I'm hoping you may be able to help with this.

It may be the same for weatherstrippingkit also. We don't have any real portfolios set up there, so I haven't verified, but I just want to include it here. Edited to add: Erica will be putting some content in weatherstrippingkit, so we may see the same thing there.

![screenshot 2016-05-19 at 1 46 58 pm](https://cloud.githubusercontent.com/assets/5922040/15403687/38d94e5e-1dc8-11e6-8f8b-ff225448bb9d.png)

**Comment by jboz62** [comment]
Yeah, it was noted on the test site, it is a simple CSS change. If you want to add:
`.open > .dropdown-menu li {
    clear: both;
}`
to the custom css file, that will fix it. I'll have to add this to the originalTheme.css file and commit it to the repository for so it works on all light theme sites.

**Comment by jboz62** [comment]
let's leave this issue open as a reminder to add that. thanks for the reminder!

**Comment by jboz62** [comment]
We should probably also add these swanky drop down indicators too so it's more obvious there's a drop down menu there. Had them on Steve's site before he nixed the top menu. They point upward when the drop down is open.

![screen shot 2016-05-19 at 1 56 08 pm](https://cloud.githubusercontent.com/assets/11739120/15404015/9d0a5f7a-1dc9-11e6-917e-f719714d05a8.png)

![screen shot 2016-05-19 at 1 58 42 pm](https://cloud.githubusercontent.com/assets/11739120/15404066/d8ea38c6-1dc9-11e6-9b46-01a72fecd82c.png)

**Comment by KathJohnson** [comment]
Great! I applied that change to the heirloom windows Customproject css file and it looks good now. I don't like to step on your toes, so I'm letting you know I did that. I concur with keeping this open for now.

Is the drop-down carrot a css-controllable thing?

**Comment by jboz62** [comment]
Sorry, didn’t hit “send” on this email yesterday. Yes, that’s all created with css. I can send it to you if you want to add it to this site.

Did you notice that the left menu is still showing up on the portfolio pages? Must be a bug.

**Comment by jboz62** [comment]
I added that css to this site for that arrow function. It's on line 104 of the custom style sheet if you want to copy/paste it onto any other sites. I'll add it to the originalTheme.css file.

![screen shot 2016-05-20 at 10 14 35 am](https://cloud.githubusercontent.com/assets/11739120/15430695/702bf3e6-1e74-11e6-8254-807f7b78dc6e.png)

**Comment by KathJohnson** [comment]
Thank you much. I've noted this bit of advice and code scraps for future use and I'm closing this issue now.
