### ISSUE TITLE
Remove specific text from project page

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#26]
The words "Click on images below to enlarge." appear at the bottom of each Project page. This is not applicable in the dark theme, so please just remove this as boilerplate (it should stay in light theme, however).
 
Example:
http://cms.zigbop.io/projects/4
![screenshot 2015-01-22 at 1 17 08 pm](https://cloud.githubusercontent.com/assets/5215893/5861611/fb2a65d6-a238-11e4-9540-ddc0b2644476.png)

**Comment by acavanagh** [comment]
Hi John - I just wanted to chime in and say that these tickets are great,
they're all very clear and just the right size to be actionable.  So far it
looks like all things that I'll be able to resolve very quickly.  Thanks!

**Comment by meetinghouse** [comment]
That's nice feedback to get. Thanks!

Sincerely,

Katherine Johnson, Content Developer
The Custom Building & Restoration Trades Directory
<http://www.restorationtradesdirectory.com/>
http://www.restorationtradesdirectory.com
(413) 584-0288

Published by:
Corbett Research Group <https://mail.google.com/>
"Building Websites that Work - - for the Building Artisans."
http://www.restorationtrades.com
