### ISSUE TITLE
BOTH THEMES: Hardcode "Home" on menu instead of using page title on homepage.

### ISSUE THREAD

**Issue by jboz62** [meetinghouse/cms#261]
@1sp @KathJohnson 
We need to have the "Home" menu item hardcoded as "Home" instead of using the title H1 tag on the homepage for light theme. Currently, when you put a title in the title field on all pages, it shows up in the menu as that title, this if fine except on the homepage where we need it to say "home" in the menu.

We are hiding the first H1 title on the homepage with CSS, but it flashes on page load, which isn't good. It would be better to have this built into the script. You can see an example of the css flash on here: http://heirloomwindows.corbettresearchgroup.com/ Look for the word "home" above the title. That's the actual title that is also displayed in the menu. It should be that no matter what is put in the title, it says "home" in the menu, or maybe there just shouldn't be a title field on the homepage? Sudhir, maybe you have some ideas on the best way to do this?

Katherine, thoughts on this?

Let's discuss.

**Comment by meetinghouse** [comment]
My thoughts on this are: yes. But processes and the ability to deploy
changes safely have to come first.

**Comment by jboz62** [comment]
@vivek-chaudhari Vivek, while you're working on the menu for the Blog change, can you think about this issue and let me know what you think? We need the "home" button to always have the title "home" no matter what the user titles the home page. Please review my description for the details on Github.

Thanks,
John

**Comment by vivek-chaudhari** [comment]
@jboz62 I don't think so we need to change current way of displaying menu. If flashes is the issue for http://heirloomwindows.corbettresearchgroup.com/, we can do one thing, we can provide checkbox on create/edit page namely "Hide title from page" , if it is checked then systen will hide it otherwise will display title.

**Comment by jboz62** [comment]
That sounds like a great idea, Vivek. Would that hide all page titles or just on the homepage?

--
John Bozaan
Bozaan Design
413-437-0097

**Comment by vivek-chaudhari** [comment]
@jboz62 Each page have this configuration option, by default it is unchecked and showing title and if we checked it, will not show title for respected page.

**Comment by jboz62** [comment]
@meetinghouse John, please review Vivek's plan for this issue. His suggestion is to "Provide a checkbox on the create/edit page, namely "Hide title from page", if it is checked, then system will hide title, otherwise it will display the title. Each page [would] have this configuration option, by default it is unchecked and showing title and if we checked it, it will not show title for respective page."  This allows us to check the box on the homepage to hide the title and name it "Home" so it shows up right. I think this is a good plan. Thoughts?

Btw, can you have Erica add herself to Github so we can message her directly? I'm hoping you get this, but I'm not sure. Katherine used to answer them. Thanks!

@vivek-chaudhari Vivek, would it be possible to pre-populate "Home" into the title for the homepage and default the checkbox to "checked"? Please let me know if you can do that and how long it would take. Thanks! 

John B.

**Comment by vivek-chaudhari** [comment]
@jboz62 John, are you talking about pre-populate "Home" into the title when we are on '/pages/create' page or when we seed page into database using seeder?

**Comment by jboz62** [comment]
Yes, but only for the home page. It would probably have to be a “read-only” field on the homepage so it’s not editable. I’m not sure what "when we seed page into database using seeder” means.

**Comment by vivek-chaudhari** [comment]
When we run database seeder on fresh installation of CMS, we can provide home page title as "Home" and make sure that it is read only when we visit this page in edit mode.

**Comment by jboz62** [comment]
That sounds like a good solution, Vivek, we do that with a lot of other pre-populated content on the pages and other places. That combined with the ability to hide the title via the checkbox, like you mentioned, sounds like it would solve this. How much time would this take?

**Comment by vivek-chaudhari** [comment]
@jboz62 It will consume 2-3 hours approx.

**Comment by jboz62** [comment]
@vivek-chaudhari Ok, sounds good. Let me clear this work and the other menu sort issue with John C. before we begin. Thanks

**Comment by jboz62** [comment]
@vivek-chaudhari Please proceed on this issue, Vivek. Let me know if you have any questions on the setup or need any clarification. Thanks, John

**Comment by jboz62** [comment]
@vivek-chaudhari On thing I think we need to change on this, though. Can we make the "Home" page title **editable** instead of **read-only**? I saw one of our sites uses "Welcome" on their site, this would mess that up for them. Maybe what we need to do is pre-populate "Home", but have it be editable so it can be changed if needed. Thoughts?

**Comment by vivek-chaudhari** [comment]
@jboz62  Now review this please. Added hide title option as checkbox while create/edit page and when we install a fresh copy of CMS and run seeder. System will seeds home page title as 'Home' and it is editable later.

**Comment by jboz62** [comment]
Ok, thanks Vivek, I'll take a look. I still can't do a pull request on your last changes. Did you figure out what is wrong?

**Comment by jboz62** [comment]
Setup is working.
