### ISSUE TITLE
BOTH THEMES: Forge deployment bug

### ISSUE THREAD

**Issue by KathJohnson** [meetinghouse/cms#263]
@1sp 

I haven't made much headway so far with discussions with our sys admin, but I'd like to press ahead anyway. It seems to me that the first bottleneck is problematic Forge deployment.

You suggested the following:

It could be that we have uncovered a bug in forge. I would suggest to put a command auditor/logger on the server for some time to see the process execution flow during the forge deployment.

Is this something you can do?

**Comment by 1sp** [comment]
Sorry for replying late. I am travelling right now and can surely do this as soon as I resume work (I am available from coming 11th onward ). Then we can do a test deployment run to analyse what happens during the whole process.

**Comment by meetinghouse** [comment]
@1sp, if you're around today, can you let me know what is involved for me
with putting a logger on the server? And then let's find a time when I can
deploy and we'll see what happens and can restore S+H if needed.

Sincerely,
Katherine Johnson, Research Director
Corbett Research Group
http://www.restorationtrades.com
"Web Marketing that Works"

Publishers of:

The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

The Building Arts Notebook, "Journal of the Guild of Building Artisans"
http://buildingartisansguild.com/

Email:  katherine@restorationtrades.com
Phone: (413) 475-3154

**Comment by KathJohnson** [comment]
@1sp, hello. Is there a good time to work on this today? I can make time tonight (my time) if that is more convenient for your schedule. I would love to move forward on this and start knocking these delays down so we can go ahead with needed programming changes. Thanks.

**Comment by 1sp** [comment]
Lets do it today?

**Comment by jboz62** [comment]
@KathJohnson Did you get Sudhir's message about working on adding the logger today? Is this still needed after the fixes you and Andrew did?

**Comment by meetinghouse** [comment]
Sudhir! So glad to see you back on your feet!

Andy made some changes (I am not completely sure what) and I refreshed the
site token for all the sites. The problem doesn't seem to be occurring now,
but he did agree with you that it might be a bug in Forge. So for the
moment, we can keep an eye on the Recent Events log. I haven't seen any
unexpected deployments for about a week, but I will check there after each
deployment.

I will be in touch shortly about what the next step is, though.

**Comment by KathJohnson** [comment]
I am closing this issue now. Thanks.
