### ISSUE TITLE
LAUNCHED SITES: Turn off debugger

### ISSUE THREAD

**Issue by KathJohnson** [meetinghouse/cms#266]
@jboz62 Can you tell me how to turn off the debugger for the launched sites? This is probably something I could do, with direction. If not, I will add requesting of debugger disabling to my launch checklist.

A site to start use for instruction could be newenglandsoundproofing.com

**Comment by jboz62** [comment]
It's not difficult, but it should be committed on a branch and merged to blog. The file is in app/config/app.php - line 16 change to 'false': 'debug' => false,

If you have trouble with it let me know and I'll send it, just a bit buried today.

**Comment by meetinghouse** [comment]
This is not an urgent issue for today, so we can circle back to it. This
would turn off the debugger for all sites that had the current code base
deployed to them, correct? I'd like to be able to keep it turned on for
test sites. Is there an easy way to simply turn it off when a site is
launched live? I propose that with the understanding that the debugger is
actually useful for resolving problems. If it isn't useful, then of course
we can turn it off across the board.

(I will be, at some point, setting most of the staging sites to be in
maintenance mode so they don't get picked up by Google as the content is
being developed. That way any debugger pages should also be locked up, so
that will hopefully resolve the security risk.)

Sincerely,
Katherine Johnson, Research Director
Corbett Research Group
http://www.restorationtrades.com
"Web Marketing that Works"

Publishers of:

The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

The Building Arts Notebook, "Journal of the Guild of Building Artisans"
http://buildingartisansguild.com/

Email:  katherine@restorationtrades.com
Phone: (413) 475-3154

**Comment by jboz62** [comment]
Not sure if this still needs answering, but it would turn off the debugger for whatever site you deploy the change to. I think if someone needs to test something on a site, they could just change it temporarily via FTP and then change it back when they finish. I don’t think it needs to be on for all of the sites, test sites is probably ok, like you mentioned.

Best,
John
--
John Bozaan
Bozaan Design
413-437-0097
www.bozaandesign.com <http://www.bozaandesign.com/>
