### ISSUE TITLE
BOTH THEMES: Menu management to include blog function

### ISSUE THREAD

**Issue by KathJohnson** [meetinghouse/cms#267]
@1sp This is related to closed issues #221 and #260. The menu management piece is working for the light theme (with a couple additional items that are tracked in issues #252 and #244). 

I am opening this issue because it is necessary in order to make the codebase safe to push to all sites -- both dark and light theme. Currently, I am unable to push current code to the S+H website (or any future site that is set to dark theme) because it messes up the left nav menu. So it is important to resolve this.

It would be ideal to allow menu management to happen in the dark theme as it does in light theme, if that is feasible. Can you take a look and see if it is? 

I'd love to be able to work on this issue with our new process, which isn't in place entirely yet. But if you'd like to create a tagged release for this, and also script the backup copying of the db, this might be a good time to do it. If you'd like separate issues for those things, please tell me and I am happy to do that.

**Comment by 1sp** [comment]
@KathJohnson Let me check the menu management on dark theme and update here accordingly..

For the new process, It would be good idea to proceed with it as we are going to deploy a feature/enhancement. We can adopt the semantic versioned tagged releases right away. I can also start working on the db backup script. I would suggest that we track it in a separate ticket.

**Comment by meetinghouse** [comment]
Thanks. I've created Issue #268 for the back up script.

**Comment by KathJohnson** [comment]
@1sp - Hi. Do you have any thoughts on how to make the menu management piece work for the dark theme? Doing so would heal the rift between the current code base and the dark theme site (of which we will soon have two). 

If you'd like to chat about this at a more convenient time for you, I can be available tonight (my time), which I believe is morning your time. Perhaps about 9am for you tomorrow (July 20)?

**Comment by jboz62** [comment]
As per our discussion in the last meeting, the blog functionality with the dynamic menu needs to be added to both themes:
- We need the ability to name the blog to whatever is needed on the menu item (e.g. Builder's Notebook). 
- We need the blog to be enabled/disabled via the admin settings.
- Dark theme will have sub-menu items (see the S+H site for example).
- Light theme will utilize a drop-down on the Top Menu and an accordion menu on the left sidebar menu (as it is now).

**Comment by jboz62** [comment]
Seems there are no issues reported on the new blog setup from Vivek. Closing this issue. Well done, @vivek-chaudhari.
