### ISSUE TITLE
New Site: shlandscaping

### ISSUE THREAD

**Issue by KathJohnson** [meetinghouse/cms#269]
@1sp S+H would like a second site, just like the first in structure, but with different content, of course. Normally, I'd just deploy a new staging site and set it to dark theme. But since the current code base doesn't match what's on S+H, the structure would be different. 

Do you know of a way to copy the code and also content of a site wholesale? Then we could go in and wipe out most of the content, but the menus and such would still be there.

I know this is not totally opportune timing, but if it's possible, can we do it?

**Comment by 1sp** [comment]
@KAthJohnson I believe if you copy the site's folder and save it with a
different name (and map copied folder to a domain) it would be equivalent
to duplicating a site 's code and its content.

On Wed, Jul 6, 2016 at 10:09 PM, KathJohnson <notifications@github.com>
wrote:

> @1sp <https://github.com/1sp> S+H would like a second site, just like the
> first in structure, but with different content, of course. Normally, I'd
> just deploy a new staging site and set it to dark theme. But since the
> current code base doesn't match what's on S+H, the structure would be
> different.
>
> Do you know of a way to copy the code and also content of a site
> wholesale? Then we could go in and wipe out most of the content, but the
> menus and such would still be there.
>
> I know this is not totally opportune timing, but if it's possible, can we
> do it?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/meetinghouse/cms/issues/269>, or mute the thread
> <https://github.com/notifications/unsubscribe/AADrx_rarpq4KBZZkL0qjEJ72mzr9lleks5qS9pQgaJpZM4JGRiz>
> .
>



-- 
Sudhir Porwal

**Comment by KathJohnson** [comment]
@jboz62 I can launch a new the staging site shlandscaping.corbettresearchgroup.com.

Do you know how to do what Sudhir has described above to get the content and code copied over from the existing sh site? I imagine we would have to delete the folder that gets created by creating the site at all, then replace it with a copy of the sh site's folder, and then map it to the new domain. Is that right?

**Comment by jboz62** [comment]
Sorry, missed this email. It’s not too difficult, you really just need to clone/make a copy of the whole directory of the S+H site, then rename it to shlandscaping.corbettresearchgroup.com. Then point/map the domain to that new directory. I can clone the site for you, if that helps.

**Comment by jboz62** [comment]
@KathJohnson Katherine, I copied the S+H directory to a new directory called shlandscaping.corbettresearchgroup.com. Please map the domain to that directory and let's see if everything is working ok. Thank you.

**Comment by meetinghouse** [comment]
I haven't actually created the site through Forge yet. So I can do that,
but I am required to install a repository. That will overwrite the
directory, I think, with something that doesn't work for dark theme. Can
you re-copy the directory after I deploy? I'll hold off creating the sample
site until I hear from you.

**Comment by jboz62** [comment]
Sure, I can do that, but I’m not sure what the outcome would be. Might be good to get Sudhir’s input on this.

**Comment by KathJohnson** [comment]
This site is up and running. There will probably be some further changes coming down the line that will need decision-making as far as custom ftp changes vs. programming changes to keep it under version control. But for the moment, shlandscaping.corbettresearchgroup.com exists and seems to work and has some css customization already applied by John Bozaan.
