### ISSUE TITLE
BOTH THEMES: Add custom.js file

### ISSUE THREAD

**Issue by KathJohnson** [meetinghouse/cms#270]
@1sp - Can you please add a custom.js file and then add it to the gitigore file so custom javascript can be added to individual sites and have it not get overwritten upon deploy? Thanks.

**Comment by 1sp** [comment]
@KathJohnson I can add a link to "assets/js/custom.js" in main.blade.php and add "assets/js/custom.js" in .gitignore . Is this what you want?

(Actual creation of the "assets/js/custom.js" on each site would be done manually ?)

**Comment by KathJohnson** [comment]
I think that will be fine. @jboz62, does that work for you?

Let's particularly be sure to add it to the site example1. That is the site that gets the content copied for any new site I launch, so then at least any new sites will have it already, without having to be manually added. Thanks.

**Comment by 1sp** [comment]
I just merged changes into meetinghouse:blog (https://github.com/meetinghouse/cms/pull/271)

**Comment by meetinghouse** [comment]
Great! John, is that what you need?

**Comment by jboz62** [comment]
Yes, perfect! I’ll add that script once we deploy to NES. Is it safe to do that? Looks like you tried on the 5th and it failed.

**Comment by jboz62** [comment]
I just ran the deploy, looks good. I'll upload the script.

**Comment by jboz62** [comment]
@KathJohnson This script has been added, Katherine, please alert Steve to make sure everything is working right.

**Comment by meetinghouse** [comment]
Thank you! I've contacted Steve and we'll see what his testing turns up.
