### ISSUE TITLE
LIGHT THEME: Finish Drag and Drop Admin Menu Sort Feature.

### ISSUE THREAD

**Issue by jboz62** [meetinghouse/cms#276]
@vivek-chaudhari Vivek, we have a drag and drop Admin Menu setup in the admin on **light theme**. It works to a point, but does not include the new sub-menu capability. Can you take a look at that and let us know if you can make that work and give us a time estimate? It should work something like this: https://johnny.github.io/jquery-sortable/ Thanks, John

**Comment by vivek-chaudhari** [comment]
@jboz62 It will take 4-5 hours to provide sub menu capability, and it will work 1 level only, not more than it.

**Comment by jboz62** [comment]
Thanks, Vivek. I didn’t think about if they add a second level, it doesn’t look like you can do a second level anyway. Is that possible if someone requests that feature? Let me check with John to see if he wants to move ahead with this.

**Comment by vivek-chaudhari** [comment]
We can add n-level of menus as we have on wordpress but it needs lot of changes on light theme, need to make database changes, need to make changes on left and top navigation rendering and so on.

**Comment by jboz62** [comment]
Hi Vivek, 

Sorry for the delay. Can you go ahead and execute this plan? I still need to check the last changes. I’ll get to that soon, very behind after being sick.

Thanks and regards,
John

**Comment by vivek-chaudhari** [comment]
@jboz62 Okay.

**Comment by vivek-chaudhari** [comment]
@jboz62 Please review it. It works fine till this level http://www.awesomescreenshot.com/image/1807036/a1ae802599ac1f30f6de09563f4218f6 . I have tried to support n-level but it cause issue while saving. I will check it later if we need to go ahead.

**Comment by vivek-chaudhari** [comment]
@jboz62 should we provide n-level of navigation, I have tried on my localhost and seems to save proper data on database? Now only displaying menus items in it's order is left.

**Comment by jboz62** [comment]
Hi Vivek, it looks like you have 4.5 hours in, how much additional time will it take to do the n-level display?

**Comment by vivek-chaudhari** [comment]
@jboz62 It will take 2-3.5 hours more to display it. I have worked offline for providing this to you.

**Comment by jboz62** [comment]
Ok, that’s sounds fine, please proceed.

**Comment by vivek-chaudhari** [comment]
@jboz62 Okay..

**Comment by vivek-chaudhari** [comment]
@jboz62 Now review it. Now you can add n-level navigations for light theme.

**Comment by jboz62** [comment]
@vivek-chaudhari Hello Vivek, I'm seeing an issue with the menu setup on the light theme. When I turn off a menu item (uncheck the "Make this page a menu item" checkbox) it doesn't remove the item from the menu and the menu item goes to the first position (0). Can you take a look at that? I have it running on http://demotest.corbettresearchgroup.com/ Thanks - John

**Comment by vivek-chaudhari** [comment]
@jboz62 Okay John I am looking on this issue.

**Comment by vivek-chaudhari** [comment]
@jboz62 Now review this. whenever we unchecked this checkbox then menu_name goes to blank and it's menu order will be 0. Now we have resolved this.
