### ISSUE TITLE
DARK THEME: Make Homepage Content Area Text Viewable.

### ISSUE THREAD

**Issue by jboz62** [meetinghouse/cms#278]
@vivek-chaudhari Hi Vivek, we need the ability to add text to the homepage on Dark Theme. Currently, we have a slideshow that appears in the background on the homepage of dark theme, but we'd like to also be able to add text. That capability is disabled now, we're wondering if it's possible to have both the slideshow and text on the same page. I added some code to the main.blade.php file to add some SEO text to that page for S+H, but it would be better if we can do that via the page content area in the admin. 

Is that possible? Please let me know if that can be done and, if so, how long it would take.

Thanks,
John

**Comment by vivek-chaudhari** [comment]
@jboz62  yes it is possible. Home page contents are already added from backend, but not displaying on front end. We can easily achieve it. It will take 1-2 hours for me.

**Comment by jboz62** [comment]
Vivek, will the slideshow still display even with the contents displaying? If so, please proceed to execute this change. Thanks.

**Comment by vivek-chaudhari** [comment]
Yes, slideshow will be display but texts are going to visible on slider. Background have slider and front end will texts.

**Comment by vivek-chaudhari** [comment]
@jboz62 Now check this, now whatever content are added in content editor will viewable on home page.
