### ISSUE TITLE
No edit button available for Portfolio page

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#29]
When logged in and viewing the portfolio page, I do not see an edit button.

http://cms.zigbop.io/portfolio
![screenshot 2015-01-22 at 1 44 48 pm](https://cloud.githubusercontent.com/assets/5215893/5862076/dab65d10-a23c-11e4-8942-290f57e19411.png)

Same problem for the sub-portfolio pages, tag, tag1, tag2. Figured I'd just put that in the same issue. I bet it will get fixed at the same time.

http://cms.zigbop.io/projects/tags/tag
![screenshot 2015-01-22 at 1 46 33 pm](https://cloud.githubusercontent.com/assets/5215893/5862117/1a0bfe02-a23d-11e4-996a-33d3d3460a82.png)

**Comment by acavanagh** [comment]
The Portfolio page is a dynamic listing of Projects.  There's nothing to edit.  If you want to change the text or the image for a project listing you have to edit the project.  I could put an edit link next to the title of each project, if that helps.

**Comment by meetinghouse** [comment]
I get it now. The sub-portfolios are the tags you enter on the fly in a project, not a separate entity you create in the database and then assign to different projects. 

OK, then. This looks good. Thanks.
