### ISSUE TITLE
Portfolio selection confusing in Project edit page

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#30]
While logged in, when I go to the project edit page, there is a section for "Related Portfolios." This is not applicable for the dark theme and is confusing. My understanding is that the next section, "Tags," is what is used for the dark theme.

Please remove the Related Portfolios option from the edit screen. It should stay in the light theme, however. 

I don't know the function of the Sort drop down in the dark theme yet, so if that is not coupled with the Related Portfolios option, then please do not remove it as part of this issue.

http://cms.zigbop.io/projects/1/edit
![screenshot 2015-01-22 at 1 52 37 pm](https://cloud.githubusercontent.com/assets/5215893/5862222/f02e8ce8-a23d-11e4-8e5d-6e533a1108b7.png)

**Comment by acavanagh** [comment]
fixed
