### ISSUE TITLE
Dark Theme: Add "active"/"not-active" classes to /projects/tags and /posts/tags sub-menu items.

### ISSUE THREAD

**Issue by jboz62** [meetinghouse/cms#310]
@vivek-chaudhari When you click on a sub-menu item for projects (portfolios) or blog and the page loads, there is no "active" class on the active menu item. Can you add the active/not-active classes functionality to those sub-menus on dark theme like it is on the main menu?

You can see the projects sub-items on Steve's site here: http://revrbacoustics.corbettresearchgroup.com/projects/tags/Bars

And, of course, the posts here: http://shlandscapesitework.com/posts

Thanks,
John

**Comment by jboz62** [comment]
@vivek-chaudhari Vivek, did you fix this already? I just did a deploy on REVRB and it didn't clear the settings for "portfolio" (projects). Not sure why it did before, maybe just review to be sure everything is okay. Thanks!

**Comment by vivek-chaudhari** [comment]
@jboz62 Yes john we fixed it already but don't know why it is not working now.

**Comment by vivek-chaudhari** [comment]
@jboz62 Now can you please review this? Try to pull it from vivek-work branch.
