### ISSUE TITLE
Fix help links

### ISSUE THREAD

**Issue by acavanagh** [meetinghouse/cms#39]
Most of the new fields - esp in blog posts - have links to the wrong help.  Need to create the help pages for these and fix the links, then turn it over to John to populate the pages.

**Comment by meetinghouse** [comment]
Am I correct in understanding that the help links are connected to a field
in the database, then?

If so, I'm thinking it's not easily possible to create separate help
information for fields that are shared between the light theme and dark
theme. For instance, can I create different help text for the Project
Default Image Uploader (on the project edit page) for the two different
themes?

Sincerely,

Katherine Johnson, Content Developer
The Custom Building & Restoration Trades Directory
<http://www.restorationtradesdirectory.com/>
http://www.restorationtradesdirectory.com
(413) 584-0288

Published by:
Corbett Research Group <https://mail.google.com/>
"Building Websites that Work - - for the Building Artisans."
http://www.restorationtrades.com

**Comment by acavanagh** [comment]
They're not in the database.  All the help links point to various anchors on this page:
http://www.restorationtrades.com/help.html

I don't actually know where that page lives, but I assume someone on your end does.   That page needs to get updated, and then I'll make sure that the help links are correct.  We need a help for Tags, and for any of the fields on the posts edit page that need their own help section.

**Comment by meetinghouse** [comment]
This is old history, and help links are being managed on our end. So I'm closing this one, thanks.
