### ISSUE TITLE
Show tags for blog posts when viewing any blog submenu category

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#42]
When I go to Builders Notebook, http://cms.zigbop.io/posts, I see recent blog posts and a sub-menu of blog post tags also.
![2](https://cloud.githubusercontent.com/assets/5215893/5944367/7431b8fc-a6f4-11e4-9f3f-1901a277e56c.png)
When I click one of the tags I can view the posts in that tag, but the submenu disappears.
http://cms.zigbop.io/posts/tags/new-tag
![3](https://cloud.githubusercontent.com/assets/5215893/5944414/bea20f04-a6f4-11e4-9e0d-6a34fd847b97.png)

Please make the submenu of blog post tags visible on the tag page.

**Comment by meetinghouse** [comment]
I see this change. But is the text white? I can see the number 1 in the dropdown, and I can see other numbers when I mouse through the list, but if I select something, the box appears blank.
http://cms.zigbop.io/projects/2/edit
![3](https://cloud.githubusercontent.com/assets/5215893/6065195/4b90c800-ad31-11e4-82bc-9f451319e626.png)

**Comment by acavanagh** [comment]
what browser/os are you using?  on chrome/mac it looks like this:
https://www.dropbox.com/s/zmciwut7voly0gz/Screenshot%202015-02-05%2019.09.17.png?dl=0
so it's probably a browser issue - as soon as I can re-create it I'll fix it, but need more info.

**Comment by meetinghouse** [comment]
I saw this first on a Chromebook, so in Chrome. I have since found the same
thing on my Windows laptop using Firefox, Chrome, and IE. I haven't checked
in Opera, but it is consistent across these three so far.

Sincerely,

Katherine Johnson, Content Developer
The Custom Building & Restoration Trades Directory
<http://www.restorationtradesdirectory.com/>
http://www.restorationtradesdirectory.com
(413) 584-0288

Published by:
Corbett Research Group <https://mail.google.com/>
"Building Websites that Work - - for the Building Artisans."
http://www.restorationtrades.com

**Comment by acavanagh** [comment]
This is going to be a little tricky to fix because I can't re-create the problem and it looks normal for me.  I added a more specific css rule - I'll assign this ticket back to you to see if you still see the problem.  If not, then please close the issue.  If the problem persists, then just assign it back to me with a note and I'll try something else.

**Comment by meetinghouse** [comment]
Unfortunately, I still see it the same way.

**Comment by meetinghouse** [comment]
This issue is also occurring with the Project weight field in the Project create and edit screens.

**Comment by meetinghouse** [comment]
This is really old and isn't really applicable anymore. I'm closing it.
