### ISSUE TITLE
Link to blog post from tag page broken

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#43]
When I go to a blog post tag page, http://cms.zigbop.io/posts/tags/test-tag
![4](https://cloud.githubusercontent.com/assets/5215893/5944456/19f79f0e-a6f5-11e4-93a0-33b979015ec9.png)
and click on one of the posts, I get to an error page.
http://cms.zigbop.io/posts/11
![5](https://cloud.githubusercontent.com/assets/5215893/5944474/3980d3a4-a6f5-11e4-8091-3835cc6d43de.png)

**Comment by acavanagh** [comment]
This is an artifact of the fake data I used - I had it generate a bunch of random tags, but they don't necessarily correspond to an actual post or project. I'm going to delete all the tags and add a few manually so that they're still there for testing but don't just link off into oblivion any more.
