### ISSUE TITLE
Image verbiage in blog post edit page confusing

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#45]
On the blog post edit page, http://cms.zigbop.io/posts/4/edit
the image uploader labels are confusing. They reference project images rather than blog post images. Can these labels (and, later, the associated help text links?) be changed to reflect that the image is for a blog post rather than a project?
This includes the label, "Project Default Image Uploader" and also the explanatory text underneath that currently reads "This is the image we will use for the default project image."
![7](https://cloud.githubusercontent.com/assets/5215893/5944831/02fad692-a6f8-11e4-9849-460216dad8f5.png)

**Comment by acavanagh** [comment]
this is done, but you might consider changing the verbiage on the help page to be more generic so you can use the same help text for project or post default images, or any others that might come along later.  Unless you want the text to be different for each, of course.

**Comment by meetinghouse** [comment]
That is good advice about making the help verbiage more generic. The help pages are my next project, in fact. 

Am I able to put different help links in for the dark theme and light themes? If so, where can I find the distinct help repository for the dark theme? Currently, all the help links are in cms_help, but I think if I make changes there it will affect the help links for both light and dark themes, right?

**Comment by acavanagh** [comment]
hmm, that's a good point.  I was thinking that since the help links go to a particular section of the help document, and since most of the fields are the same, you could just use the same document.  I can see how you might not want that to be the case.  Using the same document and just having the oddball links in the dark theme link to their own section would be the quickest/cheapest solution, but it wouldn't be to hard to set up a seperate document for the dark theme, keep most of the links the same, and just change the oddball links in the dark theme to link to the new document.

**Comment by meetinghouse** [comment]
I think we'd like a separate document to put in the help links for the dark theme. Can you make a copy of the current help document so it has the links for now, and let me know where it is so I can edit them later?

**Comment by acavanagh** [comment]
That document lives on the restoration and trades directory server.  I'm not sure why.  Do you want me to create a new document there (not sure that I still have access) or set it up in the same git repo as this project?

**Comment by meetinghouse** [comment]
We may not be communicating clearly. The help document itself lives on the restorationtrades.com site. I believe that is so that it is very easy for John to update. The links to the help document live in the cms_help repository, which I edited to include the links where we wanted them. What I'd like to do now is create help links for the dark theme as well, but I don't have anywhere to put them where they won't also show in the light theme (that I know of). 

The plan is currently to split the help topics over several pages on restorationtrades.com, so the links in the light theme will be getting updated anyway. There will be separate pages for where dark theme and light theme help is different, and where they are the same, the link will point to the same page.

So what I thought I was asking for is a separate repository for dark theme help. It can start off as a copy of the light theme help, and I will edit links wherever necessary. Is that possible, and do you have advice concerning that?

**Comment by acavanagh** [comment]
Right now I don't think I have access to the cms_help repository; I don't see anything in it and I don't have access to the settings.

I think that you should keep the pages wherever they are easiest for you to edit, whether that be in the resto-trades main site or in a repo on github.  If I understand what you're saying correctly, it sounds like you'll have a general help page that works for everything, and then a light help and a dark help page that holds version-specific help.  That makes a lot of sense to me.

It seems like the place where you might need one help link for the light theme and a different help link for the dark theme would be on project edit pages, as they're handled a little differently in the dark theme.  In those cases we'd need to but in an @if statement so the correct link would show on the correct theme - something like:
```
@if($settings->theme == true)
<a href="http://www.restorationtrades.com/dark_help.html#project_web_address" target="_blank">Help</a>
@endif

@if($settings->theme == false)
<a href="http://www.restorationtrades.com/light_help.html#project_web_address" target="_blank">Help</a>
@endif
```

**Comment by meetinghouse** [comment]
I was being dumb. The help links are in the master repository, not in the help one. I think the help one was created to hold help information, but then John opted instead to use the restorationtrades.com site, so the links are just put directly into the master. They are in the cms\app\views area, in the create.blade.php and edit.blade.php file wherever appropriate.

I've inserted an @if statement as directed above for the help link for the field. I'm now waiting for it propogate through so I can see how it works.

**Comment by acavanagh** [comment]
That sounds right, but if you're editing the code in github make sure that
you're on the blog branch.

**Comment by meetinghouse** [comment]
Aha, perhaps that explains the looooong delay I'm seeing in the help link changes propagating. I can't recall how long to expect it to take. I put the @if statement in the master branch, which is where the help links have lived. Tomorrow I will move links into the blog branch and see how much duplication I may need to do to get them showing up in both themes.

**Comment by acavanagh** [comment]
You should probably take the @if statement out of the master branch, it
might make those sites throw an error because there is no $settings->theme
on the master branch.
At some point we should talk about deployment - I think it makes sense to
eventually merge the 'blog' branch in to master and set things up so that
you can deploy a new site and then just choose the options you want -
blog/no blog, light/dark, etc.  All we really need to do to make that
happen is to make sure that the site still looks right with the dark theme
off, that the dark theme looks ok with no blog, and that the light theme
looks ok when it has a blog.  We can even have separate default content for
each version if necessary.

**Comment by meetinghouse** [comment]
OK, this is such a tiny thing but it is driving me crazy. I am using the code you sent to put help links into the blog branch. I've only done one file so far (cms/app/views/pages/edit.blade.php) 

The link works, yay! But for some reason, that I can't for the life of me see, the word "Help" now has a space after it, before the closing parenthesis. I can't find any spaces. John couldn't find it either. Can you see where the space is coming from?

**Comment by acavanagh** [comment]
put the parens inside the if statement, around the <a> tags - like this:
https://www.dropbox.com/s/rqeedlmpixv4nk5/Screenshot%202015-03-03%2020.44.04.png?dl=0

**Comment by meetinghouse** [comment]
Thanks for your help -- got rid of the space. Since this issue has wandered so far afield of the original purpose, and the original purpose has now been served, maybe it should be closed? I'll leave it up to you.
