### ISSUE TITLE
Home page edit confusing

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#47]
The edit screen for the homepage in the dark theme is confusing. In the new theme, only the Page Browser Description and Page Web Address fields are editable in any practical way. 

All the other fields that show here as editable don't have any impact on the site. Is it possible to hide the Page Heading and Page Main Body, as well as their related help links?
http://cms.zigbop.io/pages/1/edit
![1](https://cloud.githubusercontent.com/assets/5215893/6064808/7f824d12-ad2e-11e4-8c34-11c941aeaabb.png)

**Comment by acavanagh** [comment]
These should be hidden on the homepage for the dark theme now.
