### ISSUE TITLE
Can't navigate to individual blog posts from Builder's Notebook page

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#48]
This may have been impacted by the changes from Issue #43 , I don't know, but now when I am on the Builder's Notebook page, and I click on any of the posts there, nothing happens.
http://cms.zigbop.io/posts
![2](https://cloud.githubusercontent.com/assets/5215893/6065072/5d3d7f2c-ad30-11e4-9436-4265a43680db.png)

**Comment by acavanagh** [comment]
You're right, it was fallout from fixing that issue.  It's been corrected.
