### ISSUE TITLE
Admin settings page doesn't update

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#49]
I'm reviewing the Admin Settings page http://cms.zigbop.io/settings/1/edit

It doesn't appear to save any of my changes. I am pretty sure that several of these fields are irrelevant in the dark theme, but since I can't make any updates to check, I can't finish reviewing the page. Should it be uneditable?
![4](https://cloud.githubusercontent.com/assets/5215893/6066234/99f5ef5e-ad39-11e4-8afb-c3cb1288333a.png)

**Comment by acavanagh** [comment]
This should be editable again now.
