### ISSUE TITLE
Re-reorder the field on Admin Pages

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#50]
On the Admin Pages page, the order of pages in the center should probably mirror the order over in the left sidebar (including the sub-pages of Our Company:

Our Company
Our Process
Testimonials
News & Awards
Builder's Notebook
Contact Us

All Projects can go away. I think that's a link to Portfolio in the light theme, but that is not editable in the dark theme, so let's not have it on the page list.

http://cms.zigbop.io/pages
![5](https://cloud.githubusercontent.com/assets/5215893/6066337/569388e2-ad3a-11e4-931c-cdaedc3ddef3.png)

**Comment by acavanagh** [comment]
Just made the changes, see if it's what you're looking for.

**Comment by meetinghouse** [comment]
That looks good, and just like what I asked for. Now that we've turned back on the Admin Projects page, however, could we put "Portfolio" in the list just above News & Awards? It won't have an edit button, like Builder's Notebook doesn't.

So the link should read "Portfolio" and it should link to the Admin Projects page
http://shconstruction2.corbettresearchgroup.com/admin/projects

**Comment by meetinghouse** [comment]
Looks good, thanks.
