### ISSUE TITLE
Admin Projects page

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#51]
There is an Admin Projects page in the dark theme, but it is not applicable here.

Would it be easy to change this page to show each project, its tags, and the assigned sort order, with the tags and weight editable right there?

If that's not feasible, I think this page should just be dropped.

http://cms.zigbop.io/admin/projects
![Uploading 6.png . . .]()

**Comment by acavanagh** [comment]
It's feasible, but it would take an hour or so.  Say the word and I'll make it, otherwise I'll just hide it for the dark theme.

**Comment by meetinghouse** [comment]
After consulting with John, I think we can just hide this page for now, please. It would be sort of handy for working with the whole list of projects, but the portfolio is serving a different purpose in the dark theme than in the light theme, so for now, let's just hide the page.

**Comment by acavanagh** [comment]
Sure.  Hidden now.

**Comment by meetinghouse** [comment]
Since John has been identifying changes for this page to make it work for the dark theme, it looks like it should be unhidden again. Could you put the link for it back in the top menu (not sure of the actual name for the menu, but the black admin menu at top of screen when logged in), after Admin Pages and before Admin Settings?

**Comment by acavanagh** [comment]
funny, when I was working on the font formatting issues and the hiding related portfolios issues I was thinking "I thought we weren't using this page in the dark theme, guess I was wrong".  I'll unhide the menu item.

**Comment by meetinghouse** [comment]
This looks good, thanks.
