### ISSUE TITLE
Verbiage correction in Profile page

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#52]
In both the dark and light themes, there is a punctuation thing that is just driving me crazy. This is so simple, it seems like I should just change it myself but I don't really know where to do that. I'm not sure I really want to know, frankly.

The text reads "Update your info below eg password, email etc"

It desperately needs some punctuation. This would be better: "Update your info below (e.g., password, email, etc.)"

http://cms.zigbop.io/users/1/edit
![7](https://cloud.githubusercontent.com/assets/5215893/6066492/64d58d14-ad3b-11e4-9c30-3f60a644db20.png)

**Comment by acavanagh** [comment]
You're right, that's painful.  Fixed now for both themes.
