### ISSUE TITLE
Please make "Maintenance Mode" the default

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#53]
When a new site is launched, it would be best if maintenance mode were the default so that search engines don't crawl it when it isn't ready yet. It looks like it is not the default right now. Can you set it so that it is?

**Comment by acavanagh** [comment]
Maintenance mode should now be the default when rolling out a new site.  One of the steps in your deploy script gets a database that's all set up and copies it to the new site.  That database now has maintenance mode switched on.  Additionally, there's another database in there that will work for the dark theme.
