### ISSUE TITLE
Add "Create" button for Portfolio and Builder's Notebook

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#54]
I am attempting to upload some content to the newly launched sh test site (http://shconstruction2.corbettresearchgroup.com/) and I've found something I should have really caught earlier.

There's no way to add a new blog post or project. No add button. Can you put an "Create" button on the Builder's Notebook page (http://cms.zigbop.io/posts) when the user is logged in, and also a "Create" button on the Portfolio page (http://cms.zigbop.io/portfolio)? The create button could be in the same spot as the "Edit" button is on other pages, and formatted similarly, I think.

**Comment by acavanagh** [comment]
Wow, I hard to believe that we both missed that.  I'll put a button up
asap.  In the meantime, if you want to add posts or projects you can go to
http://shconstruction2.corbettresearchgroup.com/posts/create or
http://shconstruction2.corbettresearchgroup.com/projects/create
respectively.
