### ISSUE TITLE
Error when uploading image to blog post

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#55]
Using the /create URL you e-mailed me earliert, I successfully created a blog post. That was good!

But now, when I attempt to upload an image, I receive an error message, attached.

http://shconstruction2.corbettresearchgroup.com/posts/1

![screenshot 2015-02-12 at 2 25 22 pm](https://cloud.githubusercontent.com/assets/5215893/6175396/63aa2bf0-b2c4-11e4-9386-8d895f31f7e5.png)

**Comment by acavanagh** [comment]
that's a permissions issue on the server.  I think I just fixed it - can
you try again?

**Comment by meetinghouse** [comment]
I'm not getting the error anymore. However, I can only upload one image to a blog post now. I think I was able to upload multiples before??? Anyway, I should be able to upload multiple images, aside from the main one.

**Comment by meetinghouse** [comment]
Because there are other issues dealing with this same page, to avoid confusion, I am withdrawing this one.
