### ISSUE TITLE
Project Tile Image Uploader reverts to Top Image

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#58]
The Tile Image Uploader appears to be working and we can upload images there. It displays on the portfolio page correctly.

However, if any subsequent updates are made to the project, then the tile image then changes to display the Project Top Image instead. 

For instance, this page http://shconstruction2.corbettresearchgroup.com/projects/15/edit
![screenshot 2015-02-25 at 11 51 55 am](https://cloud.githubusercontent.com/assets/5215893/6375389/b6a2e0b6-bce4-11e4-9a5e-913ea3666b24.png)

**Comment by acavanagh** [comment]
this one should be fixed now, if you give it a few minutes to deploy and
try you should see the correct image stick.
