### ISSUE TITLE
PROJECTS SUBSEQUENT IMAGE UPLOADER, EDIT

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#59]
Enable Subsequent Image Caption Edit on the Project Edit screen (http://shconstruction2.corbettresearchgroup.com/projects/15/edit)

![screenshot 2015-02-25 at 11 54 59 am](https://cloud.githubusercontent.com/assets/5215893/6375449/27dffb38-bce5-11e4-9f7a-242965b994f5.png)

The issue is that after Subsequent Image Creation, there is no way to Edit the Caption. Let me know if this is unfeasible.

**Comment by acavanagh** [comment]
Are we using captions on the dark theme?  I don't think they get displayed
anywhere, do they?

**Comment by meetinghouse** [comment]
Andy,

Captions are displayed on all of the Subsequent Images. See
http://shconstruction2.corbettresearchgroup.com/bauhaus_new_construction


Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748

**Comment by acavanagh** [comment]
not sure how I missed that.  I'll turn the edit back on for the dark theme.

**Comment by acavanagh** [comment]
fixed
