### ISSUE TITLE
Enable image sorting in project edit screen

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#60]
Currently there is no way to sort the images in the Subsequent Project Images Uploader section of the Project Edit and Create screens. Can a weight or sort order be displayed for each image upon creation, and then be available for editing later?

![screenshot 2015-02-25 at 11 54 59 am](https://cloud.githubusercontent.com/assets/5215893/6375490/68ed7ae2-bce5-11e4-8eb1-62b31ef15160.png)

**Comment by acavanagh** [comment]
done

**Comment by acavanagh** [comment]
sorry, I must have wiped this out with one of the subsequent changes.  I'll restore it tonight.

**Comment by meetinghouse** [comment]
I'm able to set the weight for the images, but I can't actually see the text in the Image Position box as I type it. 

I can see the numbers when I go back after updating, but if I click on it I get a dropdown to choose from instead of the ability to type in the box. I can type in the box, actually, and I can save it, but I can't see it as I do that.

Can the box just be a normal text box that can be typed in?
http://shconstruction2.corbettresearchgroup.com/projects/15/edit
![screenshot 2015-02-26 at 12 08 22 pm](https://cloud.githubusercontent.com/assets/5215893/6397294/b2755e4c-bdb1-11e4-98a9-2c9d527d7fab.png)

**Comment by acavanagh** [comment]
should be better now

**Comment by meetinghouse** [comment]
Yes, that looks good now. Thanks.
