### ISSUE TITLE
Font format on the Admin Projects page

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#62]
The text on the white lines of the Admin Projects page is a light gray, which is pretty hard to read. Can you make it a darker gray? If this is a change we should do ourselves, please let me know.

http://shconstruction2.corbettresearchgroup.com/admin/projects
![screenshot 2015-02-25 at 12 07 21 pm](https://cloud.githubusercontent.com/assets/5215893/6375716/dd3334fe-bce6-11e4-80cf-e71938f3b5dc.png)

**Comment by acavanagh** [comment]
darker now
