### ISSUE TITLE
Related Portfolio on Admin Projects page not showing correct information

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#63]
The “Related Portfolio” column shows the item “Masonry Repair”. This seems to be a database value from the previous content, a legacy item. Can this be removed or changed to reflect the tags for the project? If changed to show tags, please change the heading to read "Related Tags."

http://shconstruction2.corbettresearchgroup.com/admin/projects

![screenshot 2015-02-25 at 12 07 21 pm](https://cloud.githubusercontent.com/assets/5215893/6375745/11e44fbc-bce7-11e4-9972-17512846f9b0.png)

**Comment by acavanagh** [comment]
Removing it for now.
