### ISSUE TITLE
Page Edit button doesn't work

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#65]
When logged in, the edit button on the Our Company page doesn't work. I can mouse over it and it looks like it is going to work, but I can't click it. It appears to be the same for other pages as well. The edit button DOES work from the Admin Pages page, so that is good, but the edit button on the left sidebar of each of the pages also needs to work.

Here are the pages for which the edit button is currently not working:

Our Company
http://shconstruction2.corbettresearchgroup.com/about

Our Process
http://shconstruction2.corbettresearchgroup.com/our_process

Testimonials
http://shconstruction2.corbettresearchgroup.com/testimonials

News & Awards
http://shconstruction2.corbettresearchgroup.com/news_awards

Interestingly, the Contact Us page edit button works fine.
http://shconstruction2.corbettresearchgroup.com/contact

**Comment by acavanagh** [comment]
fixed
