### ISSUE TITLE
ENABLE BLOG IMAGE UPLOADER UI

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#66]
[“Default Image Uploader” produces error below at Create:
Intervention \ Image \ Exception \ NotWritableException
Can't write image data to path (/home/forge/shconstruction2.corbettresearchgroup.com/public/img/posts/thumb/blogframing.jpg)
The image attempted was a jpg filesize 70KB and dimensioned 600 x 600 px.]   [Previous exchange]

CURRENT ISSUE - - - Blog Image Uploader, at Create Blog Post, now produces “on page” (User returned to same page), UI error at Create:

"The image must be a file of type: jpeg, bmp, png, gif, jpg."

The file attempted was a previously uploaded (uncorrupted)  jpg., 850px wide, under 300KB. Tested multiple jpgs. Still nothing.

**Comment by acavanagh** [comment]
I can now create blog posts with all images working, I think this was fixed alongside another ticket - can you test again and confirm that it works?

**Comment by meetinghouse** [comment]
The blog image uploader works without the error now on the create screen.
