### ISSUE TITLE
FIX CREATE BLOG POST FAILURE MESSAGE

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#67]
Let’s stop Error message. Continuing from the Blog Image Uploader failure (see ENABLE BLOG IMAGE UPLOADER UI), if we omit the failed Image Upload, that is if we Create the Post text only, no Image, we get the system error:

InvalidArgumentException
Route [posts] not defined.

BUT, in fact, the Post DOES show at Builder’s Notebook, in spite of the Error. Without the Image. The program is unhappy about something, obviously, but is not good at expressing it.

**Comment by acavanagh** [comment]
image and route fixed

**Comment by meetinghouse** [comment]
Error no longer occurring, looks good.
