### ISSUE TITLE
CHANGE BLOG POST EDIT UPLOAD IMAGE DISPLAY SIZE

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#68]
Display Blog Images at uploaded size. Blog Images display at 850px, no matter the size of the image. An image uploaded width 600 or 335px both display at 850p. Display Blog Images at uploaded size.

**Comment by acavanagh** [comment]
Are you talking about the top 'default' image or the supplemental images?

**Comment by meetinghouse** [comment]
All images that appear on the individual blog post pages, please. The thumbnails that appear on the portfolio page do need to be the special size. Currently, they are being cropped. That may get addressed later, but for now I'm only talking about the pictures as they display on the post page.

For instance, this photo on this page may be a little distorted because of the display. It looks a little distorted.

http://shconstruction2.corbettresearchgroup.com/european_design
![screenshot 2015-02-26 at 1 05 18 pm](https://cloud.githubusercontent.com/assets/5215893/6398227/3799d0fc-bdb8-11e4-8820-95444d94411a.png)

**Comment by acavanagh** [comment]
ok, they should all be original size up to 850px.  Hopefully it won't look weird.  It's easy to put it back if it does.

**Comment by meetinghouse** [comment]
The images are now showing at whatever size they are, in all their inconsistent glory.
