### ISSUE TITLE
FURNISH BLOG TITLE TAGS

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#70]
Please furnish “Browser Results” or “Title Tag” field for each of the three types of Blog pages, 

(1.) Builder’s Notebook (Blog) page, 
(2.) subsidiary “Tag” (sub-Blog) pages (such as “Home Energy Systems”) and 
(3.) for the Post pages themselves, such as /smart_home_systems.  

Currently, they all default read “S and H Construction, Inc.”

**Comment by acavanagh** [comment]
title tags added

**Comment by meetinghouse** [comment]
I see that the title tags have been added all three places.

I tested the title tag for a blog post and it reflected correctly. When I deleted it again, the title tag defaulted to the URL.

Instead of this, can you make this a required field?

**Comment by acavanagh** [comment]
yes

**Comment by meetinghouse** [comment]
Great. Let me know when the field has been changed to be required.

**Comment by acavanagh** [comment]
it should now be required

**Comment by meetinghouse** [comment]
Yeah, I see that it is now required. Thanks.
