### ISSUE TITLE
Trouble deploying site, and new SSH key

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#71]
I attempted to create a new site (light theme) today
LIBERTYCONSTRUCTION.CORBETTRESEARCHGROUP.COM
using the same deployment procedure as always.

It is not working. I have checked my procedure several times and I think it is correct, but still, I get this page when I try to visit the new site:
![screenshot 2015-02-26 at 2 35 21 pm](https://cloud.githubusercontent.com/assets/5215893/6400078/b5f1ba8a-bdc4-11e4-8b23-cd557945d086.png)

I have not seen that before. 

I also see a new server in Forge called icy-winter and have an e-mail from Feb 11 alerting me (well, John, really, but I have a copy) that a new public SSH key has been added to GitHub for this server.

Do you know anything about this new server, and whether it may be connected with my inability to launch a new site?

**Comment by acavanagh** [comment]
I added that server when I thought you wanted me to set up the new dark
theme site on a different server.  I'll delete it next time I'm in there.

as for the light theme site, I'll check it out and let you know what I find.

**Comment by acavanagh** [comment]
oh.  it's in maintenance mode.  one of you asked me recently to change the
default settings so that the sites would be in maintenance mode when they
first get deployed.  You just have to go to /login and log in.  You can
change the settings to take it out of maintenance mode whenever you're
ready.

**Comment by meetinghouse** [comment]
Andy,

I see this! Thanks for the info...I'll try to get it done in the morning.


Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748

**Comment by acavanagh** [comment]
I took the liberty site out of maintenance mode already. Should be all set.

**Comment by meetinghouse** [comment]
Thanks. I've updated our documentation to note that for any newly deployed sites we will have to login to view them. And I see the liberty site just fine now.
