### ISSUE TITLE
Create supplemental css file

### ISSUE THREAD

**Issue by acavanagh** [meetinghouse/cms#72]
- add file create to deployment step
on master branch:
- add file to .gitinore
- add link to file to master blade template
- merge change into blog branch also

**Comment by meetinghouse** [comment]
Happy to see movement on this item. I spoke with John today and he is keen to move this up in priority. Let us know when there is a css file available for both light and dark themes, and how to access it. And any warnings or caveats, too. Thanks.

**Comment by acavanagh** [comment]
everything is in place.  To add the supplemental css file to any site you want, add the following line to the deploy script:
touch public/assets/css/customProject.css
then run a deployment.  That will add a customProject.css file that will get scooped in to the site.

Don't forget to remove the line from the deploy script after the file has been added.

**Comment by meetinghouse** [comment]
Thanks! Two questions: should these two extra lines of code be tacked on right to the end of the current deploy code? And do you know how I can access this css file? I know that's more of a sys admin question.

**Comment by acavanagh** [comment]
I think right on the end would be fine.  Do you know if your sysadmin
person set up sftp access to your website server?

**Comment by meetinghouse** [comment]
Andy, do the supplemental css files actually exist yet, or did you just script the possibility of creating them? I would like to poke around and see if I have access to them (or get access if I don't have it currently), but do I need to redeploy some sites in order to do so? I am being careful about running redeploy code now.

**Comment by acavanagh** [comment]
mmm, now that I think about it I only added that to the master branch.  I
don't think I merged that in to the blog branch yet, which is the one we're
using now.  I'll do that tonight.  That said, it does exist on
steeplejacksworld.corbettresearchgroup.com, so you can test things there.
It's in /home/forge/
steeplejacksworld.corbettresearchgroup.com/public/assets/css/customProject.css

**Comment by acavanagh** [comment]
I just merged that code in to the blog site, but the sites will need to be
updated

**Comment by meetinghouse** [comment]
Hi. We're revisiting this issue now. It'll be on John's high priority list. When we try to go to the address you listed above, 
steeplejacksworld.corbettresearchgroup.com/public/assets/css/customProject.css

I get an error. This is a screenshot of it. I'm not actually sure what I should be seeing instead.

![screenshot 2015-06-10 at 12 06 18 pm](https://cloud.githubusercontent.com/assets/5215893/8087482/30192ad2-0f69-11e5-94ae-4c9fb279b201.png)

**Comment by acavanagh** [comment]
You should be seeing a more normal 404 not found message.  Looks like I
have to shut off detailed error reporting.

**Comment by meetinghouse** [comment]
Andy,
This is not about the Error message as such but rather that the css file that we sought at your example:
steeplejacksworld.corbettresearchgroup.com/public/assets/css/customProject.css
was not visible. WE MAY BE UNCLEAR ON THE CONCEPT!  And not for the first time. Should we be able to view the customproject.css at the example URL given?
Best,
John C.

**Comment by meetinghouse** [comment]
Andy,
We got the path to work by leaving the /public folder out of the path, so we can close this out, for now. One more down...
Thanks,
John C.

**Comment by acavanagh** [comment]
right, if you're accessing it in the browser you wouldn't use the public
part, but when you're creating the file with the deploy script (noted in
the other ticket) you'll need to be sure to include it, and when you're
accessing the server to edit it you'll also need the full path.

**Comment by meetinghouse** [comment]
Andy,
Got it. I am still looking for this file. What is the path to what server to find/edit/download this file? I have numerous logins for Forge. Is it the Sudo login? Where do I enter it? I tried the main /auth/login, and was refused.
Best,
JC

**Comment by meetinghouse** [comment]
Never mind!
;-)
JC
