### ISSUE TITLE
Slideshows not displaying on Our Company or Our Process pages

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#74]
Issue #28 was to resolve the slideshow not displaying on the Our Process page. I can see that it was resolved on the staging site. However, on the deployed site the slideshow is not displaying on either the Our Process page or the Our Company page.

I uploaded images to shconstruction2.corbettresearchgroup.com for both pages, but they are not displaying. The example below is just for the Our Company page, but the same applies for the Our Process page. You can see that I uploaded images in the edit page, though thumbnails are not showing (that' the first screenshot)

http://shconstruction2.corbettresearchgroup.com/about
![screenshot 2015-03-03 at 12 43 06 pm](https://cloud.githubusercontent.com/assets/5215893/6468414/dd3c0c4e-c1a2-11e4-8e53-a46e39b643ac.png)

And here is the Our Company page when viewed, not in edit mode:
![screenshot 2015-03-03 at 12 45 03 pm](https://cloud.githubusercontent.com/assets/5215893/6468456/21df35ec-c1a3-11e4-9fdf-1a7a8ae02bd0.png)

**Comment by acavanagh** [comment]
should be all set now, just didn't have the permissions set on the server for that folder to accept uploads. (issue #78 )

**Comment by meetinghouse** [comment]
Looks good now, thanks.
