### ISSUE TITLE
Possible to have a pdf uploader?

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#75]
This is just a question about whether it is feasible to have the ability to upload pdf's to the server in the dark theme and be able to link to them within the content fields of the various pages. 

For instance, S+H's current site is in Drupal, and if they have a new press release, say, they send me a PDF. I save that PDF directly on the server, and then insert a link in the body text to that page. Here is an example:
http://shconstruction.com/content/press-releases
![screenshot 2015-03-03 at 1 05 11 pm](https://cloud.githubusercontent.com/assets/5215893/6468831/f2f54d68-c1a5-11e4-855a-0a6ae7cbbca2.png)

then when you click the first link on that page you see the PDF being referred to:
http://shconstruction.com/pr/S+H-CONSTRUCTION-NAMED-BEST-OF-BOSTON-HOME-2015.pdf
![screenshot 2015-03-03 at 1 06 12 pm](https://cloud.githubusercontent.com/assets/5215893/6468850/16a245d6-c1a6-11e4-9f8b-438cf63f6d3d.png)

**Comment by acavanagh** [comment]
can't you do that already by selecting the link button in the editor and selecting upload?
https://www.dropbox.com/s/ruenlctd3h36rha/Screenshot%202015-03-03%2020.54.59.png?dl=0

**Comment by meetinghouse** [comment]
Ummmmmm, yeah I can. Derp. Thanks, this looks good then.
