### ISSUE TITLE
Blog Post Publish checkbox functionality

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#76]
Similar to issue #61 for Projects, I notice that the publish checkbox for the Blog posts does not work. For instance, the blog post called "Test Post" is not marked as published, but does show up on the Builder's Notebook page:
http://shconstruction2.corbettresearchgroup.com/posts/9/edit
![screenshot 2015-03-03 at 1 30 52 pm](https://cloud.githubusercontent.com/assets/5215893/6469337/8b173a22-c1a9-11e4-8351-b6a432f3724d.png)

http://shconstruction2.corbettresearchgroup.com/posts
![screenshot 2015-03-03 at 1 31 45 pm](https://cloud.githubusercontent.com/assets/5215893/6469349/a7322ab4-c1a9-11e4-95d9-818221b99f31.png)

**Comment by acavanagh** [comment]
This should be resolved now.

**Comment by meetinghouse** [comment]
This is fixed and looks good. It raises another issue, though. Now that an unpublished post doesn't appear anymore, there isn't a way to navigate to that unpublished post later to edit it. That doesn't seem good.

I guess we need an Admin Blog page, like the Admin Projects page. And it would need to appear in the top menu when logged in, and on the Admin Pages list. Is that feasible?

**Comment by meetinghouse** [comment]
Just for clarity, I just reviewed this issue, and want to make sure it is clear what the request is (since it drifted a bit from the original request). In the Dark Theme, we need an Admin Blog page, which is pretty much like the Admin Projects page, only showing Blog Posts rather than Projects. This will enable the user to manage blog posts, whether published or unpublished.

**Comment by acavanagh** [comment]
You should have an admin page for the blogs.  Visible at http://example103.corbettresearchgroup.com/.  When we enable blogs for the light theme it'll be there too.

**Comment by meetinghouse** [comment]
This looks totally great. I tested it for unpublished and published blog posts both and it worked fine. Thank you!

Am I safe to deploy code to shconstruction2.corbettresearchgroup.com

I'd like to do that myself to make sure it works, but would like the green light so I don't break things.

**Comment by acavanagh** [comment]
go for it!  let me know how it goes.

**Comment by meetinghouse** [comment]
It is fine and the Admin Posts page is now avaiable for shconstruction2. Thank you so much! This is an excellent boost for usability of the blog. Closing now.
