### ISSUE TITLE
Cannot view Builder's Notebook when not logged in

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#77]
I just visited the SH website while NOT logged in and noticed that if I try to navigate to Builder's Notebook I am prompted to login. That surely isn't right!

So, starting on the homepage
http://shconstruction2.corbettresearchgroup.com/

I click Builder's Notebook in the left nav and get the login page
http://shconstruction2.corbettresearchgroup.com/login

**Comment by meetinghouse** [comment]
Do you want me to assign issues to you, by the way? I have mostly not been doing so, but occasionally I get a wild hair and assign it. That is probably annoying. Which is preferable?

**Comment by acavanagh** [comment]
Probably easier to assign them to me from the start, but not a big deal
either way.

**Comment by acavanagh** [comment]
should be all set now

**Comment by meetinghouse** [comment]
Looks good, thanks.
