### ISSUE TITLE
Light Theme: Collapse Portfolios in left nav bar

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#79]
In the light theme, the various portfolios that a user creates then show up as separate buttons on the left nav bar under "Links." 
http://steeplejacksworld.corbettresearchgroup.com/
![screenshot 2015-03-04 at 12 13 47 pm](https://cloud.githubusercontent.com/assets/5215893/6488808/f36bc840-c267-11e4-9edc-68139dbefe80.png)

In order to make the left nav bar buttons more mobile-friendly, John would like to have the default view of the left nav just have a button that is labeled "Portfolio" and if it is clicked/touched, then the whole list of user-created sub-portfolios will show as buttons. Is this feasible?

**Comment by meetinghouse** [comment]
After speaking with John today, this issue is also a priority, just below Issue #72. Thanks.

**Comment by acavanagh** [comment]
Is this what you're looking for:
https://www.dropbox.com/s/u8nngxzq7qbvvad/collapse_nav.mp4?dl=0

do you have a deployed site handy that I can test it out on?

**Comment by meetinghouse** [comment]
No, this isn't quite what we had in mind. Sorry to have not provided full specs. Instead of collapsing all the links into just one that says "Portfolios", can you collapse only the sub-portfolios into the one heading "Portfolios."

In other words, there should be five links in the left nav bar when the page loads: Portfolios, About Page, Contact Page, All Projects, and Home. They don't need to be different fonts. They can all be the same font that they currently are. The goal is to limit the number of buttons to five to be more google mobile friendly.

Can it also be set so that "Portfolios" opens into a list of the sub-portfolios (e.g., Structural Restoration, Masonry Repair) upon mouse-over rather than needing to click?

Here is the deployed site I've been using for light theme work lately:
http://steeplejacksworld.corbettresearchgroup.com

**Comment by meetinghouse** [comment]
Andy, after looking at some sites today on smaller screens, John has a slight change to this request. I will try to just give a full spec here again in this comment in the hopes of being totally clear.

Can the left nav be set so that upon loading the homepage, four links appear on it rather than the one that currently appears:
Home
Portfolios
About page
Contact page

When a visitor clicks the Portfolios link, the nav bar should expand to show what it shows now when Portfolios is clicked.
Here is how it looks now:
http://steeplejacksworld.corbettresearchgroup.com/
![screenshot 2015-03-25 at 1 45 08 pm](https://cloud.githubusercontent.com/assets/5215893/6831209/32516108-d2f5-11e4-92d0-d0fe3eba850f.png)

Here is how it looks now when "Portfolios" is clicked:
![screenshot 2015-03-25 at 1 45 39 pm](https://cloud.githubusercontent.com/assets/5215893/6831263/9ceb0352-d2f5-11e4-92d9-1fe88734b412.png)

**Comment by acavanagh** [comment]
check it out now, I think it's more like what you're looking for.

**Comment by meetinghouse** [comment]
Yes, that is super awesome. One small request, though -- it looks like the Portoflios link is a little indented. Maybe there's just an extra space there, I don't know. But other than that, looks good.

**Comment by meetinghouse** [comment]
I know this is super nit-picky, but the little indent at the beginning of the word Portfolios in the sidebar on the light theme is sort of driving me crazy. I think this may have gotten lost in all the millions of issues. Could it possibly be changed?

**Comment by acavanagh** [comment]
I think this is straightened out now.  You can see the difference at
http://coloralchemist.corbettresearchgroup.com/admin.  Have to update the
code on other sites to see it.

**Comment by acavanagh** [comment]
speaking of updating the other sites, are there any in that list that
you're not going to use?  I don't want to waste your time/money updating
stuff that's not necessary.

**Comment by meetinghouse** [comment]
Yay, the space is gone. Does my picky heart good.

As far as which sites to update and which ones not to, I have to answer your question with another question:

If we opt to only update a certain set of sites right now, will there be a time in the future when it will be possible to push all the most current code to all the sites at one go? Or must there be manual shenannigans forever and ever for the sites that exist right now before they can get updated?

**Comment by acavanagh** [comment]
There's only two things preventing manually pushing updates to all the code:

1.  The extent of the changes we've made right now requires a little extra
attention.  this is a one-time thing, unless we do another extensive
re-write.
2.  There's an issue we're having in forge with automatic deployments.  I
contacted their support and they think it's because the github user who set
up the site doesn't have admin privileges for the repository.  I'm trying
to figure out what that actually means, I'll let you know as soon as I do.

Once those two things are resolved you should have automatic, system wide
deployments any time the code is updated.

**Comment by meetinghouse** [comment]
It looks like this one is all done, so I'm closing it. Thanks.
