### ISSUE TITLE
Change width of top space above images on several pages

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#80]
At the top of several screens that lead with images in the Dark Theme, there is some dead space. John would like to make that dead space uniformly 35 pixels high. Is that feasible?

Here is a list of the pages, with links, that will need changing, and one screenshot for an example:

Portfolio page (http://shconstruction2.corbettresearchgroup.com/portfolio)
Individual project pages (http://shconstruction2.corbettresearchgroup.com/european_modern)
Our Company (http://shconstruction2.corbettresearchgroup.com/about)
Our Process (http://shconstruction2.corbettresearchgroup.com/our_process)
Builder's Notebook (http://shconstruction2.corbettresearchgroup.com/posts)

![screenshot 2015-03-04 at 12 24 25 pm](https://cloud.githubusercontent.com/assets/5215893/6489068/7f125dea-c269-11e4-8158-2bfc1223f5b4.png)

**Comment by acavanagh** [comment]
Those pages all now have 35px padding above the image

**Comment by meetinghouse** [comment]
I see that the leading image is lined up with the logo on the pages with slideshows (Our Company, Our Process), but only when I am logged in. It looks the same as before when I am logged out.

I don't see a change to the way the leading images are lined up on the Portfolio or Builder's Notebook pages, whether logged in or out.

**Comment by meetinghouse** [comment]
Consolidated in Issue #157, so closing this one.
