### ISSUE TITLE
Slideshow not displaying on Our Process Page

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#81]
In issue #74, the ability to upload images and have them display on the Our Company and Our Process pages was fixed. I was able to see the images on both pages, but later when I navigated to the Our Process page from the link on the left nav bar, the images are gone. I can see them if I go to Our Process from the Admin Pages page, but not when I go to it from the left nav bar. This is the case both when I am logged in or logged out.
http://shconstruction2.corbettresearchgroup.com/our_Process
![screenshot 2015-03-04 at 12 30 37 pm](https://cloud.githubusercontent.com/assets/5215893/6489170/48303292-c26a-11e4-8bd6-c1f353427277.png)
When I get to this page from the Admin Pages page (http://shconstruction2.corbettresearchgroup.com/pages), it looks like this, with the slideshow.

When I get to it by clicking in the left nav bar, it looks like this
![screenshot 2015-03-04 at 12 31 33 pm](https://cloud.githubusercontent.com/assets/5215893/6489190/698a676e-c26a-11e4-90c9-f0d7c0a578fd.png)

**Comment by acavanagh** [comment]
this should be fixed now

**Comment by meetinghouse** [comment]
This is fixed! But now the slideshow doesn't display when I navigate to the Our Process page from the Admin Pages screen. That's kind of weird. It is the reverse of the original state of things when I submitted this issue.

**Comment by acavanagh** [comment]
this should be all set now

**Comment by meetinghouse** [comment]
Looks good now, thanks.
