### ISSUE TITLE
Logo shows at different sizes on different pages

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#82]
I noticed as I clicked through the pages of the Dark Theme that the Company logo doesn't appear the same size on all the pages. From eyeballing it, I think it is larger on the following pages:
Builder's Notebook (http://shconstruction2.corbettresearchgroup.com/posts)
Individual blog posts (http://shconstruction2.corbettresearchgroup.com/smart_home_systems)
Portfolio (http://shconstruction2.corbettresearchgroup.com/portfolio)
Individual Project pages (http://shconstruction2.corbettresearchgroup.com/european_modern)

**Comment by acavanagh** [comment]
This should be standardized now

**Comment by meetinghouse** [comment]
This looks good. Thanks.
