### ISSUE TITLE
Subsequent Images in Project Create Screen not sortable

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#84]
In the project edit screen it is possible to specify the position for the subsequent images, but in the project create screen it is not. 
http://shconstruction2.corbettresearchgroup.com/projects/create
![screenshot 2015-03-04 at 1 38 02 pm](https://cloud.githubusercontent.com/assets/5215893/6490393/f0f86c6a-c273-11e4-9c73-2f4e07f04cde.png)

Could you please add that under the Caption field so it mirrors what's in the Project edit screen?
http://shconstruction2.corbettresearchgroup.com/projects/15/edit
![screenshot 2015-03-04 at 1 39 56 pm](https://cloud.githubusercontent.com/assets/5215893/6490396/f9083976-c273-11e4-9311-10eda2b86dad.png)

**Comment by acavanagh** [comment]
This should also be working now

**Comment by meetinghouse** [comment]
Looks good, thanks.
