### ISSUE TITLE
Where are help links for these project fields?

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#85]
I am updating help text links across the light and dark themes, but there are a few I can't locate. 

I expected to find all the help links that appear on the Project Edit page (http://shconstruction2.corbettresearchgroup.com/projects/16/edit) in this file:
cms/app/views/projects/edit.blade.php

But I don't see it for the following fields, which do have a Help link next to them on the page:
Tags (above URL)
And in the Subsequent images section:
Image Caption
Image Position

Can you tell me where to find these so I can edit them?

**Comment by acavanagh** [comment]
They're in cms/app/views/shared/tags.blade.php and cms/app/views/shared/images_angular.blade.php

**Comment by meetinghouse** [comment]
Thank you. I finally finished all the help links!
