### ISSUE TITLE
Change font of left nav bar

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#87]
Is it possible to change the font of the left nav bar to be the same as it is on the homepage right now on every other page?
Here's the font that is wanted:
http://shconstruction2.corbettresearchgroup.com/
![screenshot 2015-03-11 at 10 54 05 am](https://cloud.githubusercontent.com/assets/5215893/6598898/fde8b06a-c7dc-11e4-8ae5-867028567612.png)

Here's what appears on other pages currently:
http://shconstruction2.corbettresearchgroup.com/portfolio
![screenshot 2015-03-11 at 10 54 49 am](https://cloud.githubusercontent.com/assets/5215893/6598913/0e887ec8-c7dd-11e4-9c80-8ee798ae19bc.png)

**Comment by acavanagh** [comment]
They are the same, you just can't see the text shadow on the dark background

**Comment by meetinghouse** [comment]
Oh. Heh, that's embarrassing. Thanks.
