### ISSUE TITLE
Please truncate text on Tags pages

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#89]
On the tags page, http://shconstruction2.corbettresearchgroup.com/projects/tags/Modern%20Architecture
![screenshot 2015-03-12 at 2 59 06 pm](https://cloud.githubusercontent.com/assets/5215893/6625743/59a10aa6-c8c8-11e4-930d-9c5433af64d1.png)

all the text for a project displays. This pushes the next project way down the page and doesn't entice the visitor to click through to see more if they are interested. Can you please truncate this the way the text on the blog page is truncated? 
http://shconstruction2.corbettresearchgroup.com/posts
![screenshot 2015-03-12 at 2 59 38 pm](https://cloud.githubusercontent.com/assets/5215893/6625750/6f408684-c8c8-11e4-8416-9e0759a952c2.png)

If you need an exact wordcount, please truncate after 100 words. If it's just the first paragraph break, that's okay too. If you'd like a line count, please truncate after seven lines of the main body text.

**Comment by acavanagh** [comment]
should be all set

**Comment by meetinghouse** [comment]
Looks good, thanks.
