### ISSUE TITLE
Dark Theme: Title tags for Home page

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#91]
We notice that the title tag for the home page is a generic "HOME PAGE SEO," but I don't see a way to update it.

Can a field to update the title tag be added to the Admin Settings page? It should probably come right above the social media links section, below the Logo section.

http://shconstruction2.corbettresearchgroup.com/settings/1/edit
![screenshot 2015-03-17 at 12 26 31 pm](https://cloud.githubusercontent.com/assets/5215893/6692079/dc29f38a-cca0-11e4-9692-23469f27bffa.png)

**Comment by acavanagh** [comment]
You can already edit the title tag on the home page by going to admin/pages and clicking on the edit button next to 'home'
https://www.dropbox.com/s/ys5bj1qlti6xxr6/Screenshot%202015-08-03%2021.50.35.png?dl=0

**Comment by meetinghouse** [comment]
So it is. Sorry to bug you, that was dumb.
