### ISSUE TITLE
Dark Theme: Mysterious tag in Portfolio

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#94]
When I click Portfolio and the list of Project tags comes up, I see the project tag "foo." I may have created this myself as a test tag, I don't know. But I would like to remove it.

I can't find that any projects are actually assigned this tag, even the one unpublished project. Is there a glitch causing this tag to continue to show up? Or do we need some manual way to edit that tags list? That sounds complicated, and I'd rather just have any tags that have no published projects assigned to them either deleted from the db completely or at least suppressed from showing up. Whichever is easiest is fine.

**Comment by acavanagh** [comment]
tag deleted
