### ISSUE TITLE
Dark Theme: Change to be dark text of light background

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#95]
This is a big shift, but how difficult would it be to switch the coloring for all pages in the Dark Theme to show dark text against light background? Like, use the same dark gray that is currently the background to be the text instead, and the same light gray that is currently the font color to instead be the background. I realize this obviates even using the term "Dark Theme," but John would like this color scheme to be the default, even if a client then wishes to change it with the supplementary css file.

**Comment by acavanagh** [comment]
You mean so that it would look something like this:
https://www.dropbox.com/s/yi5ba43foul08ee/Screenshot%202015-03-17%2012.57.13.png?dl=0

Probably surprisingly easy, unless there's some weird edge case that takes
a lot of work.  Could even make a settings switch so you could pick which
way you want it.

**Comment by meetinghouse** [comment]
That is rad. Do eeeet! This dark on light coloration should be the default.

The toggle would be great also, though not available to anyone but the admin user.

**Comment by meetinghouse** [comment]
A question about this change: currently, as the theme stands, when you mouse over a link, the text color changes to being a white or a brighter gray. Can you make sure that whatever the color is when moused over is contrasting enough to be seen? Thanks. Don't want to miss this third color that occurs across the board.

**Comment by meetinghouse** [comment]
Can this issue get bumped up in priority, per John's request? Thanks.

**Comment by meetinghouse** [comment]
Consolidated in Issue #157, so closing this one.
