### ISSUE TITLE
Dark and Light themes: Mobile friendly?

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#96]
This is a basic question, but an important one. Our understanding is that these bootstrap themes are mobile-friendly. Can you confirm that, even with all the changes?

**Comment by acavanagh** [comment]
yes, should still be mobile friendly.  The original theme is built on
Twitter Boostrap, which is an extremely well-tested and popular mobile
friendly framework.  I've used the bootstrap components that the original
theme came with throughout, so it's still very mobile friendly even with
all the changes.  That said, it might be a good idea to resize your browser
to about half the screen (to see what it would do on a tablet) and all the
way narrow (to see what it would look like on a phone).  It will work and
resize gracefully on small screens, but that doesn't mean that there won't
be places where you want to make some adjustments and aesthetic
optimizations.

**Comment by meetinghouse** [comment]
Very helpful answer, thank you.
