### ISSUE TITLE
Light Theme: Add sort order to Portfolio Create Screen

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#97]
I'm creating some portfolios for a client in the light theme. I notice that in the Portfolio create screen there isn't a way to set the sort order. I have to go back into the Portfolio and edit it after the fact. I'm sure this was an oversight. Can you add the Sort order dropdown under the Publish checkbox, just like it is on the edit screen?

Portfolio create screen:
http://steeplejacksworld.corbettresearchgroup.com/portfolios/create
Screenshot showing where the sort order should be but isn't.
![screenshot 2015-03-18 at 11 45 53 am](https://cloud.githubusercontent.com/assets/5215893/6712703/59aa01ce-cd64-11e4-8b9c-87199ce9f483.png)

Screenshot of the edit screen, showing what the sort order should look like and where it should be placed:
http://steeplejacksworld.corbettresearchgroup.com/portfolios/3/edit
![screenshot 2015-03-18 at 11 46 34 am](https://cloud.githubusercontent.com/assets/5215893/6712717/71c270c0-cd64-11e4-95c1-665314835d4c.png)

**Comment by acavanagh** [comment]
ready for review

**Comment by meetinghouse** [comment]
Looks good, thanks.

**Comment by meetinghouse** [comment]
Aw, dangit. I closed this but I see it hasn't been applied across the board because the same thing comes up on another site. Do I need a procedure to roll out changes across sites when they are done?

**Comment by meetinghouse** [comment]
This is now in place for all updated sites, so I'm closing it. Thanks.
