### ISSUE TITLE
Light Theme: Sort order numbers for Portfolios

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#98]
For portfolios I am only able to sort between 1-10, using the Sort Order dropdown. 

Can this please be increased to 20? Thanks.

http://steeplejacksworld.corbettresearchgroup.com/portfolios/3/edit
![screenshot 2015-03-18 at 11 48 03 am](https://cloud.githubusercontent.com/assets/5215893/6712741/a6bde142-cd64-11e4-8463-8c76785378ec.png)

**Comment by acavanagh** [comment]
ready for review

**Comment by meetinghouse** [comment]
Looks good, thanks.
