### ISSUE TITLE
Light theme: URL not updating

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#99]
I have been populating one of the client's test sites in Forge in preparation for rolling them out live, and I made lots of mistakes when assigning URL's to the pages. 

I went back and fixed them, but I notice that the fixes didn't "take." For instance, for the page below I have edited the URL to be /flamenbaum.html but it has reverted to /deco_fence

Can this be fixed? Or is there a period of time I need to wait for URL changes to show up?

http://graneymetaldesign.corbettresearchgroup.com/deco_fence

![screenshot 2015-03-18 at 12 47 57 pm](https://cloud.githubusercontent.com/assets/5215893/6714121/053d7b58-cd6d-11e4-8451-cd138af772a7.png)

**Comment by meetinghouse** [comment]
I should add that this URL not updating issue is occurring on both project and portfolio pages.

**Comment by meetinghouse** [comment]
Adding another detail, sorry. I realize that the URL is not saving and it is giving me an error message why, derp. But I don't know what I am doing wrong. The message is
"The url must start with a slash and contain only letters and numbers, no spaces."

There are no spaces, but there is a period. The URLs on the new site should match the ones from the old site for the purposes of visitor/google statistics. Can the period be allowed?

**Comment by acavanagh** [comment]
I can change the rule to allow for periods.  I'll try to add that in
tonight.

**Comment by acavanagh** [comment]
sorry, I read this quickly and didn't think it through.  Periods are special characters and can't be used as part of a url.  The .html in the old URL is the file extension - like .doc indicates a word document, .doc indicates an html file.  The websites are now dynamic, and don't point to actual files.  You can't have a url that includes html.

What you can do if you want to preserve old links and old seo ranking is to put in a permanent redirect that redirects and request for /whatever.html to just /whatever.  A permanent redirect (301) will make make any links to the .html page continue to work, and will be mostly transparent to any search engine that has the .html version indexed already.

If I recall you have a server guy, he should be able to set this up for you.  If not let me know, I'll have to look up the syntax for the redirect but I can get it done if necessary.

**Comment by meetinghouse** [comment]
I can see what you are saying, and it makes sense. However, the old sites (set up in Bones) are also dynamic sites. Yet they have .html extensions on the URL's. Can you explain how Bones is different from the new software?
ns on the URL's. Can you explain how Bones is different from the new software?

**Comment by meetinghouse** [comment]
Found this code on the graneymetaldesign.com cpanel in the .htaccess file, just loose in the public_html directory. Is there something here that is enabling the ability to have .html in the URL?

IndexIgnore .htaccess */.??* *~ *# */HEADER* */README* */_vti*

<Limit GET POST>
order deny,allow
deny from all
allow from all
</Limit>
<Limit PUT DELETE>
order deny,allow
deny from all
</Limit>
AuthName graneymetaldesign.com

RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L]

**Comment by acavanagh** [comment]
I haven't looked at the bones sites yet, but in the old days people used to
make sites dynamic by writing php directly into the html files.  I'll take
a look at how they're doing it while I'm in there adding the google
analytics code.

**Comment by meetinghouse** [comment]
Andy,

FWIW, this was a program called Mod Rewrite that allowed us to "alias" the
Bones URL's to the pre-existing static URL's. To address your conjecture,
Bones was from scratch, not a modification of a pure html site. This method
only allowed us to impose (alias) our legacy URL's, for Google.

Hope this is helpful and relevant.

Best,

John Corbett

**Comment by acavanagh** [comment]
right, Mod Rewrite is what you'd use to create the permanent redirect that I mentioned above - 

"What you can do if you want to preserve old links and old seo ranking is to put in a permanent redirect that redirects and request for /whatever.html to just /whatever. A permanent redirect (301) will make make any links to the .html page continue to work, and will be mostly transparent to any search engine that has the .html version indexed already."

I suppose you could use it to redirect all of your new pages to end in .html instead, but it's far easier and equivalent for SEO to register a permanent redirect from anything ending in .html to it's non-html equivalent.  In other words, foo.com/page1.html is redirected to foo.com/page1 rather than the other way around. That's sort of the standard way to handle it.  That way old incoming links will still work, and it's the same thing as far as the search engines are concerned - either way the search bots are dealing with a 301 permanent redirect, which they're fine with.  

I could do that in an .htaccess file if you're using apache - you're not on the new sites - but in any case it's not considered best practice because forces the webserver to load an extra configuration file.  Typically you'd put rules like that in your vhost file or equivalent.

**Comment by meetinghouse** [comment]
I never got back to this issue to put updates in it from the email conversation of last week. But John concurs that using a re-direct as you've suggested is good, so please go ahead with it. It will work fine.

Can it please be implemented for the dark theme as well? It may never be necessary, but if it ever is needed, it would be nice to have it already in place. Unless that is a lot of extra work, in which case please let us know beforehand. Thanks.

**Comment by acavanagh** [comment]
I just put in a redirect at the steeplejacks test site.  You'll notice that if you go to http://steeplejacksworld.corbettresearchgroup.com/structural_restoration.html you end up at http://steeplejacksworld.corbettresearchgroup.com/structural_restoration.  That will preserve any incoming links to pages of the same name plus the old .html extension and prevent an seo hit, as the search engines will not notice the difference.

I couldn't figure a way to do it globally, I don't really do that kind of server management, but It's just one line in the site config and I can show Dan where to put it when we go over how to make the sites live.  He probably already knows how to do all this stuff and just needs to be shown where everything is and how it's set up on this server.

**Comment by meetinghouse** [comment]
Hey, just checking in on this. Have you and Dan conferred on it yet? It's not super duper urgent, but will need to happen at some point and that point is drawing every closer. Even more important is conferring on how to launch the real, live sites, from Issue #90. Thanks.

**Comment by acavanagh** [comment]
We emailed back and forth on that last thread, but never went further than
that.  He should contact me directly and I'll walk him through what he
needs to know.  He actually knows more about the server stuff than I do, I
just need to fill him in on the details of how your sites are set up.

**Comment by meetinghouse** [comment]
We've launched one site live so far, Connecticutmason.com, and I tested this out on it. Seems to work just fine, so I'm closing this. Thanks.
